### ISSUE TITLE
2020 AIM Site Catchments

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#101]
@alherca73 there are now 286 AIM sites with catchments online. Here are their names and database IDs.

[2020_AIM_sites_with_catchments.csv.zip](https://github.com/namc-utah/namc-bug-db/files/6232827/2020_AIM_sites_with_catchments.csv.zip)

You can retrieve the site information for each site with the following call in R:

```R
NAMCr::query("siteInfo", siteId= 104843)
```

@FYI @Feldspar5 @courtwrightj01

**Comment by alherca73** [comment]
Thanks. Just curious... why not the 351 AIM2020 watersheds? Is it because you still do not have the latest pilot db?

**Comment by alherca73** [comment]
Or maybe NOT all of these 286 belong to AIM2020?

**Comment by philipbaileynar** [comment]
I can only import catchments for which I have a site record. 

I now have the latest front end database but not the latest backend.

@alherca73 have you cross referenced your site codes with those in both databases?

**Comment by philipbaileynar** [comment]
Closing outdated issue that no longer reflects Alex's priority to get predictor functions coded.
