### ISSUE TITLE
Forest Service Customer Inconsistencies

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#102]
The inconsistent naming of forest service clients is making it really difficult to efficiently relate them together. Here are some examples:

* `USFS_R9_473` (unserscores)
* `USFS-R1-276` (hyphens)
* `USFS-R01` (zero padding)

Can we pick one convention and I will standardize the abbreviations as I import the data into the new database?

Are there downstream problems if I change these customer codes?

**Comment by philipbaileynar** [comment]
Can we use hyphens instead of underscores. It just occurred to me that underscores are wildcards when used in a SQL LIKE query. The following example will match all customers starting with USFS and any single character, not just an underscore:

```sql
SELECT * FROM entity.organizations WHERE abbreviation LIKE 'USFS_'
```

**Comment by Feldspar5** [comment]
yes on hyphens.
