### ISSUE TITLE
Site Catchment Validation

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#103]
I am implementing the API endpoint to validate site catchment polygons. The validation ensures that a catchment intersects the United States. See below. Polygons can straddle the border but they cannot reside entirely outside the united states.

Does everyone agree with this rule?

Notes:

* Without considerable effort, I can't distinguish between polygons that straddle the US and neighbouring countries and those that straddle the US and the ocean.
* I know NAMC has sites outside the United States, but I believe they are:
    * mainly legacy sites and lower priority for site delineation going forward
    * don't require models to be run, which is the main driver for delineating polygon catchments.

<img width="1139" alt="Screen Shot 2021-04-08 at 11 47 02 AM" src="https://user-images.githubusercontent.com/8645379/114081304-3bf39180-9861-11eb-8fd0-51eba5a20023.png">

**Comment by alherca73** [comment]
I think this validation makes sense. However, I am not familiar with any sites that are completely outside the US.
