### ISSUE TITLE
NULL and zero splits?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#109]
Both `lab_split` and `field_split` have lots of values that are either NULL or zero. Are these valid? What do they mean and should we do anything about them?

|Field|Count of NULLs|Count of zeroes|
|---|---|---|
|`sample.samples.lab_split`|7459|169|
|`sample.samples.field_split`|7174|1|

```sql
select labsplit, count(*) from BugSample group by labsplit order by labsplit;
select fieldsplit, count(*) from BugSample group by fieldsplit order by fieldsplit
```

**Comment by David-Fowler** [comment]
Many of these can be corrected I think. Null values in some instances I know indicate we do not know the value (yet all calculations will assume the splits are 100% for those cases). I will look further at the samples as I believe many come from specific externally invested data sources / projects which we can probably assign values to. I will add another comment when I know more.

**Comment by Feldspar5** [comment]
Lab split null values mostly come from samples that have been sorted outside NAMC.  We ask folks to provide this information, but they do not always do so.  In other cases, it might be from presence/absence data ( I am thinking of the mollusk data Chuck had us ingest).  David is accurate in his response, but we should make a decision on how to treat these.  Ideally we would have a value that is not arithmetically operational, but also explains the reason for that value.

Field split should never be 0.

**Comment by philipbaileynar** [comment]
After talking to Trip:

1. Make both `lab_split` and `field_split` required fields.
2. Set legacy records with NULL values to 0 and make an entry in the metadata for these samples noting the data change.
