### ISSUE TITLE
Convert lab_split and field_split to ratio instead of percent?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#111]
@Feldspar5 what do you think of converting all field_split and lab_split values in the database to ratio (0-1) instead of percent (0-100)?

Rationale:

- Less error prone because it makes math simpler and more direct
- the user interface can still present percentages if needed, but we will always store as a ratio.

FYI @David-Fowler

**Comment by Feldspar5** [comment]
This is totally fine.  Sorry for the delays this week - I am in the field training BLM folks but return Sunday.

**Comment by philipbaileynar** [comment]
reassigning to myself to implement.

**Comment by philipbaileynar** [comment]
This is now live in production. Closing.
