### ISSUE TITLE
Predictor Review

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#128]
@Feldspar5 please review the following list of predictors in the system. There are 169 in total. I have attached them here as a CSV file as well as posted them below on this issue. The "model_count" column indicates how many models the predictor is related to in the database.

[2021_04_28_predictors.csv](https://github.com/namc-utah/namc-bug-db/files/6395408/2021_04_28_predictors.csv)

Note that this information is available via the API using the following queries:

```R
NAMCr::query('predictors')
```

And you can get the list of predictors for a particular model with the following call (replacing the modelId with the appropriate value.

```R
NAMCr::query('modelPredictors', modelId=1)
```

And here is how you see all the models in the system and determine their IDs:

```R
NAMCr::query('models')
```

(remember that if you do use the API, that the database might be asleep and the first time you call it might take a while or fail altogether. Simply make the call again and it should be awake.)

| predictor\_id | predictor\_name | abbreviation | units | predictor\_type | is\_temporal | model\_count | models |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 152 | HydrAlt\_km | HydrAlt\_km | ?? | Anthro | false | 0 |  |
| 153 | RdDens | RdDens | ?? | Anthro | false | 0 |  |
| 46 | AtmCa | AtmCa | ?? | Atmosphere | false | 3 | WY - NE Plains \| WY - SE Plains \| WY - Wyoming basin |
| 47 | AtmSO4 | AtmSO4 | ?? | Atmosphere | false | 3 | WY - SE Plains \| WY - Wyoming basin \| WY - NE Plains |
| 48 | AtmMg | AtmMg | ?? | Atmosphere | false | 1 | WY - SE Plains |
| 66 | AtmNa | AtmNa | ?? | Atmosphere | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 67 | AtmNO3 | AtmNO3 | ?? | Atmosphere | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 49 | LST32AVE | LST32AVE | ?? | Climate | false | 1 | WY - SE Plains |
| 50 | MINWD\_WS | MINWD\_WS | ?? | Climate | false | 1 | WY - SE Plains |
| 51 | MEANP\_WS | MEANP\_WS | ?? | Climate | false | 1 | WY - SE Plains |
| 52 | XWD\_WS | XWD\_WS | ?? | Climate | false | 3 | WY - NE Plains \| WY - SE Plains \| WY - Wyoming basin |
| 53 | SumAve\_P | SumAve\_P | ?? | Climate | false | 2 | WY - SE Plains \| WY - Volcanic mountains and valleys |
| 54 | MAXWD\_WS | MAXWD\_WS | ?? | Climate | false | 1 | WY - SE Plains |
| 55 | MINP\_WS | MINP\_WS | ?? | Climate | false | 1 | WY - SE Plains |
| 56 | TMAX\_WS | TMAX\_WS | ?? | Climate | false | 4 | CSCI \| WestWide2018\_OtherEcoregions \| WY - SE Plains \| WestWide2018\_XericEasternPlains |
| 68 | PT\_Tmin | PT\_Tmin | ?? | Climate | false | 2 | WY - Wyoming basin \| WY - NE Plains |
| 69 | TMIN\_WS | TMIN\_WS | ?? | Climate | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 70 | RH\_WS | RH\_WS | ?? | Climate | false | 3 | WY - Wyoming basin \| WY - NE Plains \| WestWide2018\_XericEasternPlains |
| 71 | PPT\_ACCUM | PPT\_ACCUM | ?? | Climate | true | 2 | WY - Wyoming basin \| WY - NE Plains |
| 72 | PPT\_2MoAvg | PPT\_2MoAvg | ?? | Climate | true | 2 | WY - NE Plains \| WY - Wyoming basin |
| 73 | DOY | DOY | ?? | Climate | true | 5 | UTDEQ15 \| CO EDAS Biotype 1 \| WY - NE Plains \| WY - Wyoming basin \| NV MMI |
| 102 | AT | AT | ?? | Climate | false | 1 | AK East Central |
| 116 | PRCPSHORTW | PRCPSHORTW | ?? | Climate | false | 3 | UTDEQ15 \| NV MMI \| CO EDAS Biotype 1 |
| 118 | WDmax\_WS | WDmax\_WS | ?? | Climate | false | 1 | CSCI |
| 119 | Pmin\_WS | Pmin\_WS | ?? | Climate | false | 2 | CSCI \| WestWide2018\_XericEasternPlains |
| 120 | Tmax\_WS | Tmax\_WS | ?? | Climate | false | 0 |  |
| 121 | HYDR\_WS | HYDR\_WS | ?? | Climate | false | 1 | CSCI |
| 122 | Pmax\_PT | Pmax\_PT | ?? | Climate | false | 1 | CSCI |
| 123 | Pmax\_WS | Pmax\_WS | ?? | Climate | false | 1 | CSCI |
| 124 | Tmax\_PT | Tmax\_PT | ?? | Climate | false | 3 | CO EDAS Biotype 3 \| CSCI \| CO EDAS Biotype 2 |
| 129 | daynum | daynum | ?? | Climate | true | 1 | OR NBR |
| 135 | TMAX\_PT | TMAX\_PT | ?? | Climate | false | 0 |  |
| 136 | LOG\_LT\_PPT\_PT | LOG\_LT\_PPT\_PT | ?? | Climate | false | 1 | CO EDAS Biotype 3 |
| 138 | TMAX\_AVE | TMAX\_AVE | ?? | Climate | false | 1 | CO EDAS Biotype 2 |
| 139 | TMEAN\_AVE | TMEAN\_AVE | ?? | Climate | false | 1 | CO EDAS Biotype 2 |
| 140 | TMIN\_AVE | TMIN\_AVE | ?? | Climate | false | 1 | CO EDAS Biotype 2 |
| 141 | RH\_AVE | RH\_AVE | ?? | Climate | false | 1 | CO EDAS Biotype 2 |
| 142 | TMEANPT | TMEANPT | ?? | Climate | false | 1 | CO EDAS Biotype 2 |
| 143 | MEANP\_AVE | MEANP\_AVE | mm | Climate | false | 1 | CO EDAS Biotype 2 |
| 145 | MAXWD\_AVE | MAXWD\_AVE | ?? | Climate | false | 1 | CO EDAS Biotype 2 |
| 146 | FST32F\_AVE | FST32F\_AVE | ?? | Climate | false | 1 | CO EDAS Biotype 2 |
| 163 | PMIN\_WS | PMIN\_WS | ?? | Climate | false | 0 |  |
| 164 | TMEAN\_PT | TMEAN\_PT | ?? | Climate | false | 1 | WestWide2018\_XericEasternPlains |
| 165 | TMEAN\_WS | TMEAN\_WS | ?? | Climate | false | 1 | WestWide2018\_XericEasternPlains |
| 166 | PMIN\_PT | PMIN\_PT | ?? | Climate | false | 1 | WestWide2018\_XericEasternPlains |
| 169 | PMIN\_WS- same as MMI | PMIN\_WS- same as MMI | ?? | Climate | false | 1 | WestWide2018\_OtherEcoregions |
| 158 | Mines | Mines | ?? | DamsSpringsMines | false | 0 |  |
| 159 | Dams | Dams | ?? | DamsSpringsMines | false | 0 |  |
| 74 | Eco3\_PT | Eco3\_PT | ?? | Ecoregion | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 75 | ER13 | ER13 | ?? | Ecoregion | false | 2 | WY - Wyoming basin \| WY - NE Plains |
| 110 | ECO3 | ECO3 | ?? | Ecoregion | false | 3 | NV MMI \| UTDEQ15 \| CO EDAS Biotype 1 |
| 111 | ECO4 | ECO4 | ?? | Ecoregion | false | 3 | CO EDAS Biotype 1 \| UTDEQ15 \| NV MMI |
| 57 | LPREM\_mean | LPREM\_mean | ?? | Geology | false | 2 | WY - SE Plains \| WY - Volcanic mountains and valleys |
| 76 | Vol\_ave | Vol\_ave | ?? | Geology | false | 2 | WY - Wyoming basin \| WY - NE Plains |
| 89 | PCT\_SEDIM | PCT\_SEDIM | % | Geology | false | 1 | WY - Volcanic mountains and valleys |
| 58 | EVI\_MaxAve | EVI\_MaxAve | ?? | Landcover | false | 1 | WY - SE Plains |
| 77 | alru\_dom | alru\_dom | % | Landcover | false | 2 | WY - Wyoming basin \| WY - NE Plains |
| 78 | Evergr\_ave | Evergr\_ave | % | Landcover | false | 2 | WY - Wyoming basin \| WY - NE Plains |
| 79 | EVI\_AveAve | EVI\_AveAve | ?? | Landcover | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 147 | EVI\_MAX\_AVE | EVI\_MAX\_AVE | ?? | Landcover | false | 1 | CO EDAS Biotype 2 |
| 160 | Urban\_WS | Urban\_WS | % | Landcover | false | 0 |  |
| 161 | AG\_WS | AG\_WS | % | Landcover | false | 0 |  |
| 59 | PRMH\_AVE | PRMH\_AVE | ?? | Metrics | false | 2 | WY - SE Plains \| WY - Volcanic mountains and valleys |
| 60 | CaO\_Mean | CaO\_Mean | ?? | Metrics | false | 4 | WY - SE Plains \| WY - Wyoming basin \| WY - Volcanic mountains and valleys \| WY - NE Plains |
| 61 | MgO\_Mean | MgO\_Mean | ?? | Metrics | false | 2 | WY - Volcanic mountains and valleys \| WY - SE Plains |
| 62 | S\_Mean | S\_Mean | ?? | Metrics | false | 2 | WY - Volcanic mountains and valleys \| WY - SE Plains |
| 63 | UCS\_Mean | UCS\_Mean | ?? | Metrics | false | 1 | WY - SE Plains |
| 64 | BDH\_AVE | BDH\_AVE | ?? | Metrics | false | 3 | AK East Central \| WY - Volcanic mountains and valleys \| WY - SE Plains |
| 65 | KFCT\_AVE | KFCT\_AVE | ?? | Metrics | false | 2 | WY - SE Plains \| WY - Volcanic mountains and valleys |
| 80 | TP\_Mean | TP\_Mean | ?? | Metrics | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 81 | AWC\_soil | AWC\_soil | ?? | Metrics | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 82 | GW\_P\_Sp\_Mx | GW\_P\_Sp\_Mx | ?? | Metrics | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 83 | SOC | SOC | ?? | Metrics | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 84 | Pct\_Alfi | Pct\_Alfi | % | Metrics | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 85 | Wb\_mx\_area | Wb\_mx\_area | ?? | Metrics | false | 2 | WY - Wyoming basin \| WY - NE Plains |
| 86 | Kfact | Kfact | ?? | Metrics | false | 3 | WY - NE Plains \| WY - Wyoming basin \| WestWide2018\_XericEasternPlains |
| 87 | Db3rdbar | Db3rdbar | ?? | Metrics | false | 2 | WY - Wyoming basin \| WY - NE Plains |
| 90 | AREA\_SQKM | AREA\_SQKM | ?? | Metrics | false | 1 | WY - Volcanic mountains and valleys |
| 91 | N\_MEAN | N\_MEAN | ?? | Metrics | false | 1 | WY - Volcanic mountains and valleys |
| 92 | P\_MEAN | P\_MEAN | ?? | Metrics | false | 1 | WY - Volcanic mountains and valleys |
| 93 | New\_Long | New\_Long | ?? | Metrics | false | 1 | WY - Volcanic mountains and valleys |
| 94 | New\_Lat | New\_Lat | ?? | Metrics | false | 1 | WY - Volcanic mountains and valleys |
| 95 | SITE\_ELEV | SITE\_ELEV | m | Metrics | false | 1 | WY - Volcanic mountains and valleys |
| 96 | ELVmax\_WS | ELVmax\_WS | m | Metrics | false | 4 | AK East Central \| CSCI \| WestWide2018\_OtherEcoregions \| WY - Volcanic mountains and valleys |
| 97 | ELVmin\_WS | ELVmin\_WS | m | Metrics | false | 7 | AK East Central \| NV MMI \| UTDEQ15 \| CSCI \| WY - Volcanic mountains and valleys \| WestWide2018\_XericEasternPlains \| CO EDAS Biotype 1 |
| 98 | ELEV\_RANGE | ELEV\_RANGE | m | Metrics | false | 1 | WY - Volcanic mountains and valleys |
| 99 | TEMP\_00\_09 | TEMP\_00\_09 | ?? | Metrics | false | 1 | WY - Volcanic mountains and valleys |
| 100 | PPT\_00\_09 | PPT\_00\_09 | ?? | Metrics | false | 1 | WY - Volcanic mountains and valleys |
| 103 | Sq\_km | Sq\_km | ?? | Metrics | false | 4 | CO EDAS Biotype 2 \| CSCI \| AK East Central \| CO EDAS Biotype 3 |
| 104 | Bdh\_Ave | Bdh\_Ave | ?? | Metrics | false | 0 |  |
| 105 | BFI\_WS | BFI\_WS | ?? | Metrics | false | 2 | AK East Central \| CSCI |
| 106 | Lat\_Dec | Lat\_Dec | ?? | Metrics | false | 3 | CO EDAS Biotype 1 \| UTDEQ15 \| NV MMI |
| 107 | Long\_Dec | Long\_Dec | ?? | Metrics | false | 3 | CO EDAS Biotype 1 \| UTDEQ15 \| NV MMI |
| 109 | ELEV\_SITE | ELEV\_SITE | m | Metrics | false | 3 | NV MMI \| CO EDAS Biotype 1 \| UTDEQ15 |
| 112 | SUMMER | SUMMER | ?? | Metrics | false | 3 | UTDEQ15 \| NV MMI \| CO EDAS Biotype 1 |
| 113 | WINTER | WINTER | ?? | Metrics | false | 3 | NV MMI \| UTDEQ15 \| CO EDAS Biotype 1 |
| 114 | LOG\_XP\_PT | LOG\_XP\_PT | ?? | Metrics | false | 3 | UTDEQ15 \| CO EDAS Biotype 1 \| NV MMI |
| 115 | SQRT\_TOPO | SQRT\_TOPO | ?? | Metrics | false | 3 | NV MMI \| UTDEQ15 \| CO EDAS Biotype 1 |
| 117 | ELEV\_WS | ELEV\_WS | m | Metrics | false | 3 | UTDEQ15 \| CO EDAS Biotype 1 \| NV MMI |
| 125 | SQ\_KM | SQ\_KM | ?? | Metrics | false | 0 |  |
| 126 | ELVcv\_PT | ELVcv\_PT | ?? | Metrics | false | 1 | CSCI |
| 127 | ELVmean\_WS | ELVmean\_WS | m | Metrics | false | 2 | WestWide2018\_XericEasternPlains \| CSCI |
| 130 | long | long | ?? | Metrics | false | 1 | OR NBR |
| 131 | precip | precip | ?? | Metrics | false | 1 | AREMP MMI |
| 132 | temp | temp | ?? | Metrics | false | 1 | AREMP MMI |
| 133 | east | east | ?? | Metrics | false | 1 | AREMP MMI |
| 134 | elev\_sqrt | elev\_sqrt | ?? | Metrics | false | 1 | AREMP MMI |
| 137 | LOG\_KM2 | LOG\_KM2 | ?? | Metrics | false | 1 | CO EDAS Biotype 3 |
| 148 | ELEV\_MIN | ELEV\_MIN | m | Metrics | false | 1 | CO EDAS Biotype 2 |
| 149 | ELEV\_MEAN | ELEV\_MEAN | m | Metrics | false | 1 | CO EDAS Biotype 2 |
| 150 | DD\_LAT\_Y | DD\_LAT\_Y | ?? | Metrics | false | 1 | CO EDAS Biotype 2 |
| 151 | AreaKM | AreaKM | ?? | Metrics | false | 0 |  |
| 162 | KFACT | KFACT | ?? | Metrics | false | 0 |  |
| 167 | WSA\_SQKM | WSA\_SQKM | ?? | Metrics | false | 1 | WestWide2018\_OtherEcoregions |
| 168 | ELVmean\_WS- same as MMI | ELVmean\_WS- same as MMI | m | Metrics | false | 1 | WestWide2018\_OtherEcoregions |
| 154 | BLMown | BLMown | % | Ownership | false | 0 |  |
| 155 | Privown | Privown | % | Ownership | false | 0 |  |
| 88 | slpavg | slpavg | ?? | Slope | false | 2 | WY - NE Plains \| WY - Wyoming basin |
| 108 | NHDSLOPE | NHDSLOPE | ?? | Slope | false | 3 | UTDEQ15 \| CO EDAS Biotype 1 \| NV MMI |
| 1 | Area of local NHDPlus catchment \(square km\) | CatAreaSqKm | sqkm | StreamCAT | false | 0 |  |
| 2 | Mean catchment elevation \(m\) | ElevCat | m | StreamCAT | false | 0 |  |
| 3 | PRISM climate data - 30-year normal mean precipitation \(mm\): Annual period: 1981-2010 within the watershed | Precip8110Ws | mm | StreamCAT | false | 0 |  |
| 4 | PRISM climate data - 30-year normal mean temperature \(°C\): Annual period: 1981-2010 within the watershed | Tmean8110Ws | C | StreamCAT | false | 0 |  |
| 5 | Mean % of lithological calcium oxide \(CaO\) content in surface or near surface geology within watershed | CaOWs | % | StreamCAT | false | 0 |  |
| 6 | Mean % of lithological nitrogen \(N\) content in surface or near surface geology within catchment | NCat | % | StreamCAT | false | 0 |  |
| 7 | Mean runoff \(mm\) within watershed | RunoffWs | mm | StreamCAT | false | 0 |  |
| 8 | Mean % of lithological sulfur \(S\) content in surface or near surface geology within watershed | SWs | % | StreamCAT | false | 0 |  |
| 9 | % of watershed area classified as lithology type: saline like sediment | PctSalLakeWs | % | StreamCAT | false | 0 |  |
| 10 | Predicted mean annual stream temperature \(Jan-Dec\) for year 2008 | MAST\_2008 | C | StreamCAT | false | 0 |  |
| 11 | Predicted mean annual stream temperature \(Jan-Dec\) for year 2009 | MAST\_2009 | C | StreamCAT | false | 0 |  |
| 12 | Predicted mean annual stream temperature \(Jan-Dec\) for year 2013 | MAST\_2013 | C | StreamCAT | false | 0 |  |
| 13 | Predicted mean annual stream temperature \(Jan-Dec\) for year 2014 | MAST\_2014 | C | StreamCAT | false | 0 |  |
| 14 | Predicted mean summer stream temperature \(July-Aug\) for year 2008 | MSST\_2008 | C | StreamCAT | false | 0 |  |
| 15 | Predicted mean summer stream temperature \(July-Aug\) for year 2009 | MSST\_2009 | C | StreamCAT | false | 0 |  |
| 16 | Predicted mean summer stream temperature \(July-Aug\) for year 2013 | MSST\_2013 | C | StreamCAT | false | 0 |  |
| 17 | Predicted mean summer stream temperature \(July-Aug\) for year 2014 | MSST\_2014 | C | StreamCAT | false | 0 |  |
| 18 | Predicted mean winter stream temperature \(Jan-Feb\) for year 2008 | MWST\_2008 | C | StreamCAT | false | 0 |  |
| 19 | Predicted mean winter stream temperature \(Jan-Feb\) for year 2009 | MWST\_2009 | C | StreamCAT | false | 0 |  |
| 20 | Predicted mean winter stream temperature \(Jan-Feb\) for year 2013 | MWST\_2013 | C | StreamCAT | false | 0 |  |
| 21 | Predicted mean winter stream temperature \(Jan-Feb\) for year 2014 | MWST\_2014 | C | StreamCAT | false | 0 |  |
| 22 | Density of roads-stream intersections \(2010 Census Tiger Lines-NHD stream lines\) within catchment \(crossings/square km\) | RdCrsCat | xs/km2 | StreamCAT | false | 0 |  |
| 23 | Density of roads-stream intersections \(2010 Census Tiger Lines-NHD stream lines\) within watershed \(crossings/square km\) | RdCrsWs | xs/km2 | StreamCAT | false | 0 |  |
| 24 | Density of roads \(2010 Census Tiger Lines\) within watershed \(km/square km\) | RdDensWs | km/km2 | StreamCAT | false | 0 |  |
| 25 | Density of georeferenced dams within catchment \(dams/ square km\) based on the National Inventory of Dams \(https://catalog.data.gov/dataset/national-inventory-of-dams\) | DamDensCat | dams/km2 | StreamCAT | false | 0 |  |
| 26 | Density of NHDPlus line features classified as canal, ditch, or pipeline within the catchment \(km/ square km\) | CanalDensCat | km/km2 | StreamCAT | false | 0 |  |
| 27 | Density of NHDPlus line features classified as canal, ditch, or pipeline within the upstream watershed \(km/ square km\) | CanalDensWs | km/km2 | StreamCAT | false | 0 |  |
| 28 | Density of Superfund sites within watershed \(sites/square km\) | SuperfundDensWs | sites/km2 | StreamCAT | false | 0 |  |
| 29 | Density of mine sites within watershed \(mines/square km\) | MineDensWs | mines/sq km | StreamCAT | false | 0 |  |
| 30 | % of watershed area classified as developed, high-intensity land use \(NLCD 2006 class 24\) | PctUrbHi2006Ws | % | StreamCAT | false | 0 |  |
| 31 | % of catchment area classified as developed, high-intensity land use \(NLCD 2006 class 24\) | PctUrbHi2006Cat | % | StreamCAT | false | 0 |  |
| 32 | % of watershed area classified as developed, low-intensity land use \(NLCD 2006 class 22\) | PctUrbLo2006Ws | % | StreamCAT | false | 0 |  |
| 33 | % of catchment area classified as developed, low-intensity land use \(NLCD 2006 class 22\) | PctUrbLo2006Cat | % | StreamCAT | false | 0 |  |
| 34 | % of watershed area classified as developed, medium-intensity land use \(NLCD 2006 class 23\) | PctUrbMd2006Ws | % | StreamCAT | false | 0 |  |
| 35 | % of catchment area classified as developed, medium-intensity land use \(NLCD 2006 class 23\) | PctUrbMd2006Cat | % | StreamCAT | false | 0 |  |
| 36 | % of watershed area classified as ag land cover \(NLCD 2006 classes 81-82\) occurring on slopes greater than or equal to 10% | PctAg2006Slp10Ws | % | StreamCAT | false | 0 |  |
| 37 | % of watershed area classified as ag land cover \(NLCD 2006 classes 81-82\) occurring on slopes greater than or equal to 20% | PctAg2006Slp20Ws | % | StreamCAT | false | 0 |  |
| 38 | % of catchment area classified as ag land cover \(NLCD 2006 classes 81-82\) occurring on slopes greater than or equal to 10% | PctAg2006Slp10Cat | % | StreamCAT | false | 0 |  |
| 39 | % of catchment area classified as ag land cover \(NLCD 2006 classes 81-82\) occurring on slopes greater than or equal to 20% | PctAg2006Slp20Cat | % | StreamCAT | false | 0 |  |
| 40 | % of watershed area classified as developed, high-intensity land use \(NLCD 2011 class 24\) | PctUrbHi2011Ws | % | StreamCAT | false | 0 |  |
| 41 | % of catchment area classified as developed, high-intensity land use \(NLCD 2011 class 24\) | PctUrbHi2011Cat | % | StreamCAT | false | 0 |  |
| 42 | % of watershed area classified as developed, low-intensity land use \(NLCD 2011 class 22\) | PctUrbLo2011Ws | % | StreamCAT | false | 0 |  |
| 43 | % of catchment area classified as developed, low-intensity land use \(NLCD 2011 class 22\) | PctUrbLo2011Cat | % | StreamCAT | false | 0 |  |
| 44 | % of watershed area classified as developed, medium-intensity land use \(NLCD 2011 class 23\) | PctUrbMd2011Ws | % | StreamCAT | false | 0 |  |
| 45 | % of catchment area classified as developed, medium-intensity land use \(NLCD 2011 class 23\) | PctUrbMd2011Cat | % | StreamCAT | false | 0 |  |
| 101 | Variable | Variable | ?? | Unknown | false | 1 | AK East Central |
| 128 | Slope\_WS | Slope\_WS | ?? | Unknown | false | 1 | CSCI |
| 144 | MAXP\_AVE | MAXP\_AVE | ?? | Unknown | false | 1 | CO EDAS Biotype 2 |
| 157 | OilGasWells | OilGasWells | ?? | Unknown | false | 0 |  |
| 156 | OilFld\_Pct | OilFld\_Pct | % | UT\_Grazing | false | 0 |  |

**Comment by Feldspar5** [comment]
Do we have the model associated with each of these?

**Comment by philipbaileynar** [comment]
@Feldspar5 I have updated the table above with the names of the models for which each predictor is used. **scroll over to the right to see the new information** (because it gets cut off in this web page).

Note that each predictor can be used by multiple models. Each model name is separated by a pipe |

[2021_04_28_predictors.csv](https://github.com/namc-utah/namc-bug-db/files/6395599/2021_04_28_predictors.csv)


For my reference, here's the SQL that generated these data:

```sql
SELECT p.predictor_id,
       p.predictor_name,
       p.abbreviation        abbreviation,
       u.abbreviation        units,
       t.predictor_type_name predictor_type,
       p.is_temporal,
       count(m.*)            model_count,
    array_to_string(array_agg(m.abbreviation), ' | ') models
FROM geo.predictors p
         inner join geo.units u on p.unit_id = u.unit_id
         inner join geo.predictor_types t on p.predictor_type_id = t.predictor_type_id
         left join
     (
         SELECT mp.predictor_id, m.abbreviation
         from geo.model_predictors mp
                  inner join geo.models m on mp.model_id = m.model_id) m on p.predictor_id = m.predictor_id
group by p.predictor_id, p.predictor_name, p.abbreviation, units, predictor_type, is_temporal
order by predictor_type
```

**Comment by philipbaileynar** [comment]
@Feldspar5 responded with the following prioritization:

https://docs.google.com/spreadsheets/d/199HRoyZOX1XowUKLdyWZMNENYe_d_K5O2RkeDY6wJ1o/edit?usp=sharing
