### ISSUE TITLE
Offical Taxonomy and Translation Data

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#131]
OK @David-Fowler this is the official request that we discussed for you to provide the official NAMC taxonomy list of taxa and translation taxa.

@Feldspar5 this is an extremely important request that I need David's help with completing this week.

## Background

To date I have been importing taxa listings and OTU taxa from PilotDB. Through our discussions it appears that this information requires some manipulation before it is ingested into the new system; manipulation that requires your institutional knowledge. Therefore I have created this issue to capture my request for the manipulated, final data.

## Request

1. Official NAMC taxa hierarchy - preferably this would be provided as a series of SQL insert statements into the `taxa.taxonomy` table (schema [here](https://github.com/namc-utah/namc-bug-db/blob/master/docker/postgres/initdb/01_SCHEMA.sql#L461-L473)) and submitted as a pull request in this repository.
    - The SQL statements must reuse the same taxa code from PilotDB.
    - The final file should be called `10_taxa_taxonomy.sql` and placed in the [initdb](https://github.com/namc-utah/namc-bug-db/tree/dev/docker/postgres/initdb) folder.
2. Taxa listings for each OTU. Here's the [schema for the target table](https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/01_SCHEMA.sql#L567-L576).
    - these data should also be placed in the [initdb](https://github.com/namc-utah/namc-bug-db/tree/dev/docker/postgres/initdb) folder as SQL insert statements. Call the file `20_taxa_translation_taxa.sql`.
    - Note that the list of official OTUs (translations) is available [here](https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/10_taxa_translations.sql) for cross reference. Add others to this file if needed.
    - Remember that for OTU translations we only need one record in this table for the taxa that is present in the OTU and used for rolling up organisms. We don't need the entire hierarchy.
    - Remember for synonym translations you can include all taxa that require an alias scientific_name. 

This is a blocking issue for me. I will drop everything to answer questions or support the completion of this ticket.

**Comment by philipbaileynar** [comment]
Status please?

**Comment by Feldspar5** [comment]
David - We need an update on this process today - there is so much that is hinging on these data.

**Comment by philipbaileynar** [comment]
Reassigning to Andrew per @Feldspar5 request.

**Comment by philipbaileynar** [comment]
Official taxa and translations now in the database.
