### ISSUE TITLE
Where are synoyms in Pilot?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#137]
@David-Fowler can you point me to taxonomic synonyms in Pilot please?

I see the `CommonName` fields in the `dbo.PilotDB.Taxonomy` table. Is this correct? Are they anywhere else? Front end database?

**Comment by David-Fowler** [comment]
A partial compilation of all synonyms are in PilotDB.taxa.synonym. CommonName fields are not up to date and would cause more issues if used at this point. Part of the updated tables I was going to pass you relating to the taxonomy effort was an updated synonyms tables corresponding to the PilotDB.taxa.synonym table. Again, while this the current table is not complete it is the most up-to-date currently in a database table.

**Comment by philipbaileynar** [comment]
Thanks. I will use `PilotDB.taxa.synonym` for now.

Can you confirm that I can ignore the `scientific_name column`? All I need is the `synonym` column, right?

**Comment by David-Fowler** [comment]
Correct. The `scientific_name` column is a replicate from the taxonomy table `synonym` and `code` are all that is needed to match entries.

**Comment by philipbaileynar** [comment]
OK ~8,000 synonyms are now being imported from pilot!
