### ISSUE TITLE
Can we Split_Count and MakeBigRareCount Not NULL?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#146]
In the bug data table (now called [sample.organisms](https://github.com/namc-utah/namc-bug-db/blob/master/docker/postgres/initdb/01_SCHEMA.sql#L1158-L1175) can we make both `split_count` and `big_rare_count` default to zero and be NOT NULL?

Do either of these fields have special meaning when they are null? 

* There are currently zero records where split_count is NULL
* There are currently 4901 records were big_rare_count is NULL

**Comment by Feldspar5** [comment]
Both split and BR should be values from 0-n.  There is nothing special about 'null'.  All nulls can be changed to 0.

**Comment by philipbaileynar** [comment]
I have now made these two fields NULL for the next deploy of the database.
