### ISSUE TITLE
Taxonomy To Delete

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#152]
Here are the taxonomy that @andrew-caudillo flagged for deletion. Before I do so I will check how many occurences of these taxa there are in PilotDB.

@Feldspar5 this is really an FYI for you to scan this list and raise any concerns before I delete them.

| taxonomy\_id | level\_name | scientific\_name | notes | parent\_id | parent\_scientific\_name | parent\_level\_name |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1922 | Class | Agnatha | NULL | 1921 | Chordata | Phylum |
| 637 | Class | Bivalvia | NULL | 595 | Mollusca | Phylum |
| 591 | Class | Hydrozoa | NULL | 590 | Cnidaria | Phylum |
| 1223 | Class | UNID''d terrestrial | NULL | 53 | Arthropoda | Phylum |
| 5828 | SubClass | Megadrili | Not in ITIS | 1 | Annelida | Phylum |
| 1929 | Order | Aeolosomatida | Not in ITIS | 1 | Annelida | Phylum |
| 6130 | Order | Anguilliformes |  | 1240 | Actinopterygii | Class |
| 6132 | Order | Atheriniformes |  | 1240 | Actinopterygii | Class |
| 6142 | Order | Clupeiformes |  | 1240 | Actinopterygii | Class |
| 4321 | Order | Conchostraca |  | 1923 | Branchiopoda | Class |
| 6047 | Order | Littorinimorpha | NULL | 596 | Gastropoda | Class |
| 6131 | Order | Percopsiformes |  | 1240 | Actinopterygii | Class |
| 1009 | Order | Tricladida | broken into 3 groups, not really used anymore, but valid. | 5753 | Rhabditophora | Class |
| 5827 | Order | Unionacea | NULL | 637 | Bivalvia | Class |
| 5639 | SubOrder | Capniidae/Nemouridae | NULL | 403 | Plecoptera | Order |
| 2108 | SubOrder | Oribatei | Oribatei invalid | 55 | Sarcoptiformes | Order |
| 3044 | Family | Anguillidae |  | 6130 | Anguilliformes | Order |
| 3045 | Family | Aphredoderidae |  | 6131 | Percopsiformes | Order |
| 3047 | Family | Atherinidae |  | 6132 | Atheriniformes | Order |
| 6135 | Family | Atherinopsidae |  | 1240 | Actinopterygii | Class |
| 4169 | Family | Atherix/Suragina | NULL | 2812 | Brachycera | SubOrder |
| 2261 | Family | Atylotus/Tabanus | NULL | 2812 | Brachycera | SubOrder |
| 2118 | Family | Axonopsidae | NULL | 5436 | Prostigmata | SubOrder |
| 2120 | Family | Clathrosperchonidae | NULL | 5436 | Prostigmata | SubOrder |
| 3172 | Family | Clupeidae |  | 6142 | Clupeiformes | Order |
| 4825 | Family | Musculium/Sphaerium | NULL | 649 | Veneroida | Order |
| 3918 | Family | Other Chloroperlidae | NULL | 403 | Plecoptera | Order |
| 4078 | Family | Other Coenagrionidae | NULL | 2815 | Zygoptera | SubOrder |
| 5978 | Family | Pisidiidae |  | 649 | Veneroida | Order |
| 2384 | Family | Prostoia/Podmosta | NULL | 403 | Plecoptera | Order |
| 5834 | Family | Stygothrombidiidae | NULL | 5436 | Prostigmata | SubOrder |
| 2165 | Family | Thyasidae | NULL | 5436 | Prostigmata | SubOrder |
| 5710 | Family | Tricorythodes/Caenis | NULL | 5724 | Furcatergalia | SubOrder |
| 39 | Family | Tubificidae | NULL | 5711 | Tubificida | SubOrder |
| 4535 | SubFamily | Gryllotalpinae | NULL | 5794 | Orthoptera | Order |
| 2925 | SubFamily | Libellulinae | NULL | 396 | Libellulidae | Family |
| 2092 | SubFamily | Petromyzontinae | NULL | 1258 | Petromyzontidae | Family |
| 5889 | SubFamily | Timpanoginae | NULL | 262 | Ephemerellidae | Family |
| 5665 | Tribe | Hydroporus/Hygrotus | Unsure if in same tribe. | 2187 | Hydroporinae | SubFamily |
| 5427 | Tribe | Nebrioporus/Stictotarsus | NULL | 2187 | Hydroporinae | SubFamily |
| 3942 | Genus | Armiger | NULL | 628 | Planorbidae | Family |
| 6133 | Genus | Atherinomorus |  | 3047 | Atherinidae | Family |
| 6136 | Genus | Atherinops |  | 6135 | Atherinopsidae | Family |
| 6137 | Genus | Atherinopsis |  | 6135 | Atherinopsidae | Family |
| 2482 | Genus | Bezzia group | NULL | 2351 | Palpomyiini | Tribe |
| 6020 | Genus | Boreonectes | not in ITIS, but the genus appears valid. "Species can be transferred to Leconectes or Nectoboreus" | 4625 | Hydroporini | Tribe |
| 753 | Genus | Chlorohydra | NULL | 593 | Hydridae | Family |
| 4314 | Genus | Coptotomus | typo. coMpto... | 105 | Dytiscidae | Family |
| 1396 | Genus | Cyphon | NULL | 172 | Scirtidae | Family |
| 849 | Genus | Elsianus | NULL | 121 | Elmidae | Family |
| 5885 | Genus | Enallagma/Ischnura | NULL | 374 | Coenagrionidae | Family |
| 2066 | Genus | Ephemerella inermis/dorothea | NULL | 262 | Ephemerellidae | Family |
| 1282 | Genus | Ephemerella inermis/infrequens | NULL | 262 | Ephemerellidae | Family |
| 635 | Genus | Fontelicella | NULL | 633 | Hydrobiidae | Family |
| 4534 | Genus | Gryllotalpa | NULL | 4535 | Gryllotalpinae | SubFamily |
| 594 | Genus | Hydra | NULL | 593 | Hydridae | Family |
| 6134 | Genus | Hypoatherina |  | 3047 | Atherinidae | Family |
| 5424 | Genus | Ilybiosoma senates group | Speices group does not appear anywhere. The species for Ilybiosoma doesn't exist in ITIS or EoL | 5861 | Agabinae | SubFamily |
| 6171 | Genus | Ipnobius |  | 633 | Hydrobiidae | Family |
| 5918 | Genus | Lipiniella | NULL | 1675 | Chironomini | Tribe |
| 2076 | Genus | Lopognathella | Not anywhere | 2083 | Onychiuridae | Family |
| 1619 | Genus | N.Z. mud snail? indistinct characteristics | NULL | 633 | Hydrobiidae | Family |
| 4847 | Genus | Neocurtilla | NULL | 4535 | Gryllotalpinae | SubFamily |
| 6118 | Genus | Neomysis |  | 6117 | Mysidae | Family |
| 2095 | Genus | Optioservus divergens/pecosensis | NULL | 121 | Elmidae | Family |
| 2468 | Genus | Panisopus | NULL | 2132 | Hydryphantidae | Family |
| 4017 | Genus | Paraleptophlebia with tusks | NULL | 287 | Leptophlebiidae | Family |
| 2136 | Genus | Partunia | Looks like a typo of some kind. Doesn't appear anywhere | 2132 | Hydryphantidae | Family |
| 34 | Genus | Pristinella |  | 662 | Naididae | Family |
| 2471 | Genus | Probezzia group | NULL | 5776 | Sphaeromiini | Tribe |
| 141 | Genus | Promoresia | NULL | 121 | Elmidae | Family |
| 3934 | Genus | Proptera | NULL | 640 | Unionidae | Family |
| 6162 | Genus | Pseudosuccinea |  | 604 | Lymnaeidae | Family |
| 5826 | Genus | Rhynolimnochares | NULL | 2147 | Limnocharidae | Family |
| 5319 | Genus | Stygonectes | NULL | 1947 | Crangonyctidae | Family |
| 2588 | Genus | Tanytarsus curticonrin group | Not anywhere on the web | 1305 | Tanytarsini | Tribe |
| 5908 | Genus | Thienemannimyia group | duplicate taxon | 1682 | Pentaneurini | Tribe |
| 5832 | Genus | Tyrellia | NULL | 2144 | Limnesiidae | Family |
| 6147 | Genus | Utterbackia |  | 640 | Unionidae | Family |
| 3013 | SubGenus | Epitheca \(Tetragoneuria\) |  | 1982 | Corduliidae | Family |
| 2700 | Species | Acentrella parvula |  | 907 | Acentrella | Genus |
| 2330 | Species | Agrypnia dextra | NULL | 939 | Agrypnia | Genus |
| 3160 | Species | Alosa aestivalis | NULL | 3172 | Clupeidae | Family |
| 3161 | Species | Alosa alabamae | NULL | 3172 | Clupeidae | Family |
| 3162 | Species | Alosa chrysochloris | NULL | 3172 | Clupeidae | Family |
| 3163 | Species | Alosa mediocris | NULL | 3172 | Clupeidae | Family |
| 3164 | Species | Alosa pseudoharengus | NULL | 3172 | Clupeidae | Family |
| 3165 | Species | Alosa sapidissima | NULL | 3172 | Clupeidae | Family |
| 3041 | Species | Amia calva | NULL | 3042 | Amiidae | Family |
| 5942 | Species | Amnicola greggi | NULL | 600 | Amnicola | Genus |
| 5941 | Species | Amnicola integra | NULL | 600 | Amnicola | Genus |
| 6012 | Species | Amnicola limosus | NULL | 600 | Amnicola | Genus |
| 5977 | Species | Amnicola longinqua | NULL | 600 | Amnicola | Genus |
| 5939 | Species | Amnicola pilsbryi | NULL | 600 | Amnicola | Genus |
| 1833 | Species | Ancyronyx variegata | NULL | 1243 | Ancyronyx | Genus |
| 3043 | Species | Anguilla rostrata | NULL | 3044 | Anguillidae | Family |
| 3046 | Species | Aphredoderus sayanus | NULL | 3045 | Aphredoderidae | Family |
| 3048 | Species | Atherinomorus stipes |  | 6133 | Atherinomorus | Genus |
| 3055 | Species | Atherinops affinis |  | 6136 | Atherinops | Genus |
| 3050 | Species | Atherinopsis californiensis |  | 6137 | Atherinopsis | Genus |
| 1263 | Species | Baetis intermedius | NULL | 250 | Baetis | Genus |
| 6058 | Species | Baetis phoebus | NULL | 250 | Baetis | Genus |
| 6018 | Species | Baetis piscatoris complex | NULL | 250 | Baetis | Genus |
| 5862 | Species | Bolshecapnia maculata | NULL | 736 | Bolshecapnia | Genus |
| 3166 | Species | Brevoortia gunteri | NULL | 3172 | Clupeidae | Family |
| 3167 | Species | Brevoortia patronus | NULL | 3172 | Clupeidae | Family |
| 3168 | Species | Brevoortia smithi | NULL | 3172 | Clupeidae | Family |
| 3169 | Species | Brevoortia tyrannus | NULL | 3172 | Clupeidae | Family |
| 4219 | Species | Caenis fuscum | NULL | 261 | Caenis | Genus |
| 1714 | Species | Camelobaetidius similis | NULL | 784 | Camelobaetidius | Genus |
| 2905 | Species | Capnura frisoni | NULL | 5746 | Capnura | Genus |
| 1309 | Species | Caudatella cascadia | NULL | 264 | Caudatella | Genus |
| 1827 | Species | Caudatella orestes | NULL | 264 | Caudatella | Genus |
| 5470 | Species | Chaoborus albipes | not in ITIS | 772 | Chaoborus | Genus |
| 5940 | Species | Cincinnatia cincinnatiensis | NULL | 5994 | Cincinnatia | Genus |
| 5976 | Species | Cincinnatia peracuta | NULL | 5994 | Cincinnatia | Genus |
| 5980 | Species | Cipangopaludina malleata | NULL | 2053 | Cipangopaludina | Genus |
| 125 | Species | Cleptelmis ornata | NULL | 124 | Cleptelmis | Genus |
| 3170 | Species | Clupea harengus | NULL | 3172 | Clupeidae | Family |
| 3171 | Species | Clupea pallasi | NULL | 3172 | Clupeidae | Family |
| 2745 | Species | Corisella tarsalsis | NULL | 318 | Corisella | Genus |
| 5915 | Species | Cricotopus \(Isocladius\) Type I | NULL | 2808 | Cricotopus \(Isocladius\) | SubGenus |
| 2540 | Species | Cricotopus brevipalpis | NULL | 863 | Cricotopus | Genus |
| 4351 | Species | Cricotopus patens |  | 2808 | Cricotopus \(Isocladius\) | SubGenus |
| 4364 | Species | Cumberlandia monodonta | NULL | 1516 | Margaritiferidae | Family |
| 5360 | Species | Dannella lita | NULL | 3898 | Dannella | Genus |
| 5652 | Species | Dixella indiana | unresolved name via EOL. | 665 | Dixella | Genus |
| 3173 | Species | Dorosoma cepedianum | NULL | 3172 | Clupeidae | Family |
| 3174 | Species | Dorosoma petenense | NULL | 3172 | Clupeidae | Family |
| 5968 | Species | Dreissena burgensis | NULL | 2000 | Dreissena | Genus |
| 1556 | Species | Drunella longicornis | NULL | 266 | Drunella | Genus |
| 4432 | Species | Ellipes minutus | mole cricket? We don't need that | 5794 | Orthoptera | Order |
| 2392 | Species | Elsianus moestus | NULL | 849 | Elsianus | Genus |
| 1259 | Species | Entosphenus tridentatus | NULL | 2035 | Entosphenus | Genus |
| 4449 | Species | Epeorus ironopsis | NULL | 280 | Epeorus | Genus |
| 778 | Species | Ephemerella inermis | NULL | 268 | Ephemerella | Genus |
| 3175 | Species | Etrumeus teres | NULL | 3172 | Clupeidae | Family |
| 2695 | Species | Ferrissia parallelus | NULL | 599 | Ferrissia | Genus |
| 5970 | Species | Fluminicola fusca | NULL | 634 | Fluminicola | Genus |
| 6002 | Species | Fluminicola hindsi | NULL | 634 | Fluminicola | Genus |
| 5983 | Species | Fontelicella bonnevillensis | NULL | 635 | Fontelicella | Genus |
| 6005 | Species | Fontelicella deserta | NULL | 635 | Fontelicella | Genus |
| 5982 | Species | Fontelicella glenwoodensis | NULL | 635 | Fontelicella | Genus |
| 5987 | Species | Fontelicella koosharensis | NULL | 635 | Fontelicella | Genus |
| 5988 | Species | Fontelicella pavantica | NULL | 635 | Fontelicella | Genus |
| 5981 | Species | Fontelicella pilsbryana | NULL | 635 | Fontelicella | Genus |
| 4490 | Species | Fontelicella robusta | NULL | 635 | Fontelicella | Genus |
| 5986 | Species | Fontelicella sanpetensis | NULL | 635 | Fontelicella | Genus |
| 5985 | Species | Fontelicella sevierensis | NULL | 635 | Fontelicella | Genus |
| 5938 | Species | Fontelicella stearnsiana | NULL | 635 | Fontelicella | Genus |
| 1432 | Species | Gerris remigis | NULL | 327 | Gerris | Genus |
| 3264 | Species | Gila crassicauda |  | 6227 | Gila | Genus |
| 1721 | Species | Gloiobdella elongata | Helobdella elongata is invalid. Changed | 18 | Helobdella | Genus |
| 4537 | Species | Gyretes compressus | NULL | 1389 | Gyretes | Genus |
| 3176 | Species | Harengula clupeola | NULL | 3172 | Clupeidae | Family |
| 3177 | Species | Harengula humeralis | NULL | 3172 | Clupeidae | Family |
| 3178 | Species | Harengula jaguana | NULL | 3172 | Clupeidae | Family |
| 3179 | Species | Harengula thrissina | NULL | 3172 | Clupeidae | Family |
| 2596 | Species | Heptagenia diabasia | NULL | 281 | Heptagenia | Genus |
| 2500 | Species | Hesperoperla abedus | NULL | 451 | Hesperoperla | Genus |
| 846 | Species | Heterlimnius koebelei | NULL | 128 | Heterlimnius | Genus |
| 5997 | Species | Hydrobia atea | NULL | 1512 | Hydrobia | Genus |
| 5998 | Species | Hydrobia longinqua | NULL | 1512 | Hydrobia | Genus |
| 4616 | Species | Hydrobiomorpha castus | NULL | 3863 | Hydrobiomorpha | Genus |
| 3049 | Species | Hypoatherina harringtonensis |  | 6134 | Hypoatherina | Genus |
| 3283 | Species | Hypophthalmichthys molitrix | NULL | 1312 | Cyprinidae | Family |
| 3284 | Species | Hypophthalmichthys nobilis | NULL | 1312 | Cyprinidae | Family |
| 2906 | Species | Ilybiosoma cordatum | Agabus cordatus is no longer valid. Changed | 5435 | Ilybiosoma | Genus |
| 793 | Species | Isoperla patricia | NULL | 462 | Isoperla | Genus |
| 3180 | Species | Jenkinsia lamprotaenia | NULL | 3172 | Clupeidae | Family |
| 3181 | Species | Jenkinsia majua | NULL | 3172 | Clupeidae | Family |
| 3182 | Species | Jenkinsia stolifera | NULL | 3172 | Clupeidae | Family |
| 3099 | Species | Lagochila lacera | NULL | 1350 | Catostomidae | Family |
| 5487 | Species | Leptodiaptomus oregonensis | NULL | 1025 | Leptodiaptomus | Genus |
| 2062 | Species | Lopognathella choreutes | Not anywhere | 2076 | Lopognathella | Genus |
| 2961 | Species | Lymnaea caperata | NULL | 927 | Lymnaea | Genus |
| 4044 | Species | Lymnaea catascopium | NULL | 927 | Lymnaea | Genus |
| 2934 | Species | Lymnaea humilis | NULL | 927 | Lymnaea | Genus |
| 2939 | Species | Lymnaea humilis/bulimoides |  | 927 | Lymnaea | Genus |
| 605 | Species | Lymnaea stagnalis | NULL | 927 | Lymnaea | Genus |
| 3301 | Species | Lythrurus ardens |  | 6235 | Lythrurus | Genus |
| 1835 | Species | Macronychus glabratus |  | 1244 | Macronychus | Genus |
| 6010 | Species | Musculium uintaense | NULL | 651 | Musculium | Genus |
| 4875 | Species | Neotridactylus apicialis | NULL | 5794 | Orthoptera | Order |
| 1277 | Species | Nixe criddlei | NULL | 284 | Nixe | Genus |
| 3183 | Species | Opisthonema libertate | NULL | 3172 | Clupeidae | Family |
| 3184 | Species | Opisthonema medirastre | NULL | 3172 | Clupeidae | Family |
| 3185 | Species | Opisthonema oglinum | NULL | 3172 | Clupeidae | Family |
| 4927 | Species | Optioservus ampliatus | NULL | 135 | Optioservus | Genus |
| 1742 | Species | Optioservus pecosensis | NULL | 135 | Optioservus | Genus |
| 4042 | Species | Paraleptophlebia helena \(tusks\) |  | 292 | Paraleptophlebia | Genus |
| 5048 | Species | Physella gyrina | NULL | 627 | Physella | Genus |
| 5049 | Species | Physella heterostropha | NULL | 627 | Physella | Genus |
| 6008 | Species | Pisidium avum | NULL | 647 | Pisidium | Genus |
| 5955 | Species | Pisidium calcolus | NULL | 647 | Pisidium | Genus |
| 5953 | Species | Pisidium coarctatum | NULL | 647 | Pisidium | Genus |
| 5954 | Species | Pisidium exiquum | NULL | 647 | Pisidium | Genus |
| 5965 | Species | Pisidium hallae | NULL | 647 | Pisidium | Genus |
| 5956 | Species | Pisidium huachucanum | NULL | 647 | Pisidium | Genus |
| 5963 | Species | Pisidium miliva | NULL | 647 | Pisidium | Genus |
| 5967 | Species | Pisidium parvus | NULL | 647 | Pisidium | Genus |
| 5966 | Species | Pisidium stigosa | NULL | 647 | Pisidium | Genus |
| 2766 | Species | Polypedilum tuverculum | NULL | 1301 | Polypedilum | Genus |
| 6039 | Species | Pristina idrensis |  | 33 | Pristina | Genus |
| 2508 | Species | Pristinella amphibiotica |  | 34 | Pristinella | Genus |
| 2639 | Species | Pristinella jenkinae |  | 34 | Pristinella | Genus |
| 5104 | Species | Promoresia elegans | NULL | 141 | Promoresia | Genus |
| 5105 | Species | Promoresia tardella | NULL | 141 | Promoresia | Genus |
| 2709 | Species | Psectrocladius psilopterus | typo. SILOpterus... | 1298 | Psectrocladius | Genus |
| 2705 | Species | Pseudocloeon propinquus | NULL | 2277 | Pseudocloeon | Genus |
| 606 | Species | Pseudosuccinea columella | NULL | 2025 | Pseudosuccinea | Genus |
| 1773 | Species | Radix auricularia | NULL | 607 | Radix | Genus |
| 6045 | Species | Rhyacophila cyalinata | NULL | 584 | Rhyacophila | Genus |
| 6041 | Species | Rhyacophila cyalinata group | NULL | 584 | Rhyacophila | Genus |
| 2354 | Species | Rhyacophila sibirica group A | NULL | 584 | Rhyacophila | Genus |
| 2355 | Species | Rhyacophila sibirica group B | NULL | 584 | Rhyacophila | Genus |
| 2356 | Species | Rhyacophila sibirica group C | NULL | 584 | Rhyacophila | Genus |
| 3186 | Species | Sardinella aurita | NULL | 3172 | Clupeidae | Family |
| 3187 | Species | Sardinella brasiliensis | NULL | 3172 | Clupeidae | Family |
| 3188 | Species | Sardinops sagax | NULL | 3172 | Clupeidae | Family |
| 1183 | Species | Serratella sequoia | NULL | 271 | Serratella | Genus |
| 1070 | Species | Serratella teresa | NULL | 271 | Serratella | Genus |
| 943 | Species | Serratella tibialis | NULL | 271 | Serratella | Genus |
| 1862 | Species | Shipsa notunda | NULL | 436 | Shipsa | Genus |
| 2696 | Species | Siphlonurus paramaletus | NULL | 304 | Siphlonurus | Genus |
| 2694 | Species | Skwala parallela | NULL | 469 | Skwala | Genus |
| 5254 | Species | Sperchopsis tessellatus | NULL | 2194 | Sperchopsis | Genus |
| 5958 | Species | Sphaerium dentatum | NULL | 648 | Sphaerium | Genus |
| 5280 | Species | Stenelmis convexula | NULL | 143 | Stenelmis | Genus |
| 5293 | Species | Stenelmis markeli | NULL | 143 | Stenelmis | Genus |
| 5302 | Species | Stenelmis vittipennis | NULL | 143 | Stenelmis | Genus |
| 5916 | Species | Tribelos jucundum | NULL | 1687 | Tribelos | Genus |
| 6043 | Species | Tricorythodes corpulentus | NULL | 307 | Tricorythodes | Genus |
| 2603 | Species | Tricorythodes edmunsi | NULL | 307 | Tricorythodes | Genus |
| 5991 | Species | Tryonia exigua | NULL | 2014 | Tryonia | Genus |
| 5993 | Species | Tryonia longinqua | NULL | 2014 | Tryonia | Genus |
| 5974 | Species | Utterbackia imbecillis | NULL | 3939 | Utterbackia | Genus |
| 6013 | Species | Valvata malleata | NULL | 616 | Valvata | Genus |
| 145 | Species | Zaitzevia milleri | NULL | 144 | Zaitzevia | Genus |
| 1664 | SubSpecies | Microcylloepus pusillus similis | NULL | 131 | Microcylloepus | Genus |
| 5011 | SubSpecies | Pelocoris femoratus femoratus | NULL | 5010 | Pelocoris femoratus | Species |

```sql
select taxonomy_id, level_name, scientific_name, notes, parent_id, parent_scientific_name, parent_level_name from vwTaxonomyWithParents where status_id = 5
```

**Comment by Feldspar5** [comment]
No issues here; please delete.
