### ISSUE TITLE
Sample Metrics Involves Multiple Rarefactions

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#155]
@Feldspar5  and  @David-Fowler can you confirm that calculating all metrics for a single sample actually involves multiple rarefactions.

Let's take three metrics as an example:

**Metric 1 - Richness of scrapers**

1. Load all sample organisms
2. throw away all organisms that don't have the scraper attribute
3. rollup remaining organisms to OTU
4. rarefy the rolled up organisms
5. count the distinct number of rolled up taxa

**Metric 2 - Richness of Insects**

1. Load all sample organisms
2. throw away all organisms that are not at or lower than Insecta in the taxonomic hierarchy
3. rollup remaining organisms to OTU
4. rarefy the rolled up organisms
5. count the distinct number of rolled up taxa

**Metric 3 - Sample Richness**

1. Load all sample organisms
2. rollup all organisms to OTU
3. rarefy the rolled up organisms
4. count the distinct number of rolled up taxa

# Question

Notice how each of these metric "workflows" involves rarefying a different set of organisms. Therefore each metric requires its own rarefaction process. Please confirm my thinking on this.

@Feldspar5 this reinforces our decision to **not** store rarefactions and calculate metrics each time they are needed.

**Comment by Feldspar5** [comment]
The rarefaction only occurs a single time per sample:
1. Start with raw data (~600 organisms with bench IDs)
2. Standardize to proper OTUnames (now we have a different number of names in the hat, and many remaining have different IDs). 
3. Rarefy to correct count (eg. remove 300 names from hat without replacement)
           -some of these will be unique names
           -some names will appear >1 time on the list
4. All richness metrics are then derived from this list

An illustration of an issue that presents at times and is confusing for the end user (this example is for abundance versus richness metrics though):  Tolerant taxa abundance is a non-zero value.  After standardization and rarefaction though, those  tolerant taxa do not remain on list. This leads to a value of 0 for tolerant taxa richness.

**Comment by philipbaileynar** [comment]
Thanks @Feldspar5, this is how I currently have everything coded. I am OK to proceed with what you have suggested.

But this is not what I took away from our discussion on Tuesday. During that call we discussed doing the taxa (.e.g. Insecta) or attribute (e.g. scraper) filtering before the standardization and rarefaction. In the case of attributes, this is because the attributes are assigned to individual species and not necessarily at the family or genera level. If we proceed with your suggestion above, we need the attributes to be assigned to the taxa that appear in the OTUs. Perhaps they are already?

**Comment by Feldspar5** [comment]
Apologies for any confusion!  The issue with attributes is that their incompleteness or need to generalize at coarser levels (which can lead to loss of data/taxa) can both lead to less than ideal results.  The onus is on NAMC to either a) accurately populate attributes at all levels (may be impossible) and b) ensure that OTU-decisions made for a model reflect similar traits within that group of organisms.  In other words, if we decide to use midges at sub-family for a set of OTUs, we need to ensure that the midge sub-family contains children with homogeneous traits (predators, etc.).  In all cases though, there should only be a single rarefaction.  The issue you raise is one in which I might react with horror at the incomplete nature of the process, but one at which Chuck might shrug and acknowledge it is the best we can do.
