### ISSUE TITLE
Fish Gut Questions

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#161]
@Feldspar5 here are the first version of the tables for fish guts:

https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/01_SCHEMA.sql#L1295-L1343

A few lingering questions:

1. Do you want to keep track of the technician and weight technician?
2. Is it important to keep track of the fish number?
3. Notice how I have put the non-taxonomic weights on the parent table. This is fine if the three categories (organic, inorganic and other) are fixed and unchanging. If there are other non-taxonomic weight categories in other years, I will tweak this design.
4. I am only keeping the sample weight. Now is the time to request the tin and tin+sample if you want them!
5. Do we need the AF, ME and Total columns to the right of the screenshot below? If so, what do they represent?

![image](https://user-images.githubusercontent.com/8645379/124050278-18a73100-d9cf-11eb-807b-791b15535498.png)

**Comment by Feldspar5** [comment]
1. We do not need to keep track of the technicians
2. Fish # not needed
3.  I ran a query on all the non-taxa names used in these data.  They were never standardized, but looks like they revolve around the same basic 3 you have listed.  I have reached out to my techs to confirm and will let you know. 
4. Just sample weight
5. Nope.  That appears to be some kind of tally between the techs
