### ISSUE TITLE
Do metrics and model runs require the same rarefied data?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#164]
The following information is needed to run a model:

- list of rarefied taxa
- metrics
- predictors

Currently I am rarefying the taxa for a sample within the code that calculates metrics. These rarefied taxa are internal to the metric calculation and discarded when the code finishes. They are not stored anywhere.

This means that when the model code runs and requests the list of rarefied taxa from the database, a new rarefaction is performed and the list of taxa that is provided to the model code will be slightly different than that used for the metrics (it's random after all).

Is this a problem?

If it's a problem, we can return the list of rarefied taxa as part of the same API endpoint that provides metrics. This will ensure that the code that calculates metrics uses precisely the same list of rarefied taxa as the model.

**Comment by Feldspar5** [comment]
NAMC has been producing metrics in reports that are independent of the rarefaction used in the model run.  I would like to move away from this practice and instead adopt your final paragraph as above: return the list of rarefied taxa as part of endpoint.

**Comment by philipbaileynar** [comment]
This issue is now replaced by #198
