### ISSUE TITLE
Model Results Associated with Different Sites

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#173]
I am importing the model results from the spreadsheet provided by @Feldspar5. I am basing my import on sample ID but as a safety check I verify that the site specified in the spreadsheet is indeed the site that I have in the new database. There are hundreds of rows in the spreadsheet where this is not the case.

@David-Fowler suggested on our call yesterday that this might be related to a historical attempt to clean up site names.

Here's just a tiny sample:

```
[error] [metric values] Sample 157848 has site GN-SS-10861 in CSV but is associated with site 385438107154 in postgres
[error] [metric values] Sample 157850 has site GN-SS-10434 in CSV but is associated with site PALM-07 in postgres
[error] [metric values] Sample 157876 has site WR-SS-11053 in CSV but is associated with site EAWICR01 in postgres
[error] [metric values] Sample 158309 has site BO-SS-10248 in CSV but is associated with site IF-RV-10266 in postgres
[error] [metric values] Sample 164313 has site GR-TR-1106 in CSV but is associated with site San Rafael 6 in postgres
[error] [metric values] Sample 164315 has site GR-TR-1289 in CSV but is associated with site 3MILEUP in postgres
[error] [metric values] Sample 164318 has site PR-LS-13308 in CSV but is associated with site SPR12-04 in postgres
[error] [metric values] Sample 164354 has site FI-LS-26225 in CSV but is associated with site W3151 in postgres
[error] [metric values] Sample 164680 has site CY-TR-1012 in CSV but is associated with site CASTC-01 in postgres
[error] [metric values] Sample 164683 has site CY-TR-1319 in CSV but is associated with site 495715 in postgres
[error] [metric values] Sample 164684 has site CY-TR-1319 in CSV but is associated with site 495715 in postgres
[error] [metric values] Sample 164686 has site CY-TR-1477 in CSV but is associated with site LWARCHCYN in postgres
[error] [metric values] Sample 164687 has site CY-TR-1477 in CSV but is associated with site 4953193 in postgres
[error] [metric values] Sample 164697 has site MB-SS-10066 in CSV but is associated with site PFC:UT-04 in postgres
```

Can anyone shed some light on these CSV site names? Do they indeed look like legacy site names that have since changed but the spreadsheet still has the old values?

**Comment by David-Fowler** [comment]
The CSV data is using ReachID not Station. You can make the import linking back to the ReachID (customerStation) field in the Sample table. That should allow the necessary link to occur.

Be careful with all the others that did map in as sometimes a ReachID exists as a Station in the database but it is not actually referring to the same station. So it would be safer to map everything to ReachID (customerStation) and/or re-verify the import data's origin to make sure station is used.

**Comment by philipbaileynar** [comment]
Thanks @David-Fowler 

I'm not actually using the site to link. It's just a sanity check, which is why it freaked me out when so many didn't match up!!!!!!

So I will ignore the warnings. 

The link is by sample ID is reliable.
