### ISSUE TITLE
Create GitHub repo for NAMC models

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#176]
* Create a new repo in the [namc-utah](https://github.com/namc-utah) organization to store model R code (and accompanying miscellaneous files). The repo should be called `namc-models`
* This is a private repo. Please create a README.md, but no license file for now.
* Each model should have at least one R script as well as several optional CSV, text and RData files.
* The repo should look like:

```
\final_models\
\final_models\<model_name>
\final_models\<model_name>\<model_script>.R
\final_models\<model_name>\<model_data>.csv (optional)
\final_models\<model_name>\<model_data>.Rdata (optional)
\experimental_models\
\experimental_models\ (none here yet)
```

The two sources of these files are on S3 under nardata/Matt:

* Final Models.zip (organism models)
* WQ models.zip

A few comments:

* All the files are small, most less than 10Mb apart from the Wyoming (WY) Alkalinity.RData file that is 1Gb. I have asked @Feldspar5 if this file is valid but have yet to hear back from him.
* Renaming/standardizing R script file names is OK, but I would be careful renaming data files. I presume that the scripts reference these by name. We intend to have @David-Fowler write a wrapper R script to run each model (so that calls to the API are centralized). So @David-Fowler might end up standardizing the model script and other file names too.

Please research if GitHub LFS is appropriate. I will verify with @Feldspar5  and @courtwrightj01 which git clients they are using and that this client also supports LFS.

**Comment by MattReimer** [comment]
New Repo:
https://github.com/namc-utah/namc-models

The git ignore leaves the data files out of it so only the `.R` files are included.
