### ISSUE TITLE
Samples API endpoint revamp

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#180]
# Background

Several generic API endpoints for the big tables in the database (sites, samples and boxes) were underperforming for two key  reasons:

1. Inefficient SQL
1. Pulling back too much data

I have rewritten these queries to make them more efficient. Also, they now **must** be called with at least one list of parameters. For example, when you request `samples` you must provide of either of:

* array of sample IDs
* array of box IDs
* array of project IDs
* array of entity IDs (customers)
* array of site IDs

This is all through one endpoint "samples". We have done something similar before for organisms. i.e. the node.js code needs to check that at least one of these arrays is passed and that it's not empty. If no array is passed then throw warning.

This pattern is repeated for samples, sites and boxes as you will see below.

# Samples

Change the existing `samples` endpoint to take one of the following arguments

* array of samples -> [sample.fn_samples](https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/02_sample_functions.sql#L121)
* array of projects -> [sample.fn_project_samples](https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/02_sample_functions.sql#L177)
* array of boxes -> [sample.fn_box_samples](https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/02_sample_functions.sql#L201)
* array of entities -> [sample.fn_entity_samples](https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/02_sample_functions.sql#L224)

# Samples by Polygon

Add a new endpoint for requesting all samples within a polygon. Note the DB does checking on the validity of the GeoJSON polygon. This is similar to [taxa within polygon](https://github.com/namc-utah/namc-bug-db/blob/dev/packages/common/src/schema.graphql.ts#L143).

* samplesWithinPolygon -> [sample.fn_polygon_samples](https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/02_sample_functions.sql#L224)

# Samples by Point and Distance

Add a new endpoint for requesting all samples within a distaince (metres) of a point (latitude and longitude in decimal degrees). Note the stored procedure does bounds checking on all three of these parameters. This is similar to [taxa point and distance](https://github.com/namc-utah/namc-bug-db/blob/dev/packages/common/src/schema.graphql.ts#L140)

* samples within point and distance -> [sample.fn_point_distaince_samples](https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/02_sample_functions.sql#L278)

**Comment by MattReimer** [comment]
From our discussion:

Data being requested |   | Array of Samples | Array of Boxes | Array of Projects | Array of Sites | Array of Entities | Polygon | Point and Distance
-- | -- | -- | -- | -- | -- | -- | -- | --
Samples |   | Y | Y | Y | Y | Y | Y | Y
Sites |   | Y | Y | Y | Y | Y | Y | Y
Boxes |   |   | Y |   |   | Y |   |  
Projects |   |   |   |   |   |   |   |

**Comment by MattReimer** [comment]
THis should be complete.
