### ISSUE TITLE
Migrate Incomplete boxes and Samples From BugLab to New Database

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#183]
Enhance the Python migration to incorporate incomplete boxes from BugLab. Currently the script only migrates complete boxes.

**Comment by philipbaileynar** [comment]
Various combinations of flags from BugLab:

| waiting | onhold | active | complete |  |
| :--- | :--- | :--- | :--- | :--- |
| false | false | false | false | 1 |
| true | false | false | true | 1 |
| false | false | true | false | 23 |
| false | true | false | false | 2 |
| true | false | false | false | 30 |
| false | false | false | true | 686 |

**Comment by David-Fowler** [comment]
1. Non-complete boxes do not have samples present in Pilot. Those samples must be migrated.
2. All boxes regardless of status are in both databases (but only the box not the samples). When boxes are created records are placed in both databases having the same key (boxid). This was to guarantee we could always get to the set of data by boxid no matter the database it was currently on. Once completed the box record in PilotDB gets updated with the final count, dates etc.

Boxes were occasionally merged with other boxes thereby changing the counts present in each (so the count in Pilot's Boxtracking) will not always match BugLab's. Other changes also occur which can make matching harder.

It would also be nice to maintain the original submission data from BugLab's submission tables (wrap them up as JSON and drop them in the new db). That data is occasionally needed for data validation.

I also have a partial sql script meant to perform a full cross-database comparison of completed boxes to get an overall QA viewpoint of all the data. Over the years there have been some messy replications / partial merges / temporary manipulations of data that I have wanted to fully identify and validate their statuses. I will try to run this in the next week and walk through it to identify potential data we need to handle in a special manor.

**Comment by David-Fowler** [comment]
For the two top ??? BugLab Samples where only a single box is present you do not have to handle them (just ignore them). The first, is already in PilotDB and was most likely reactivate in BugLab for viewing purposes and never got deactivated. The second is a test box used for things like training, data handing checks etc. We may want similar box(es) in the new database but they should be created with fresh data and/or data that is more comprehensive.

**Comment by philipbaileynar** [comment]
This worked out really well. I now have active, waiting and onhold boxes and their samples migrating to the new system.
