### ISSUE TITLE
New API endpoint needed for organizations

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#184]
Please create a new API endpoint that calls [entity.fn_organizations](https://github.com/namc-utah/namc-bug-db/blob/dev/docker/postgres/initdb/02_entity_functions.sql#L45-L98)

API endpoint name:

`organizations`

Arguments:

* limit
* offset
* searchTerm (optional string that filters the organizations by name)

Returns:

Usual "records" structure with the fields shown in the stored proc definition.

**Comment by MattReimer** [comment]
The changes have been deployed to staging
