### ISSUE TITLE
BugData Notes

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#195]
This is a question about the "notes" stored with bug data. For reference here is a tiny subset of such records from Pilot:

| sampleid | code | lifestage | bugsize | SplitCount | bigrarecount | notes |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | 179 | L | NULL | 16 | 0 | I |
| 2 | 1743 | A | NULL | 1 | 0 |  |
| 2 | 1217 | A | NULL | 0 | 2 | ,Measurements:<br/>1@51mm<br/>1@33mm |
| 1 | 599 | A | NULL | 4 | 0 | R,Class material |
| 734 | 179 | L | 2.5 | 1 | 0 | ,damaged |
| 730 | 208 | P | 3 | 1 | 0 | ,Only found 3 pupae |
| 730 | 208 | P | 2 | 2 | 0 | ,Only found 3 pupae |
| 2892 | 5430 | A | 2 | 1 | 0 | ,Terrestrial |
| 1767 | 182 | L | 3 | 1 | 0 | M,T |
| 1729 | 760 | L | 0.2 | 158 | 0 | ,Napulii |
| 1729 | 100 | A | 2.4 | 0 | 1 | U,Terrestrial |
| 1274 | 578 | L | 14 | 1 | 0 | ,Correct measurement is 14.2 |
| 1274 | 578 | L | 13 | 1 | 0 | ,Correct measurement is 13.4 |
| 1280 | 480 | L | 1 | 1 | 0 | I |
| 1281 | 121 | L | 4.6 | 1 | 0 | I,U |
| 1281 | 121 | L | 4.4 | 1 | 0 | U |

The old tables do not have a primary key and so we need to determine what constitutes a unique bug data record.

Up to this point I have been ignoring notes and simply grouping records by the following three columns that form a unique index in the new database:

- Code (taxon)
- life stage
- bug size

If there were multiple records across these three columns I simply summed the split counts for the single record in the new database. However, now I am considering the notes I have discovered that I can no longer simply group on these three columns because some records have different notes. So there might be something like:

| sampleid | code | lifestage | bugsize | SplitCount | bigrarecount | notes |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
|1234|1|L|2|1|0|D|
|1234|1|L|2|1|0|U|

# Option 1

If we need notes to distinguish bugdata records then I need to incorporate them into the bugdata table primary key. @David-Fowler originally wanted the notes in a lookup table so that we could report on the number of occurrences of different note types (e.g. "how many damaged occurences of taxon X"). I can still accomplish this by storing the notes as an array of values (rather than the current comma separated values that are hard to work with). The primary key on bug data would then become:

- Code
- life stage
- bug size
- notes (array of strings)

# Option 2

We could merge bugdata records across code, life stage and bug size and simply concatenate the notes. I don't think this is a good idea because it fundamentally alters the original data (e.g. the two rows above would be combined into one with the note "D,U" which misrepresents the original observation).

# Option 3

We could create a new table called `organism_notes` that assigns a unique integer ID to each unique combination of notes. This "bug note primary key" would then become part of the primary key in bugdata. So you could have multiple taxon, life stage and bug size records so long as they are distinguished by a different note ID.

- Code
- life stage
- bug size
- note_id (foreign key to new table called sample.organism_notes that has one record for each unique note combination)

# Related Question

- In past conversations, Trip has suggested that we only need to retain [official note types](https://github.com/namc-utah/namc-bug-db/blob/master/docker/postgres/initdb/10_taxa_note_types.sql) and discard all the old hand written notes (e.g. "Terrestrial" and "Correct Measurement" above). But I am seeing some important information in these data! I recommend that if on a go forward basis we only capture official note types that we at least store the legacy values (if only for an initial period and drop them later).

**Comment by Feldspar5** [comment]
From a functional perspective, I do not really see a difference between 1 and 3.  I do want to note, however, that notes are not a field that we ever really access.  In many cases (eg., D, U) they may be read by EU in order to understand why an identification was not taken to a finer resolution.  They are not data we use otherwise.  I do respect their integrity and need to keep them separate.  I propose either of the two options (1 & 3) and lean towards whichever is the simplest to execute.  

There was no question in the RQ section at the end, but I concur with the idea presented.

**Comment by David-Fowler** [comment]
The notes like those you have identified are suppose to be concatenated. I believe most of those identified would have to be historical as STREAM has only ever concatenated notes and not distinguished notes with different counts (i.e. they are not part of the primary key). As a taxonomist identifies and groups individuals any notes applying to individuals get concatenated with the notes of other individuals in the same group (where a group in this case is represented by the 4 fields making up the primary key).

It sounds like there is a desire to move away from the definition / junction table approach? Is there a reason for this? While there are other ways to store definitions, abbreviations, active / inactive values the table approach makes it clean, straight forward and easy to extend / manage. Is the thought to use enumerators with arrays? I would just prefer to see us store both values and descriptions in the database.

**Comment by philipbaileynar** [comment]
@David-Fowler there are no primaries keys on either BugLab.BugData or PilotDB.BugData, that's the cause of the problem.

Here's my proposed solution:

1. Notes will be stored in a junction table as originally planned.
1. The primary key of the new BugData table (called `sample.organisms` in the new database) will be:
        - SampleID
        - Code
        - LifeStageID
        - BugSize
1. Any records that break this primary key are legacy data and can be grouped, summing SplitCount and concatenating notes.

I will be implementing this first thing Friday. Please object before then...

**Comment by philipbaileynar** [comment]
Here's the query that I'm now using to import BugData:

```sql
SELECT B.SampleID, Code, LifeStage, BugSize, Sum(SplitCount) SplitCount, Sum(BigRareCount) BigRareCount, string_agg(Notes, ',') notes, count(*) tally
FROM PilotDB.dbo.BugData B INNER JOIN PilotDB.dbo.BugSample BS on B.SampleID = BS.SampleID
GROUP BY B.SampleID, Code, LifeStage, BugSize;
```

**Comment by David-Fowler** [comment]
That should be good.

**Comment by Feldspar5** [comment]
I have no objections to this
