### ISSUE TITLE
Qualitative Metrics

### ISSUE THREAD

**Issue by David-Fowler** [namc-utah/namc-bug-db#201]
@philipbaileynar after a discussion with @Feldspar5 it became apparent that we missed the proper handling of qualitative metrics and summaries. Qualitative samples where no area exists still need to calculate metrics and densities. How this has been done to date is to replace all density values in formulas with a simple sum of the split count (big rare was included previously but is not any longer). Densities refer to the split and area corrected individual counts for quantitative samples; these all become just a sum of the individual counts across life stage, measurements etc.

A case statement in a single place was able to handle this previously so I am hoping something similar can be done now. If I get a chance to dig into the code more I will issue a pull request with a fix.

**Comment by philipbaileynar** [comment]
There are 14,733 samples that are flagged as qualitative but have area specified.

```sql
select count(*) from sample.samples where qualitative and area is not null;
```

The areas are spread across over 100 different values. Here are just the 10 most frequently occuring:

| area | count |
| :--- | :--- |
| 1 | 13813 |
| 0.74 | 269 |
| 0.002123992 | 56 |
| 1.85 | 47 |
| 0.14 | 45 |
| 1.67 | 44 |
| 0.5 | 37 |
| 0.046 | 28 |
| 3.2 | 24 |
| 0.09 | 21 |

```sql
select area, count(*) from sample.samples where qualitative and area is not null group by area order by count(*) desc limit 10;
```

And here is the simple query I am using to set null on area column for all historical qualitative samples. This query gets executed at the end of the data migration.

```sql
update sample.samples set area = null where qualitative;
```

**Comment by philipbaileynar** [comment]
Incorrectly closed this issue!
