### ISSUE TITLE
Sample Taxa Attributes Endpoint

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#206]
Distinct taxa with attributes. This will get pivoted in R so scientific_name are rows, attributes are columns and attribute values are cell contents.

```sql
select s.sample_id, t.taxonomy_id, t.scientific_name, a.attribute_name, ta.attribute_value from sample.organisms o
inner join sample.samples s on o.sample_id = s.sample_id
    inner join taxa.taxonomy t on o.taxonomy_id = t.taxonomy_id
inner join taxa.taxa_attributes ta on t.taxonomy_id = ta.taxonomy_id
inner join taxa.attributes a on ta.attribute_id = a.attribute_id
where s.box_id = 2000
group by s.sample_id, t.taxonomy_id, t.scientific_name, a.attribute_name, ta.attribute_value;
```

**Comment by philipbaileynar** [comment]
The stored procedures for this are done. Reassisning to @MattReimer to implement the API...

This follows the pattern of several other endpoints whereby there's a single endpoint that can be called with one of several different types of inputs:

## endpoint name

`sample_taxa_attributes`

## arguments

|argument| stored proc|
|---|---|
|array of sample IDs|`sample.sample_taxa_attributes(p_limit int, p_offset int, p_sample_ids int[])`|
|array of box IDs|`sample.box_taxa_attributes(p_limit int, p_offset int, p_box_ids int[])`|
|array of project IDs|`sample.project_taxa_attributes(p_limit int, p_offset int, p_project_ids int[])`|
|array of entity IDs|`sample.sample_entity_taxa_attributes(p_limit int, p_offset int, p_entity_ids int[])`|
|polygon|`sample.polygon_entity_taxa_attributes(p_limit int, p_offset int, p_polygon text)`|
|point and distance|`sample.point_distance_taxa_attributes(p_limit int, p_offset int, p_polygon text)`|

## return type

All these queries return the same records with the same fields:

- sample_id       int,
- taxonomy_id     smallint,
- scientific_name varchar,
- attribute_id    int,
- attribute_name  varchar,
- attribute_value varchar

**Comment by MattReimer** [comment]
@philipbaileynar note that the name of a query has changed:

https://github.com/namc-utah/namc-bug-db/commit/b3983d08c7879ceddbd90b4041bb3e83e3e670d0#diff-d077771eb4d0124d67aaeb93323bcf094a511174f6ff2cb1bc58b40671489009R1033
