### ISSUE TITLE
How to Parse JSON in R?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#207]
@David-Fowler can you provide a couple lines of R code that can deserialize JSON please?

So a typical API endpoint might return the following data frame:

| taxonomy\_id | scientific\_name | metadata |
| :--- | :--- | :--- |
| 1 | Annelida | {"status": "Verified"} |
| 4 | Aeolosomatidae | {"status": "Verified"} |
| 5 | Branchiobdellida | {"status": "Verified"} |

and we need a couple of lines of code to produce the following data frame:

| taxonomy\_id | scientific\_name | status |
| :--- | :--- | :--- |
| 1 | Annelida | Verified |
| 4 | Aeolosomatidae | Verified |
| 5 | Branchiobdellida | Verified |

FYI @courtwrightj01 @Feldspar5

**Comment by David-Fowler** [comment]
The latest version of NAMCr has auto expansion abilities (turned on by default) when using the query function. The save function will get a similar update shortly. 

I think it is best when dealing with data going into the database that the code handling the JSON is in one spot; the added function arguments are self explanatory but will also be well documented. It should enable all our API "use" code to be cleaner and worry less about technical details.

For knowledge though and using the most compact form the below will work:
`data = data %>%
    lapply(jsonlite::fromJSON) %>%
    lapply(as.data.frame, stringsAsFactors = FALSE) %>%
    dplyr::bind_rows()

#OR using the NAMCr built in functions
data = NAMCr::json.expand(data, "metadata")
# and collapsing
data = NAMCr::json.expand(data, "newField", c("field1","field2"))
`

Note: the NAMCr package I explicitly am not forcing a dplyr package dependency therefore the code in the package is different. It can be viewed here [https://github.com/namc-utah/NAMCr/blob/main/R/utilities.R](url).

**Comment by David-Fowler** [comment]
Updated the last comment's code block to be a little more explicit for those that are interested
