### ISSUE TITLE
Partial Split Counts

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#220]
- There are 63,344 split_counts in the database that are not wholly divisible by 1.
- They occur across 1,837 samples
- They occur across two boxes:

| box\_id | box\_received\_date | organization\_name |
| :--- | :--- | :--- |
| 1251 | 2009-05-01 00:00:00.000000 +00:00 | BLM - OR - Prineville District Office |
| 1949 | 2018-03-09 00:00:00.000000 +00:00 | Utah State University - Buglab |

Here are 5 sample records:

| sample\_id | taxonomy\_id | life\_stage\_id | bug\_size | split\_count | big\_rare\_count |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 140605 | 19 | 3 | NULL | 3.59 | 0 |
| 140605 | 121 | 3 | NULL | 390.95 | 0 |
| 140605 | 173 | 3 | NULL | 17.93 | 0 |
| 140605 | 179 | 3 | NULL | 14.35 | 0 |
| 140605 | 180 | 3 | NULL | 1215.88 | 0 |

```sql
select b.box_id, b.box_received_date, o.organization_name
FROM (
         select sample_id
         FROM sample.organisms
         where mod(split_count::numeric, 1::numeric) <> 0
         group by sample_id
     ) s
         inner join sample.samples ss on s.sample_id = ss.sample_id
         inner join sample.boxes b on ss.box_id = b.box_id
         inner join entity.organizations o on b.customer_id = o.entity_id
group by b.box_id, o.organization_name;

select sample_id, taxonomy_id, life_stage_id, bug_size, split_count, big_rare_count
FROM sample.organisms
where mod(split_count::numeric, 1::numeric) <> 0
limit 5;
```

**Comment by philipbaileynar** [comment]
@David-Fowler curious if you recall the reason why a) partial split counts exist, and b) if they are still needed?

**Comment by Feldspar5** [comment]
Yes, please explain why these are not simply integer values direct from bench.  What am I missing?

**Comment by David-Fowler** [comment]
These are pre split values. Data that we obtained without the proper split data. This as you can see is a rare occurrence yet we needed to be able to handle the data.

I will get more specifics regarding the datasets as I know I have them but I almost think at least one was AIM related in some way.

**Comment by philipbaileynar** [comment]
@David-Fowler  can you explain to a novice (me) what pre-split means please?

There are ~ 2,000 boxes and only 2 have this special case:

1. Can these be retroactively adjusted to regular split count, thereby allowing the split count column to be made integer?
1. Through what method would additional data like this get into the database?

**Comment by Feldspar5** [comment]
Box 1949 is imported data from the state of WY when we were working with their model to develop a sub-model.  I have no idea what the 1251 box is but clearly it was imported data as well.

What is interesting is that 2170 should have suffered the same decimal state, but is all integers.  In the case of 2170 (and likely 1949), data were processed in external lab that did not provide agency with actual counts.  David might remember if we needed to convert the counts in 2170 to integers.  If so, we should perform the same arithmetic to the other 2 and get rid of all decimal splits.

**Comment by Feldspar5** [comment]
1949 contains 'raw' data in the notes field and a scale factor in the labnotes field.  Unfortunately, there is a unique scale factor for every sample (n=1951) so I cannot reverse engineer the true 'raw' values.  Given the qualitative data in 1949 and that the raw and scale values exist in the data, I am leaning towards either truncating split values or rounding.  We will not use these qualitative data for analyses later on and can always replicate the existing decimal split values.

**Comment by Feldspar5** [comment]
1251 is an imported set of data that does not contain any notes fields with data.  It is listed as quantitative though.  I propose we round all of these split counts to nearest integer.  The numbers given represent total number of organisms found in a square meter of stream bed; there are no scaling factors from field split, area, or lab split.  All of these are 1.  So changing 60.97 to 61 will not alter data in a meaningful way.

**Comment by philipbaileynar** [comment]
I am eager to make `split_count` an integer field. Here are the actions I plan to take:

1. Box 1949:
    - store the RawCount value currently in the notes field and store it in split_count
    - store the split_count in the notes field in the new system (so we have it to refer to should we need to circle back)
1. Box 1251:
    - round the split_counts to the nearest integer.
    - store the old split_count value in the notes field.

Remember, once I do this the database will only ever be able to store integer bug count data!!!!! This is an important decision.

@Feldspar5 @courtwrightj01 @David-Fowler please comment your approval before I proceed.

**Comment by Feldspar5** [comment]
Split counts should/can only ever be integers, so this decision is solid.  

Box 1949: existing split counts should be rounded and then stored as integers in split_count.  The two notes fields can hopefully be stored as well (raw counts and scale factor).  The raw count value in the notes field (currently) should not be stored as the split count.

**Comment by David-Fowler** [comment]
Box 1949:
- do what you mentioned above
- also change the labsplit to match the percentage equal to the CorrFact value stored in LabNotes

Box 1251:
- do what you mentioned
- this box of data is a little odd and contains data that is quite old and from multiple data sets. I believe some of the data was adjusted to match the splits of other data and / or processed externally and then imported. Rounding the data should be ok.


This does raise the question of what if we want to import data like this in the future, where we are only given processed data and we have to fill in splits, it would not be possible. This makes us less nimble but does make our data more standardized (get stuff done fast versus going back and forth trying to get all the data we need ). This would hold true for research project as well where maybe we just want to get test data into db.

That said trying to enforce integers is probably best long term and forces research to follow good practices.

Ok I will stop ranting now... I think we all get it.

**Comment by Feldspar5** [comment]
Box 1949: Those correction factors are not lab splits; why do you think we should store them that way?  

We recently ingested a huge dataset from ORDEQ for which no split data were available.  I think we just called everything at 100%.  We also occasionally receive pre-sorted material and rarely receive true splits from them.  Again, we call these 100%.

But still, all integers.

**Comment by David-Fowler** [comment]
Using the correction factors as a lab split yield the integer counts we are after (i.e. the correction factor times the raw count stored in bugdata notes equals the non-integer split counts currently stored). While we may get data without the proper splits we try our best to validate and work with the customer to get the most accurate data possible. In this case some process adjusted the raw counts to make these non-integer values (behaving like a split would: either field or lab) and that process makes the counts more scientifically relevant based on the areas given. Since we have knowledge of the adjustment and want to use the raw counts I figured we could store the adjustment as well such that metrics etc come out more relevant.

Granted this is a qualitative sample set so perhaps all this is irrelevant in this case. Up to you.

**Comment by Feldspar5** [comment]
I agree and had worked out the arithmetic.  My point is that those correction factors are not lab splits; there are far too many unique values there.  You know there are only a a small number of possible split values.  As long as we keep the data I am OK.  And yes, it is qualitative so, meh.

**Comment by David-Fowler** [comment]
In short if this were a Quan sample we rarely look at raw counts, we look at the corrected count (splits, area, raw count to density). Essentially the stored decimal values are the corrected count and with splits at 100% and an area of 1 this count would be unchanged if attempted to re-correct it. 

Because qualitative metrics do not take into account the area the results in our report would have been different had we used the raw integer counts. I believe we did what we did because we wanted those decimal values out in the report.

**Comment by philipbaileynar** [comment]
Split counts are now integers. Regarding box 1949, I followed @Feldspar5 request:

> Box 1949: existing split counts should be rounded and then stored as integers in split_count. The two notes fields can hopefully be stored as well (raw counts and scale factor). The raw count value in the notes field (currently) should not be stored as the split count.

So the split counts for this box are simply the old split count rounded to nearest integer. The lab_split for these samples is 1.
