### ISSUE TITLE
Is Benthic the only sample type that allows qualitative?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#257]
Benthic samples can be quantitative and qualitative. Can the other sample types also be qualitative?

- Zooplankton
- Drift
- Fish Diet

**Comment by Feldspar5** [comment]
Drift samples could theoretically be qualitative, but they never are.  They are always very quantitative.  NAMC is comfortable making the decision to not accept qualitative drift samples.

Fish diet samples are always quantitative, but the unit of measurement is not area/volume, but rather /fish.  This can be further analyzed using length or mass, but we will always know that a sample comes from a single fish.

Zooplankton samples are usually tows through still water.  In many ways like a drift sample (fixed net, moving water) in that they both sample a known volume of water.  The answer here is the same as drift: no reason there could not be a qual zooplankton sample, but we should not accept them (no ever expect them).
