### ISSUE TITLE
BoxId -1

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#26]
There is a BoxId of -1 in PilotDb that belongs the the CustID **USU-BUGLAB**. This box does not appear to have any samples assigned to it. Can you explain if this box has some special purpose or if it needs to be migrated to the new system?

```sql
SELECT * FROM BugSample WHERE BoxID = -1;
```

mention @Feldspar5 @courtwrightj01

**Comment by David-Fowler** [comment]
It does actually have 5 samples in it but they are on the frontend BugLab database. It is a test / training box last I knew allowing people to get comfortable with STREAM without using live data.
