### ISSUE TITLE
Default Project

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#27]
Do we need/have a concept of a "default project"? For example, when the BLM submits a box of samples, how are they assigned to a project such as AIM? Is this done manually (perhaps during submission approval?) or is it automated? 

If it is not automated, could it be? Could we have a "default project" for some, but not all, customers that then gets assigned to any submissions by that customer. Or perhaps we would assign it by station/site? Stations would have a default project(s) that get assigned when new submissions are assigned to that site?

This isn't a high priority, but it seems like an easy enhancement (providing it doesn't create more work by erroneously assigning samples to the wrong projects).

**Comment by Feldspar5** [comment]
Many sets that come in do not get assigned projects, nor do they need them.  Projects really are just that – projects.  So a BLM office in Las Cruces sends in 20 samples one year, and 18 the following year.  Neither set gets a project, but can be searched for using customer or other identifiers (eg. location).  I think project needs to be a field that is called out on submission at the NAMC side, but will need to remain manual.  Currently it is a field that can be ignored, which is no good.  Is there a way to provide targeted prompts like “these samples look like they might be part of the following projects: X, Y, Z.  would you like to assign this set to an existing project?”

Here is a recent example that might help.  We have a 2yr project with USFS in CO.  NAMC collected a set of samples and entered as the customer and assigned new project.  Then USFS crew collected set #2, which we entered with them as customer and tagged with same project (all samples in round 2 were repeat samples from round 1).   Summer 2021 we will do it all again, creating 2 more sets with the same project ID, but different customers.

Trip
