### ISSUE TITLE
Stations with missing locations

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#28]
There are 1453 stations in PilotDB with missing latitude and longitude. Is there any way of obtaining coordinates for these stations? Excel, CSV, ShapeFiles etc? I am happy to process these legacy formats and incorporate the data into the new database if they exist.

Just as a sample, here are the first 20 stations with missing coordinates:

| Station | ReachName | System1 | System2 | System3 | Location | SiteDesc | HucCode | Basin | CustID | Lat | Long | CardinalDirection | Zone | Northing | Easting | State | County | Country | Elevation | Special | LandUse | Reference | Storet | RefCriteriaID | Notes | GISnote | DelineatedBy | Shapefile |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 0000003 | NULL | Lotic | Stream | NULL | Johnson Creek \(1\) | NULL | NULL | NULL | DEQ-01 | NULL | NULL | North      | NULL | NULL | NULL | UT | San Juan | USA | NULL | Test New | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 00R073121A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 00R091318A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 01R090116A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 01R091314A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 02R091221A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 03R090118A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 04R090120A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 05R090714A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 05R091419A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 06R091316A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 07R090716A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 07R091417A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 08R090716B | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 09R090719A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 10R091519A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 11R090720A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 12R091214A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 13R091215A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |
| 15R090621A | NULL | Lotic | Stream | NULL | Unknown Place | NULL | NULL | NULL | USFWS-03 | NULL | NULL | NULL | NULL | NULL | NULL | OR | Klamath | NULL | 0 | NULL | NULL | N | NULL | NULL | NULL | NULL | NULL | NULL |

**Comment by philipbaileynar** [comment]
I would dearly like to make the location a required field for stations, but these missing sites are preventing me from doing so!

**Comment by courtwrightj01** [comment]
Do any of these stations actually have sampleIDs associated with them? If not I would remove altogether. If there is actual data associated with them, I am not sure what do say... remove and put in a relic DB? The data isnt much use to us without lat and long

**Comment by philipbaileynar** [comment]
1419 of the stations have one or more samples associated with them.

Here are the stations, sample ID, box ID and customer ID for the first 20 of them, ordered by sample date descending. Looks like 2013 was the newest.

| Station | SampDate | SampleID | BoxID | CustId |
| :--- | :--- | :--- | :--- | :--- |
| FRAZI-01 | 2013-07-08 00:00:00.000 | 151330 | 1604 | USFS\_R5\_F11\_D1 |
| AZBLM:12 | 2010-11-20 00:00:00.000 | 144334 | 1376 | BLM-AZ-410 |
| AZBLM:16 | 2010-11-20 00:00:00.000 | 144338 | 1376 | BLM-AZ-410 |
| AZBLM:17 | 2010-11-20 00:00:00.000 | 144339 | 1376 | BLM-AZ-410 |
| AZBLM:14 | 2010-10-19 00:00:00.000 | 144336 | 1376 | BLM-AZ-410 |
| LVRCRK-Q | 2010-10-15 00:00:00.000 | 143882 | 1329 | NPS-NCPN-ZION |
| RFKNCK-Q | 2010-10-15 00:00:00.000 | 143888 | 1329 | NPS-NCPN-ZION |
| LFKNCK-Q | 2010-10-15 00:00:00.000 | 143889 | 1329 | NPS-NCPN-ZION |
| AZBLM:13 | 2010-10-14 00:00:00.000 | 144335 | 1376 | BLM-AZ-410 |
| AZBLM:18 | 2010-10-14 00:00:00.000 | 144340 | 1376 | BLM-AZ-410 |
| AZBLM:19 | 2010-10-14 00:00:00.000 | 144341 | 1376 | BLM-AZ-410 |
| AZBLM:15 | 2010-10-14 00:00:00.000 | 144337 | 1376 | BLM-AZ-410 |
| BEARIVER-7 | 2010-08-02 00:00:00.000 | 143157 | 1344 | DEQ-01 |
| NORTHCRK-Q | 2010-07-01 00:00:00.000 | 143873 | 1329 | NPS-NCPN-ZION |
| RFKNCK-Q | 2010-07-01 00:00:00.000 | 143874 | 1329 | NPS-NCPN-ZION |
| LFKNCK-Q | 2010-07-01 00:00:00.000 | 143875 | 1329 | NPS-NCPN-ZION |
| LVRCRK-Q | 2010-06-28 00:00:00.000 | 143866 | 1329 | NPS-NCPN-ZION |
| PIBO:1522 | 2010-06-26 00:00:00.000 | 145997 | 1369 | USFS\_502 |
| SLCO-121 | 2009-11-23 00:00:00.000 | 143447 | 1356 | SLCWR-01 |
| SLCO-116 | 2009-10-14 00:00:00.000 | 143444 | 1356 | SLCWR-01 |

```sql
SELECT S.Station, BS.SampDate, BS.SampleID, BS.BoxID, B.CustId
FROM SiteInfo S
    INNER JOIN BugSample BS ON S.Station = BS.Station
    INNER JOIN BoxTracking B ON BS.BoxID = B.BoxId
WHERE Lat IS NULL OR Long IS NULL
ORDER BY BS.SampDate DESC;
```

**Comment by David-Fowler** [comment]
If I remember right most are all pre-STREAM. Some sites may have been fixed but the samples referring to them were not updated. We can run some queries to test if the reachid's, storets and stations were linked back wrong or have other potential connections.

Also, I believe some historic data only had UTM values (which I never got around to cleaning up and converting to lat, long)... again pre-STREAM.

It is data like this that has prevented many db constraints from being applied over the years. The data was slowly being cleaned up. I will add this to some checks and see if I can dig up anything further.

**Comment by philipbaileynar** [comment]
The 20 I just looked at do not have Easting or Northing either.

**Comment by David-Fowler** [comment]
Ok. We can resolve most of these by reaching out to the gov't organizations. They are historic sites but the names should match their records. Also many of these BLM sites have associated Aliquot parts in their sitedesc field which can help id their location (I believe though we may still need to reach out to BLM for it)

Also, some have UTM or L/L in the Notes field....

We have some cleanup to do...

**Comment by Feldspar5** [comment]
I ageee completely.  Data without locations should not be moved into new database.  We should probably delte them all, but just as easy to hoard in Box.

Trip

**Comment by Feldspar5** [comment]
Although you present some optimism David, I do not cherish the idea of squeezing >1400 locations from the BLM…

**Comment by Feldspar5** [comment]
Location does have to be required.  Absolutely.

**Comment by philipbaileynar** [comment]
Thanks everyone for your input. Here's how I intend to proceed:

1. Location will be a required field for stations.
1. Only stations with valid locations will be migrated to the new system (for now).
1. All samples will be migrated to the new system, but those with missing/invalid locations will have their station set to NULL and instead the station identifier stored in their metadata field.
1. We can easily identify the affected samples and systematically tackle the missing stations at a later date. As their locations are resolved we can migrate the recovered stations into the new database and associate them to the correct samples using the metadata mentioned earlier.

This strategy lets us implement the desired database design and provide a roadmap to getting the incompatible historical data into the new systen.

**Comment by philipbaileynar** [comment]
Export a list of these sites and provide to @Feldspar5 and @courtwrightj01

**Comment by philipbaileynar** [comment]
@courtwrightj01 here is a CSV export of all 1573 sites from PilotDB that are missing coordinates and have at least one sample associated with them.

I have included the box and customer IDs. Let me know if there are other fields that might be useful. Note I have collapsed Location and SiteDesc into a single column as these columns never seem to both contain information. It's always one or the other.

@David-Fowler just checking that coordinates for these sites are not available from some other SQLServer Spatial column?


[2021_01_29_SitesWithNoCoordinates.csv.zip](https://github.com/namc-utah/namc-bug-db/files/5896669/2021_01_29_SitesWithNoCoordinates.csv.zip)

Here's the query that I used to export these data:

```sql
SELECT SI.Station,
       SI.ReachName,
       REPLACE(REPLACE(ISNULL(SI.Location, SI.SiteDesc), ',', ' '), '  ', ' ') AS SiteDescription,
       SI.State,
       SI.County,
       BS.BoxId,
       BT.CustId
FROM SiteInfo SI
         JOIN BugSample BS on SI.Station = BS.Station
         JOIN BoxTracking BT on BS.BoxID = BT.BoxId
WHERE Lat IS NULL
   OR Long IS NULL
GROUP BY SI.Station,
         SI.ReachName,
         SI.Location,
         SI.SiteDesc,
         SI.State,
         SI.County,
         BS.BoxId,
         BT.CustID
ORDER BY Station
```

**Comment by Feldspar5** [comment]
Jennifer et al - There are 92 customers on this list.  A quick pivot reveals that a little more than 50% of the samples on this list are from 9 customers, including UT DEQ, NAMC, Chuck, and BLM Prineville.  These are all customers to whom we could reach out to get more information (well, not NAMC, ironically).  But then there are other customers lower down on the list from whom we could seek more info (NPS groups, BLM FOs, PIBO), but these are for such a small number of samples.  So then I question the value of any of these samples.  My concluding reaction is to toss them all, but would like to hear from Jennifer as well - or from David if there are possibly locations elsewhere (I doubt this though).

**Comment by philipbaileynar** [comment]
OK, I am closing this issue.

Any samples associated with sites that do not have a location are omitted from the new system. 

If this decision changes and NAMC wants to recover some of these sites and samples in the future they can be imported manually.
