### ISSUE TITLE
PilotDB.BugData.Notes

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#29]
We were planning to move the contents of the `PilotDB.BugData.Notes` column to a junction table with a lookup table called `sample.note_types` (see bottom of this diagram):

![sample schema](https://docs.google.com/drawings/d/e/2PACX-1vQJvDxsCu2AJN1T2NNF_kkBXPSUXzpc32gIcT5UE0-6Mmq_gH7CbjD64S1-DZ9ULJH8vIgJUxJ3vGnQ/pub?w=1839&h=1196)

The lookup table would have the following values:

| note\_id | note\_name |
| :--- | :--- |
| 1 | Imature |
| 2 | Pore Slide Mount |
| 3 | Mutation |
| 4 | Retained In Reference |
| 5 | Damaged |
| 6 | Gender |
| 7 | Unsure |

However, I'm digging deeper and there are hundreds of distinct notes in the current data. Here are just a few examples:

| notes | Occurrences |
| :--- | :--- |
| I | 146852 |
|  | 45306 |
| U | 35481 |
| D | 22434 |
| RawCount:1 | 21703 |
| I,D | 19356 |
| RawCount:2 | 9856 |
| I,U | 8529 |
| RawCount:3 | 6248 |
| RawCount:4 | 4368 |
| RawCount:5 | 3314 |
| RawCount:6 | 2695 |
| RawCount:7 | 2212 |
| EcoAnalystsID | 2167 |
| RawCount:8 | 1848 |
| RawCount:9 | 1544 |
| RawCount:10 | 1365 |
| RawCount:11 | 1199 |
| ,Cohort 1 | 1113 |
| RawCount:12 | 1104 |

```sql
SELECT notes, count(notes) Occurrences FROM BugData GROUP BY notes ORDER BY count(notes) DESC
```

Obviously all the current values in the notes column can't go in a lookup table. Do we really need to disaggregate the notes into a lookup table? If so, perhaps we should keep the discreet values listed at the top and then also keep the notes field as a text field for free form comments by the taxonomists.

Thoughts?

**Comment by David-Fowler** [comment]
There is some data in the notes field currently that is outside the bound of taxonomy notes and was used to house other data. Before our final migration I need to run a few routines to move that data elsewhere. There are processes in place that have not been run (things like mass data / weights etc). The RawCount values as well.

I do believe the standardized notes need to move out into a lookup table. But I do believe a free-form notes field should exist as well (just like currently the STREAM UI allows for both and just concatenates them into the notes field. By pulling the standardized ones out the notes field can just be plain free-form without any special handling.

A final thought, if all processes like masses etc are no longer placed into that field is a free-form notes field necessary? Or should be just put some thought into additional standardized note values... are free-form notes at this level valuable? - I lean toward not really.

**Comment by Feldspar5** [comment]
The taxonomists do not need notes other than the standardized values listed.  And the masses etc. are just there in limbo, so not needed in the future.  On the other hand, is it poor practice to simply include a notes field should something arise that needs comment?

**Comment by David-Fowler** [comment]
One more comment on the standardized notes which I have never been key on is that the notes are place at the record level (sample, taxa, lifestage, measurement, # of individuals) and are not separated out based on the count which the note actually applies to. Say there is a taxa at the adult level where 200 of them have been found (split count 200). If 10 are found to be damaged the note "D" is applied to all 200 not just 10 of them. Historically this is how it has always been done even pre-STREAM but really there is a loss of info. When the notes are applied it would be better to be able to assign them to a specific sub-count of the total (the junction table between bugdata and taxa notes would allow for this by simply adding a subcount field. On the UI side the only change would be to provide separate counters next to each selected note. This may require a little rework to the current ID flow if we do implement this so I am just bringing it up as a current source of data obfuscation which has a fix if we want it.

**Comment by Feldspar5** [comment]
Good call.

Notes from the taxonomists are directed towards a single individual and should be at that level always.  The non-standardized field should be general to the sample.
