### ISSUE TITLE
SampleType

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#32]
@David-Fowler I am trying associated samples in PilotDB with a sample type (Benthic, Plankton etc). What's the most reliable way to do this please?

The table `PilotDB.BugSample` does not have a `SampleType` column. I see that the front end table `BugLab.BugSample` does have the column `SampleType`, but I can't find any records that are in both tables to support a join. (Presumably the data are removed from BugLab.BugSample when the data are moved to the back end.)

**Comment by David-Fowler** [comment]
So, while the frontend and backend databases both have SampleID as the primary key of bugsample when samples are moved from the frontend to the backend they receive a new sampleID. In no way should joins based on sampleid be made between the 2 DBs. Both front and backend databases do share the same boxid for samples though so in most cases a join can be made using boxid, reachid, sampDate, sortDate; this should match most samples of the past 10 years. There are some discrepancies between the 2 DB's though of which the Backend database would take precedence. 

For all other samples not on the frontend which need a sampletype a simple exists join between the bugplankton, bugdrift, bugstomachs will provide the proper sample types (Zooplankton, Drift, Fish Diet respectively); those only in BugSample and not in any adjoining tables are Benthic.

**Comment by philipbaileynar** [comment]
Thanks @David-Fowler I will use the following query:

```sql
SELECT S.SampleID,
       Count(BP.SampleID) CountBugPlankton,
       Count(BD.SampleID) CountBugDrift,
       Count(BS.SampleID) CountBugStomachs
FROM BugSample S
         LEFT JOIN BugPlankton BP on S.SampleID = BP.SampleID
         LEFT JOIN BugDrift BD ON S.SampleID = BD.SampleID
         LEFT JOIN BugStomachs BS on S.SampleID = BS.SampleID
GROUP BY S.SampleID
```

**Comment by David-Fowler** [comment]
That will work. The counts will either be 0 or 1 which will be perfect for existence. They are one-to-one relationships.
