### ISSUE TITLE
BugSample.Mesh Valid Values

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#33]
There are 3,505 values in `PilotDB.BugSample` with a `Mesh` value of zero. I just want to confirm that zero is a valid number? Seems to me, the uninformed, that a Mesh might always have a non-zero size. If there are records that "didn't use" a mesh, or mesh is not relevant, then it makes more sense to set mesh to NULL for these records. Any insight appreciated.

| Mesh | Occurrences|
| :--- | :--- |
| NULL | 0 |
| 0 | 3505 |
| 5 | 1 |
| 30 | 24 |
| 53 | 44 |
| 56 | 3 |
| 63 | 5 |
| 64 | 16 |
| 80 | 199 |
| 100 | 33 |
| 120 | 1 |
| 150 | 2 |
| 153 | 178 |
| 180 | 88 |
| 200 | 10 |
| 243 | 41 |
| 250 | 6848 |
| 256 | 127 |
| 280 | 2179 |
| 300 | 559 |
| 330 | 195 |
| 333 | 108 |
| 350 | 104 |
| 353 | 6 |
| 363 | 527 |
| 373 | 1 |
| 400 | 1 |
| 425 | 33 |
| 480 | 1 |
| 500 | 27821 |
| 504 | 58 |
| 508 | 70 |
| 550 | 23 |
| 578 | 192 |
| 590 | 4 |
| 600 | 68 |
| 650 | 23 |
| 800 | 155 |
| 900 | 58 |
| 1000 | 636 |
| 3000 | 24 |
| 3125 | 19 |

```sql
SELECT Mesh, Count(Mesh) FROM BugSample GROUP BY Mesh ORDER BY Mesh
```

**Comment by Feldspar5** [comment]
Mesh in the field is always a non-zero value; apparently not so in the database.  Looks like this field is not one we have required in the past.  I need to think about that.  But for the below zeros, yes they should all be changed to NULL.

Some of those other small values seem totally off too, but no way to second guess them at this point.

Trip

**Comment by David-Fowler** [comment]
The reason 0 was used instead of NULL was an issue with some dated computational code which was not readily editable but handled 0 properly. 

I believe it is safe to convert them to NULL's now.
