### ISSUE TITLE
Valid net velocity in BugDrift

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#36]
The net velocity values in `PilotDB.BugDrift` are similar at around 0-2 (presumably ms-1?) except one record that has a NetVelo value of 98. Keep or discard?

| BoxId | CustId | SampleID | SampDate | SampleID | Diameter | NetTime | StreamDepth | NetDepth | NetVelo | Notes |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1271 | OSU-Wooster | 141427 | 2006-07-22 00:00:00.000 | 141427 | NULL | 1 | 0.3125 | 0.3125 | 98 | NULL |

```sql
SELECT B.BoxId, B.CustId, S.SampleID, S.SampDate, D.*
FROM BoxTracking B
         INNER JOIN BugSample S ON B.BoxId = S.BoxID
         INNER JOIN BugDrift D ON S.SampleID = D.SampleID
WHERE NetVelo > 50
```

Also, is zero valid value in the NetVelo column? There are a handful of records with zero net velocity:

| BoxId | CustId | SampleID | SampDate | SampleID | Diameter | NetTime | StreamDepth | NetDepth | NetVelo | Notes |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1904 | BLM-CO-520 | 167434 | 2017-08-09 00:00:00.000 | 167434 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1904 | BLM-CO-520 | 167442 | 2017-08-01 00:00:00.000 | 167442 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1904 | BLM-CO-520 | 167451 | 2017-08-01 00:00:00.000 | 167451 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1904 | BLM-CO-520 | 167460 | 2017-08-09 00:00:00.000 | 167460 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1904 | BLM-CO-520 | 167469 | 2017-08-03 00:00:00.000 | 167469 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1904 | BLM-CO-520 | 167478 | 2017-08-24 00:00:00.000 | 167478 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1904 | BLM-CO-520 | 167487 | 2017-08-24 00:00:00.000 | 167487 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1904 | BLM-CO-520 | 167495 | 2017-07-25 00:00:00.000 | 167495 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1904 | BLM-CO-520 | 167504 | 2017-08-03 00:00:00.000 | 167504 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1904 | BLM-CO-520 | 167513 | 2017-08-02 00:00:00.000 | 167513 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170616 | 2016-05-04 00:00:00.000 | 170616 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170624 | 2016-04-27 00:00:00.000 | 170624 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170633 | 2016-08-02 00:00:00.000 | 170633 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170651 | 2016-08-08 00:00:00.000 | 170651 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170669 | 2016-08-09 00:00:00.000 | 170669 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170678 | 2016-07-27 00:00:00.000 | 170678 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170687 | 2016-08-03 00:00:00.000 | 170687 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170696 | 2016-08-09 00:00:00.000 | 170696 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170705 | 2016-08-09 00:00:00.000 | 170705 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170713 | 2016-04-26 00:00:00.000 | 170713 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170722 | 2016-05-03 00:00:00.000 | 170722 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170730 | 2016-05-04 00:00:00.000 | 170730 | NULL | 0.0833 | NULL | NULL | 0 | NULL |
| 1905 | BLM-CO-520 | 170738 | 2016-04-28 00:00:00.000 | 170738 | NULL | 0.0833 | NULL | NULL | 0 | NULL |

```sql
SELECT B.BoxId, B.CustId, S.SampleID, S.SampDate, D.*
FROM BoxTracking B
         INNER JOIN BugSample S ON B.BoxId = S.BoxID
         INNER JOIN BugDrift D ON S.SampleID = D.SampleID
WHERE NetVelo =0
```

**Comment by courtwrightj01** [comment]
likely this is a decimal place issue. maybe check that this is not a large river but if not change to 0.98

**Comment by Feldspar5** [comment]
Unless someone sampled a fire hose, but even that could not achieve 98 m/s.  Delete

**Comment by David-Fowler** [comment]
Jennifer is right. If other samples of the same box are looked at it is clear that it is a decimal entry issue and should be 0.98 m/s

**Comment by philipbaileynar** [comment]
Here are all the velocities from that same box. Looks Like @courtwrightj01 was right. I will reassign it to 0.98m/s.

| BoxId | NetVelo |
| :--- | :--- |
| 1271 | 0.46 |
| 1271 | 0.34 |
| 1271 | 0.66 |
| 1271 | 0.73 |
| 1271 | 0.3 |
| 1271 | 0.62 |
| 1271 | 0.65 |
| 1271 | 0.62 |
| 1271 | 0.84 |
| 1271 | 0.3 |
| 1271 | 0.7 |
| 1271 | 0.95 |
| 1271 | 0.99 |
| 1271 | 0.87 |
| 1271 | 0.77 |
| 1271 | 0.68 |
| 1271 | 1.02 |
| 1271 | 0.37 |
| 1271 | 1.04 |
| 1271 | 0.66 |
| 1271 | 0.62 |
| 1271 | 0.45 |
| 1271 | 1.04 |
| 1271 | 0.37 |
| 1271 | 0.49 |
| 1271 | 0.92 |
| 1271 | 0.78 |
| 1271 | 0.65 |
| 1271 | 0.53 |
| 1271 | 0.51 |
| 1271 | 98 |
| 1271 | 0.55 |
| 1271 | 0.45 |
| 1271 | 0.8 |
| 1271 | 0.61 |
| 1271 | 0.54 |
| 1271 | 0.28 |
| 1271 | 0.86 |
| 1271 | 0.46 |
| 1271 | 0.93 |
| 1271 | 0.47 |

```sqlSELECT S.BoxId, BD.NetVelo FROM BugSample S INNER JOIN BugDrift BD on S.SampleID = BD.SampleID WHERE BoxID = 1271
```
