### ISSUE TITLE
Plankton with zero diameter

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#37]
There is one record in `PilotDB.BugPlankton` with zero diameter. Is this valid?

| BoxId | CustId | SampleID | SampDate | SampleID | Diameter | SubSampleCount | TowLength | Volume | AllQuot | SizeInterval | TowType | Notes |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 750 | USFS\_R4\_461 | 119997 | 2001-08-08 00:00:00.000 | 119997 | 0 | 5 | 36.6 | 100 | 5 | NULL | Vertical | NULL |

```sql
SELECT BT.BoxId, CustId, BS.SampleID, BS.SampDate, BP.*
FROM BoxTracking BT INNER JOIN BugSample BS on BT.BoxId = BS.BoxID
INNER JOIN BugPlankton BP on BS.SampleID = BP.SampleID
WHERE BP.Diameter = 0
```

And here's a list of all the diameters...

| Diameter | Occurrences |
| :--- | :--- |
| 0.3048 | 182 |
| 0.13 | 136 |
| 0.12 | 129 |
| 0.5 | 76 |
| 0.25 | 54 |
| 0.07 | 54 |
| 0.3 | 54 |
| 0.203 | 40 |
| 0.127 | 34 |
| 0.202 | 13 |
| 0.2029999941587448 | 11 |
| 0.1014999970793724 | 8 |
| 0.1016 | 3 |
| 0.1015 | 3 |
| 5 | 2 |
| 0.0348 | 1 |
| 1 | 1 |
| 0.15 | 1 |
| 0 | 1 |
| 0.20000000298023224 | 1 |
| NULL | 0 |

```sql
SELECT Diameter, count(Diameter) Occurrences FROM BugPlankton GROUP BY Diameter ORDER BY Count(Diameter) DESC
```

**Comment by Feldspar5** [comment]
No

**Comment by David-Fowler** [comment]
This was again a case of assigning a default value which would allow the math to work out and give a proper value without having to filter for NULL values first. Legacy code which I believe again is no longer an issue.

**Comment by philipbaileynar** [comment]
Thank you both. I will assign Diameters of zero to NULL and put a constraint on the table that all Diameters must be greater than zero going forward.
