### ISSUE TITLE
Duplicate Employees

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#40]
There are two employees that appear twice in `PilotDB.Employee`:

| FirstName | LastName | Occurrences |
| :--- | :--- | :--- |
| Beth | Carlson | 2 |
| Carlos | Frias | 2 |

```sql
SELECT FirstName, LastName, Count(EmployeeID) Occurrences FROM Employee GROUP BY FirstName, LastName HAVING Count(EmployeeID) > 1
```

Unless someone objects, I will merge these into one "individual" for Beth and one for Carlos.  Any associated records (e.g. samples that they sorted via `PilotDB.BugSample.SorterID`) will get associated with the new individuals.

**Comment by Feldspar5** [comment]
Agreed
