### ISSUE TITLE
Missing Taxa

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#41]
@David-Fowler thank you for the taxa and attribute data you provided yesterday.

There are 153 attributes in `taxa.attributes` that refer to taxa that do not exist in `taxa.taxonomy`. Here's the query to identify them and the records below that:

```sql
SELECT a.code, t.code
FROM taxa.attributes a
         LEFT JOIN taxa.taxonomy t ON a.code = t.code
WHERE t.code IS NULL
GROUP BY a.code, t.code
```

| taxa.attributes.code | taxa.taxonomy.code |
| :--- | :--- |
| 230 | NULL |
| 842 | NULL |
| 844 | NULL |
| 931 | NULL |
| 1005 | NULL |
| 1059 | NULL |
| 1092 | NULL |
| 1100 | NULL |
| 1116 | NULL |
| 1120 | NULL |
| 1121 | NULL |
| 1124 | NULL |
| 1125 | NULL |
| 1126 | NULL |
| 1133 | NULL |
| 1138 | NULL |
| 1139 | NULL |
| 1145 | NULL |
| 1146 | NULL |
| 1618 | NULL |
| 1640 | NULL |
| 1700 | NULL |
| 1747 | NULL |
| 1822 | NULL |
| 1948 | NULL |
| 1954 | NULL |
| 2032 | NULL |
| 2224 | NULL |
| 2251 | NULL |
| 2260 | NULL |
| 2305 | NULL |
| 2370 | NULL |
| 2378 | NULL |
| 2404 | NULL |
| 2406 | NULL |
| 2409 | NULL |
| 2410 | NULL |
| 2411 | NULL |
| 2412 | NULL |
| 2413 | NULL |
| 2421 | NULL |
| 2429 | NULL |
| 2431 | NULL |
| 2434 | NULL |
| 2442 | NULL |
| 2443 | NULL |
| 2466 | NULL |
| 2476 | NULL |
| 2477 | NULL |
| 2479 | NULL |
| 2483 | NULL |
| 2484 | NULL |
| 2485 | NULL |
| 2486 | NULL |
| 2487 | NULL |
| 2492 | NULL |
| 2493 | NULL |
| 2495 | NULL |
| 2496 | NULL |
| 2499 | NULL |
| 2534 | NULL |
| 2542 | NULL |
| 2551 | NULL |
| 2552 | NULL |
| 2553 | NULL |
| 2554 | NULL |
| 2555 | NULL |
| 2556 | NULL |
| 2557 | NULL |
| 2558 | NULL |
| 2559 | NULL |
| 2560 | NULL |
| 2561 | NULL |
| 2562 | NULL |
| 2563 | NULL |
| 2564 | NULL |
| 2565 | NULL |
| 2566 | NULL |
| 2567 | NULL |
| 2568 | NULL |
| 2571 | NULL |
| 2572 | NULL |
| 2573 | NULL |
| 2584 | NULL |
| 2585 | NULL |
| 2587 | NULL |
| 2604 | NULL |
| 2619 | NULL |
| 2620 | NULL |
| 2629 | NULL |
| 2630 | NULL |
| 2638 | NULL |
| 2640 | NULL |
| 2647 | NULL |
| 2648 | NULL |
| 2657 | NULL |
| 2662 | NULL |
| 2663 | NULL |
| 2664 | NULL |
| 2665 | NULL |
| 2666 | NULL |
| 2669 | NULL |
| 2677 | NULL |
| 2678 | NULL |
| 2684 | NULL |
| 2685 | NULL |
| 2686 | NULL |
| 2687 | NULL |
| 2688 | NULL |
| 2689 | NULL |
| 2691 | NULL |
| 2692 | NULL |
| 2693 | NULL |
| 2697 | NULL |
| 2698 | NULL |
| 2713 | NULL |
| 2714 | NULL |
| 2724 | NULL |
| 2727 | NULL |
| 2730 | NULL |
| 2733 | NULL |
| 2739 | NULL |
| 2740 | NULL |
| 2741 | NULL |
| 2742 | NULL |
| 2743 | NULL |
| 2744 | NULL |
| 2748 | NULL |
| 2749 | NULL |
| 2750 | NULL |
| 2756 | NULL |
| 2757 | NULL |
| 2770 | NULL |
| 2783 | NULL |
| 2784 | NULL |
| 2785 | NULL |
| 2786 | NULL |
| 2787 | NULL |
| 2799 | NULL |
| 2800 | NULL |
| 2816 | NULL |
| 2844 | NULL |
| 2847 | NULL |
| 2920 | NULL |
| 3014 | NULL |
| 3799 | NULL |
| 3834 | NULL |
| 3837 | NULL |
| 3856 | NULL |
| 4008 | NULL |
| 4070 | NULL |
| 4071 | NULL |
| 5744 | NULL |

**Comment by David-Fowler** [comment]
I will get those fixed this evening. I have a few more updates to the tables past yesterday as well so I will place another update like yesterday in box. If my cross archive queries come up with nothing then the records will just be deleted.

**Comment by philipbaileynar** [comment]
Closing this issue because it is out of date and it doesn't reflect the latest strategy for how we are getting the latest taxonomic hierarchy into the new system.
