### ISSUE TITLE
BugData Notes Clarification

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#43]
@David-Fowler can you confirm our strategy for BugData Notes please:

1. Store all official Notes (shown below) in junction table (`sample.organism_notes`).
2. Store all remaining *ad hoc* notes in the notes column of `sample.organism` (the replacement table for `PilotDB.BugData`)

Official note types:

| note\_name | abbreviation |
| :--- | :--- |
| Imature | I |
| Pore Slide Mount | M |
| Mutation | T |
| Retained In Reference | R |
| Damaged | D |
| Gender | G |
| Unsure | U |

**Comment by David-Fowler** [comment]
Minus the spelling. But yes, those are correct.

Immature
Pour
