### ISSUE TITLE
BugData BugSize = Zero

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#45]
There are 843,942 records in `PilotDB.BugData` where the BugSize is zero. Is this valid? Does it mean something? Should they be set to NULL?

Here are 10 example records:

| SampleID | Code | RowIndex | LifeStage | BugSize | SplitCount | BigRareCount | Notes | Valid |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 147693 | 745 | 22 | A | 0 | 195 | 0 | NULL | NULL |
| 147693 | 760 | 28 | A | 0 | 51 | 0 | NULL | NULL |
| 147694 | 182 | 18 | L | 0 | 170 | 0 | NULL | NULL |
| 147694 | 184 | 30 | L | 0 | 208 | 0 | NULL | NULL |
| 147694 | 187 | 32 | L | 0 | 84 | 0 | NULL | NULL |
| 147694 | 314 | 45 | A | 0 | 85 | 0 | NULL | NULL |
| 147695 | 745 | 15 | A | 0 | 262 | 0 | NULL | NULL |
| 147695 | 760 | 18 | A | 0 | 14 | 0 | NULL | NULL |
| 147696 | 180 | 3 | P | 0 | 0 | 1 | NULL | NULL |
| 147696 | 182 | 11 | L | 0 | 4 | 0 | NULL | NULL |

```sql
SELECT Top 10 * FROM BugData WHERE BugSize <=0
```

**Comment by David-Fowler** [comment]
These all had to do with historic procedure. If bugsize is 0 they can be changed to null. 0 was more handled like a default value in the past (meaning it was not measured) and allowed the math to work out with a meaningful value without have to have case statements / filters in procedures.

**Comment by Feldspar5** [comment]
All should be set to NULL, not 0.  Some of them are tiny, but not nano-tiny nor able to violate physical laws.

**Comment by philipbaileynar** [comment]
I was concerned that setting these bug_size values to NULL would confict with the unique index of:

* sample_id
* taxonomy_id
* life_stage_id
* bug_size

but it looks like we are OK:

```sql

SELECT sample_id, taxonomy_id, life_stage_id, CASE WHEN bug_size <= 0 THEN NULL ELSE bug_size END as bug_size
FROM sample.organisms
group by sample_id, taxonomy_id, life_stage_id, bug_size
having count(*) > 1;
```
