### ISSUE TITLE
SiteInfo Mismatched Ecosystems

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#46]
As mentioned in #23 the `PilotDB.SiteInfo` table has three columns `System1`, `System2` and `System3`. Ignoring the last one, `System1` appears to match up to "Ecosystem" and `System2` appears to match up to the records in `TypeSystem` (Lake, Wetland etc). But the records in `TypeSystem` already refer to an ecosystem and the ecosystems referred to in `TypeSystem` don't always match what's in `SiteInfo.System1`. 

Here are the mismatches; These are the sites for which the SiteInfo.System1 does not match the `TypeSystem.Ecosystem` when joining using `SiteInfo.System2 = TypeSystem.SystemType` (see SQL below).

I know @courtwrightj01  wants to do a thorough review of the site classification columns, but I am raising it so we have a record.

| Station | SiteInfo.System1 | SiteInfo.System2 | TypeSystem.System | TypeSystem.EcoSystem |
| :--- | :--- | :--- | :--- | :--- |
| BIBE086 | Lotic | Spring \(Static\) | Spring \(static\) | Lentic |
| CAVE022 | Lotic | Spring \(Static\) | Spring \(static\) | Lentic |
| K113F | Lotic | Wetland | Wetland | Lentic |
| K113UF | Lotic | Wetland | Wetland | Lentic |
| K203UF | Lotic | Wetland | Wetland | Lentic |
| K209F | Lotic | Wetland | Wetland | Lentic |
| K214F | Lotic | Wetland | Wetland | Lentic |
| K214-UF | Lotic | Wetland | Wetland | Lentic |
| L9312F | Lotic | Wetland | Wetland | Lentic |
| L9312UF | Lotic | Wetland | Wetland | Lentic |
| LEADBLM-01 | Lotic | Wetland | Wetland | Lentic |
| SP-013-3 | Lentic | Stream | Stream | Lotic |

```sql
SELECT Station, System1 'SiteInfo.System1', System2 'SiteInfo.System2', T.SystemType 'TypeSystem.System', T.Ecosystem 'TypeSystem.EcoSystem' from SiteInfo S INNER JOIN TypeSystems T ON S.System2 = T.SystemType WHERE S.System1 <> T.Ecosystem;
```

**Comment by David-Fowler** [comment]
When the type ecosystem and typesystem tables were standardized (this happened just before STREAM was brought online) it was decided that even if they were not perfect that everything could fit within them. I would take the values of ecosystem (lotic, lentic) from the typesystem table (and then we can always follow up with a spatial layer for QA as I believe @courtwrightj01 would like to do). Most likely these were sites added prior to STREAM and we never completed a full db cleanup.

@Feldspar5 or @courtwrightj01 please override me if you feel differently.

**Comment by David-Fowler** [comment]
Another aside to these tables. Originally the typesystem table had spring listed twice thereby making it necessary to still keep system1 and system2 in siteinfo. We later appended (static) and (flowing) to the 2 spring listing thereby making the lotic, lentic listing in siteinfo redundant. Currently, after @philipbaileynar adjust the ecosystem to match that of typesystem the only field needed in the new site table is  the data listed in system2 from siteinfo.

**Comment by Feldspar5** [comment]
﻿Thanks for the reminder

**Comment by philipbaileynar** [comment]
For now I have migrated System2 from the siteinfo table. Each system relates to exactly one ecosystem. 

After the new system goes live, it is probably worth NAMC doing a formal review of these systems to ensure they are correct.

**Comment by Feldspar5** [comment]
Thanks Phillip; we will.
