### ISSUE TITLE
Dead boxes

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#49]
Submitted via email by @Feldspar5 on 5th Jan

There are a number of orphaned/dead boxes in Stream that are irksome.  These are created sometimes when a customer makes a submission and then backtracks on some aspect, which then forces us to move to a new box.  Box 2126 is an example of this.  They tend to cause minor headaches in two areas:

1. In Stream they appear as unfinished work
2. When I run queries they can impact certain NAMC-general calcs like mean processing time, or number of samples completed in a year etc.

I have no issues with re-purposing an integer ID for a box rather than letting it remain empty.  Or perhaps there are other ways to deal with this issue.  I thought I would bring this up now in case the topic has not arisen between the two of you.

**Comment by philipbaileynar** [comment]
First, I propose keeping the data. It avoids the mystery of dis-continuous BoxIDs. Leaves an audit trail etc. I think the solution involves two strategies:

1. Do we need a new Box Status for "Aborted" (or some other term)?
2. Staff will be using views to access data for analysis. We can explicitly exclude these aborted boxes (and all their associated data) from these views. We will probably end up with several views for various purposes (i.e. one for the web map that excludes "private projects", one for scientists, one for billing etc etc). Each view will identify just the records that they need for the specific purpose. They will be well documented so you know what you're getting.

Thoughts @David-Fowler ?

**Comment by Feldspar5** [comment]
What you have outlined works for me; as long as there are clear delineations separating the aborted boxes.

**Comment by David-Fowler** [comment]
One of the original benefits / design reasons for having the separate databases was to separate the nature of data being processed and completed data. This allowed for long term stats to be computed against the completed data without being affected by the complications of data processing. Of course the lines got blurred once we started performing edits on the backend database but poor stat calculations are most likely a result of using fields that should never have been in our tables to begin with (like number of samples in boxtracking - stats should have always used a count function across the joined bugsample table to always get the true number of samples and their corresponding processed state).

I brought up the above for two reasons:

1. It demonstrates a necessity for having a merged databases (which is why we are where we are).
2. It shows the need for organizing our queries to use consistent filtering mechanisms. The addition of multiple views as @philipbaileynar mentioned will help make sure fields like "number of samples in a box" and "number of processed samples in a box" are consistent and understood. Most future queries should hopefully be straight select statements for predefined views.

With the merged database yes a 5th box status would help solve this filtering necessity as well. We currently have: pending, waiting, scheduled, active and complete. We never seem to use scheduled (as it was meant to be part of the auto-scheduling algorithm we never activated).  If scheduled goes away it can be replaced with aborted. Before scheduled was called scheduled it was called onhold and was meant to be a placeholder for boxes with an unknown future.

I agree that the audit trail is nice to maintain and can help when a customer comes back and we can clearly see what has happened in the past leading up to the current conversation. With the proper views in place we can have both valid stats and history tracking.

**Comment by philipbaileynar** [comment]
@Feldspar5 are there a finite number of boxes that should have this "aborted" status? Can you respond with the box IDs. (I'm assuming there's only a handful. If there are many of them then we can discuss other means to convey them.)

**Comment by Feldspar5** [comment]
﻿There is a finite number; I can get back to you with a list.

**Comment by David-Fowler** [comment]
The PilotDB database would only have the boxtracking record filled out and no sorterid, taxaid for the corresponding samples on the BugLab frontend database; the frontend DB would also have a "waiting" box status. This alone is not enough of a filter though as it encapsulates all waiting boxes. A further filter of box DateIn + 6 months should get us all but those occurring in the last 6 months. @Feldspar5 do you think a 6 month filter of boxes with no sorter or id data is enough?

**Comment by Feldspar5** [comment]
6 weeks ago I would have soda no, but the 2019 AIM backlog has been cleared so 6 months should be fine except for some boxes like:

Logan Rover long term – that box(es) is forever open and never processed
Some gut samples from the Green
Some abandoned boxes from the BLM in Taos, NM: we like to hide these in lab and ignore them.

My point is, I cannot think of a definitive means to ID all and only the dead sets.  Feels like we need to cast a broad net and then I need to review?

Trip

**Comment by philipbaileynar** [comment]
There are 5 records in the front end **snapshot** that I have, with NULL sorter and ider with a waiting status:

| BoxId | CustId | DateIn |
| :--- | :--- | :--- |
| 1270 | USU-BUGLAB | 2012-04-26 00:00:00.000 |
| 1472 | USFS\_R1\_279 | 2012-04-11 00:00:00.000 |
| 1476 | USFS\_R6\_372 | 2012-04-23 00:00:00.000 |
| 1481 | OSU-WOOSTER | 2012-05-08 00:00:00.000 |
| 1482 | USFS\_R5\_F10 | 2012-05-16 00:00:00.000 |

```sql
SELECT B.BoxId, B.CustId, B.DateIn
FROM BugLab.dbo.BugBoxes B
         INNER JOIN BugLab.dbo.BugSample S ON B.BoxId = S.BoxID
WHERE (S.SorterID IS NULL)
  AND (S.IderID IS NULL)
  AND B.Waiting = 1
GROUP BY B.BoxID, B.CustId, B.DateIn
```

The back end looks more problematic because lots of old boxes have NULL sorter and ider:

| BoxId | CustId | DateIn |
| :--- | :--- | :--- |
| 1 | BLM-OR-010 | 1993-01-10 00:00:00.000 |
| 2 | BLM-OR-010 | 1993-02-04 00:00:00.000 |
| 3 | BLM-CO-150 | 1993-02-04 00:00:00.000 |
| 4 | BLM-OR-120 | 1993-02-15 00:00:00.000 |
| 5 | BLM-CO-150 | 1993-03-01 00:00:00.000 |
| 6 | BLM-OR-130 | 1993-05-07 00:00:00.000 |
| 7 | AK-NDO | 1993-06-01 00:00:00.000 |
| 8 | BLM-CO-140 | 1993-06-15 00:00:00.000 |
| 9 | BLM-CO-200 | 1993-07-01 00:00:00.000 |
| 10 | BLM-UT-080 | 1993-07-01 00:00:00.000 |
| 11 | BLM-OR-122 | 1993-07-07 00:00:00.000 |
| 12 | USFS\_R5\_F11 | 1993-07-26 00:00:00.000 |
| 13 | BLM-OR-060 | 1993-09-01 00:00:00.000 |
| 14 | BLM-AZ-310 | 1993-09-01 00:00:00.000 |
| 15 | R09F21A | 1993-09-23 00:00:00.000 |
| 16 | BLM-OR-122 | 1993-09-26 00:00:00.000 |
| 17 | USFS\_R5\_F13 | 1993-10-01 00:00:00.000 |
| 18 | BLM-AZ-200 | 1993-10-01 00:00:00.000 |
| 19 | BLM-UT-050 | 1993-10-01 00:00:00.000 |
| 35 | USFS\_R4\_458 | 1994-02-01 00:00:00.000 |
| 36 | BLM-OR-040 | 1994-02-07 00:00:00.000 |
| 37 | BLM-OR-060 | 1994-02-07 00:00:00.000 |
| 38 | BLM-OR-120 | 1994-02-07 00:00:00.000 |
| 39 | BLM-OR-110 | 1994-02-07 00:00:00.000 |
| 44 | BLM-CO-160 | 1994-02-22 00:00:00.000 |
| 57 | USFS\_R6\_345 | 1994-06-10 00:00:00.000 |
| 62 | BLM-OR-130 | 1994-07-08 00:00:00.000 |
| 112 | BLM-AZ-330 | 1995-03-07 00:00:00.000 |
| 113 | USFS\_R5\_F13 | 1995-03-14 00:00:00.000 |
| 165 | BLM-AZ-330 | 1996-01-17 00:00:00.000 |
| 254 | USFS\_R3\_F2 | NULL |
| 259 | USU-Buglab | NULL |
| 270 | USFS\_R4\_317 | 1997-10-01 00:00:00.000 |
| 286 | USU-Hawkins | NULL |
| 321 | USU-Hawkins | NULL |
| 324 | NPS-MOJN-GRBA | 1998-07-27 00:00:00.000 |
| 328 | USFS\_R5\_F10\_D52 | 1998-08-08 00:00:00.000 |
| 345 | USFS\_R6\_425 | 1998-09-25 00:00:00.000 |
| 350 | USFS\_R1\_278 | 1998-10-07 00:00:00.000 |
| 362 | USFS\_R4\_337 | 1998-11-17 00:00:00.000 |
| 382 | USFS\_501 | 1999-03-12 00:00:00.000 |
| 392 | TRIBE-UMT | 1999-05-17 00:00:00.000 |
| 398 | UT-DWR-01 | 1999-04-14 00:00:00.000 |
| 460 | BLM-UT-030 | 2000-01-07 00:00:00.000 |
| 489 | USFS\_502 | 2000-09-14 00:00:00.000 |
| 501 | USU-Hawkins | 2000-09-12 00:00:00.000 |
| 504 | USU-Hawkins | NULL |
| 505 | USU-Hawkins | NULL |
| 553 | USU-Hawkins | NULL |
| 571 | USFS\_R4\_461 | 2001-03-21 00:00:00.000 |
| 624 | UT-DWR-01 | 2001-09-20 00:00:00.000 |
| 638 | NPS-MOJN-GRBA | 2001-11-13 00:00:00.000 |
| 639 | NPS-MOJN-GRBA | 2001-11-13 00:00:00.000 |
| 652 | USU-Hawkins | 2001-08-30 00:00:00.000 |
| 705 | USFS\_502 | 2002-09-24 00:00:00.000 |
| 762 | DEQ-01 | 2003-05-08 00:00:00.000 |
| 843 | UT-DWR-03 | 2004-05-12 00:00:00.000 |
| 912 | USFS\_505 | 2005-01-12 00:00:00.000 |
| 952 | NPS-NCPN-DINO | NULL |
| 955 | USFS\_R6\_348 | 2005-08-09 00:00:00.000 |
| 957 | USU-Hawkins | NULL |
| 1053 | USFS-LTBMU | 2006-09-22 00:00:00.000 |
| 1148 | USU-Buglab | 2007-07-25 00:00:00.000 |
| 1175 | USU-Hawkins | NULL |
| 1240 | USU-Buglab | 2010-12-14 00:00:00.000 |
| 1244 | USU-Hawkins | NULL |
| 1251 | BLM-OR-050 | 2009-05-01 00:00:00.000 |
| 1318 | USU-Hawkins | 2010-04-09 00:00:00.000 |
| 1334 | BLM-CO-510 | 2010-07-26 00:00:00.000 |
| 1340 | NPS-NCPN-DINO | 2010-08-19 00:00:00.000 |
| 1344 | DEQ-01 | 2010-08-30 00:00:00.000 |
| 1355 | USU-Hawkins | 2010-10-06 00:00:00.000 |
| 1374 | USU-Buglab | NULL |
| 1413 | NPS-NCPN-DINO | 2011-08-24 00:00:00.000 |
| 1434 | USU-Buglab | NULL |
| 1475 | USU-BUGLAB | 2012-04-20 00:00:00.000 |
| 1480 | NPS-MOJN | 2012-05-07 00:00:00.000 |
| 1492 | USU-BUGLAB | 2012-07-18 00:00:00.000 |
| 1502 | USU-BUGLAB | 2012-08-13 00:00:00.000 |
| 1612 | USU-BUGLAB | 2013-11-14 00:00:00.000 |
| 1654 | USFS\_504 | 2014-07-28 00:00:00.000 |
| 1666 | USFS\_504 | 2014-07-28 00:00:00.000 |
| 1737 | BLM-NM-220 | 2015-08-26 00:00:00.000 |
| 1771 | USU-Hawkins | NULL |
| 1858 | BLM-NM-220 | 2015-09-28 00:00:00.000 |
| 1903 | USU-Hawkins | 2017-08-23 00:00:00.000 |
| 1949 | USU-BUGLAB | 2018-03-09 00:00:00.000 |
| 2004 | EcoA-ID | 2018-11-16 00:00:00.000 |
| 2055 | BLM-AIM | 2020-02-25 00:00:00.000 |
| 2067 | USU-Miller | 2019-09-03 00:00:00.000 |
| 2069 | USU-Miller | 2019-09-09 00:00:00.000 |
| 2081 | USU-Miller | 2019-10-28 00:00:00.000 |
| 2100 | BLM-AIM | 2019-11-26 00:00:00.000 |

```sql
SELECT B.BoxId, B.CustId, B.DateIn
FROM PilotDB.dbo.BoxTracking B
         INNER JOIN PilotDB.dbo.BugSample S ON B.BoxId = S.BoxID
WHERE (S.SorterID IS NULL) AND (S.IderID IS NULL)
GROUP BY B.BoxID, B.CustId, B.DateIn
```

**Comment by Feldspar5** [comment]
David – Why are these queries failing to find the following dead boxes: 2126, 2127, 2128, 2129?  I am confident there are others.

**Comment by David-Fowler** [comment]
@philipbaileynar I would not look at anything on the backend database. If it made it to PilotDB it is valid data.

The query @philipbaileynar is using is not picking up those newer boxes as he is using an older frontend backup. I can push the latest backups up to box and notify @philipbaileynar when I do so. That said I only see 2126 in the database and it was added in October of last year (so was not even making it into the 6 month query I was running)? Am I missing something?

```
select distinct
	bb.boxid
from bugboxes as bb
join bugsample as bs
	on bs.boxid = bb.boxid
where
	bb.DateIn < dateadd(month,-6, getdate()) and
	bb.Waiting = 1 and
	bs.SorterID is null and
	bs.IderID is null
```

**Comment by philipbaileynar** [comment]
Closing this issue because it got long winded. Succinct outstanding task abstracted to #90
