### ISSUE TITLE
Database Metadata

### ISSUE THREAD

**Issue by David-Fowler** [namc-utah/namc-bug-db#50]
I want to add this topic to our discussion of conventions and that is I would like us to store json structured metadata for all database fields, tables, procedures, triggers etc. in the database. In postgreql this would use the "comment on ..." syntax. Much of this I have for the current MSSQL database but never attached it; I know we also have other various documents with additional info we can gather up.

The JSON structure would include something like:
{
  ProperName: "A name including Spaces used for headers in reports etc.",
  Caption: "A short description",
  Description: "An in depth description of uses, science, etc."
}

While there are other ways of storing this data, attaching it right to the source using the database specified method to do so (while extending it with JSON) helps to keep the metadata stored in one place and tightly coupled to what it belongs to (no relations to keep in check). The pivoted tables (storing metrics, predictors etc) would in addition have their own fields for this in the joined tables.

**Comment by philipbaileynar** [comment]
@David-Fowler I like this suggestion and have been thinking about this a lot. Let's discuss it because I think there are pros and cons to using the postgres "comment on".

My preference would be to have a "metadata" schema dedicated to storing the text you are proposing. We can devise a simple, flexible one or two table system within this schema. 

I agree that the information needs to be tightly coupled with the database. Indeed it could even go inside the master[ schema.sql file](https://github.com/namc-utah/namc-bug-db/blob/master/docker/postgres/initdb/01_SCHEMA.sql) as a series of SQL insert statements (instead of "comment on").

Storing the data in tables is more transparent than JSON and let's us have miscellaneous columns that can be used by scripting to generate the system documentation. I have started this, albeit crudely, using markdown files that then build the site using Jekyll (all automated by GitHub).

- Here's the [markdown folder](https://github.com/namc-utah/namc-bug-db/tree/master/docs)
- Here's the [actual site](https://namc-utah.github.io/namc-bug-db/)

I was envisioning a really simple Python script that exports the contents of the metadata tables into markdown files. This would enable us to have hyperlinks, images and other rich content without having to maintain a complex web site.

**Comment by philipbaileynar** [comment]
I have implemented the database data dictionary. My goal is to make this data dictionary simple and easy to maintain. Out-of-date documentation is worthless!

I have added two tables to the bug database that contain the descriptions of the rest of the tables and columns. They also store the "mapping" of how table names from the old databases (PilotDB and front end) to the new system. This should help people when they ask "where did the data go that was in table XXX in PilotDB".

Here's the start of the data dictionary. I will be working on the table and column descriptions over the coming days.

https://namc-utah.github.io/namc-bug-db/database/schema_entity.html

and here's the (in-progress) list of table mappings:

https://namc-utah.github.io/namc-bug-db/database/data_migration.html

All this material is still under development and still very much a work in progress. But I am interested in people's feedback and ways that this should be improved. Particularly @courtwrightj01 who highlighted the importance of the data dictionary.

**Comment by courtwrightj01** [comment]
I think this works well! I think the mapping of before and after table renaming is super important as well. Thanks! A couple questions. How would we edit this info? What is the difference between the blue and white boxes. Are blue ones that are built and white are still in the works? I am assuming units of fields go in the description column?

Jennifer

**Comment by Feldspar5** [comment]
Another question: Bugsaummary and bugsummaryOTU both have an “uncertain”; are there still decisions we need to make for these?

Is there a way you can send me a link for the taxonomy table video so I can share with Chuck?  Maybe you already did this, but it was admittedly between Thanksgiving and New Year’s…

Thanks

Trip

**Comment by philipbaileynar** [comment]
The diagrams are still very much a work in progress. They will be tightened up and more polished when we are finished! This includes adding legends to clearly communicating the meaning of colors etc. The diagrams are Google Drawings published to the web. So your NAMC Google account will own these diagrams so you can easily edit them should things change.

## Editing the information in the Database Table Descriptions

The descriptions in the database table definitions are actually stored and editable in the database itself. I created three tables to store this information. This makes it really easy to maintain the information and ensure it is kept up-to-date. It also means that you can query it and quickly answer questions about the new database design. To find the units of the fish mass for example:

 ```sql
SELECT description FROM meta.columns WHERE column_name = 'mass'
```

<img width="810" alt="Screen Shot 2021-01-11 at 2 36 32 PM" src="https://user-images.githubusercontent.com/8645379/104247253-434efe80-541c-11eb-9731-fdf34a1d71cb.png">


## Documentation Web Site

The web site in which the documentation resides is just text files in the a special folder in GitHub. When you edit the text files, GitHub detects the changes and publishes a new version of the web site. 

I am discussing with @David-Fowler whether we can use this technology (called GitHub Pages) to host your NAMC web site. There are two obvious advantages of this approach:

1. Your web site contents can be maintained by anyone who can edit a text file in GitHub.
2. There are no web servers to maintain. The final web site is a flat HTML site with no sever-side scripting or other technology that can be hacked. Zero maintainance.

**Comment by Feldspar5** [comment]
Phillip –

The NAMC website will be as described below?  Or just a NAMC documentation website?

Thanks

Trip

**Comment by philipbaileynar** [comment]
I am proposing both, but I suspect that I might need to work on convincing @David-Fowler that the NAMC web site can be a GitHub pages.

My motivations are:

1. Reduced IT admin for your NAMC web site.
2. Increased security (flat website with no server to hack)
2. Democratize the content of the web site. Get more staff knowledgable about how to edit content.

**Comment by Feldspar5** [comment]
Aesthetics?

I love all 3 ideas. Particularly #3, but what is the downside?  Why are all websites not run on GitHub?  I get that content can be edited in text, but is the site design baked in at startup?

Trip

**Comment by David-Fowler** [comment]
While markdown has its benefits and places and I do think it can work for the database documentation I do not think we should regard it for our whole website presence nor do I think we should bring the website into this database process. I would focus on just this database / system process.

**Comment by philipbaileynar** [comment]
@MattReimer pointed out that there are dozens of free tools out there for generated database documentation. I just experimented with one such tool called [Schema Spy](http://schemaspy.org/).

So you will recall that I experimented with rudimentary documentation by combining Google Drawings with some markdown:

https://namc-utah.github.io/namc-bug-db/database/schema_sample.html

And here is an experimental run of SchemaSpy on the new bug database. Make sure you click into one or more of the schemas and scroll to the bottom of the page. I really like the professional entity relationship diagrams!

https://namc-utah.github.io/namc-bug-db/bugdb/

Obviously both versions lack the specific comments that will ultimately make the documentation useful. But my question is, do we want something simple and customizable (first attempt) or something more sophisticated and detailed (such as Schema Spy)?

Personally I like the exhaustive detail of something like Schema Spy. Any future developer that wants to work with the database will appreciate this detail. 

(Note that the API will have its own documentation.)

**Comment by David-Fowler** [comment]
Agreed. I like the exhaustive detail of options like Schema Spy as well and the fact that it is one less piece of custom code (giving us update paths into the future).

Also regarding comment storage and Schema Spy specifically:

1. Comments can either be stored using the "comment on" format which used to be the default for this tool. Though as discussed yesterday, JSON will not be very pretty but potentially html or formatted plain text could work.
2. I believe Schema Spy is one of the tools that does let you define a custom comments sql query (meaning a query can be written to pull from the tables you have up already). I think this option is placed into the database properties file you define for the tool. I can check on this in a bit and will post back (I can't remember if it was schema spy or another tool I am thinking of).

**Comment by David-Fowler** [comment]
Looks like the custom query option in schema spy is no longer an option (or at least not documented)... I found reference to it for older versions but did not find it in the current docs.

That said, it does automatically render markdown stored in the database standard comments.

**Comment by courtwrightj01** [comment]
I definitely like the schema spy option better especially because of the relationship diagrams! However, I might need a bit more training in how to navigate around. It wasn’t quite as intuitive. For example, once I clicked on one schema I couldn’t figure out how to go back to the list of all the schemas to click on another one.

Jennifer

**Comment by Feldspar5** [comment]
I also really like the schema spy layout.  Particularly with the relationship diagrams too.  I did not see them at first and was spending time in the other sections, but when I found them, I was sold.  

Although I note that the visual component has been important when working in SQL in current database.  I imagine it will be less so in the new R-API-postrgres flow.

**Comment by philipbaileynar** [comment]
We are going to proceed (for now) with schema spy. Schema Spy has LOTS of configuration options and research is needed to determine the Schema Spy configuration that best suites our needs.

For now... the most obvious task is that we need to add comments to describe every database object!!!!
