### ISSUE TITLE
Deprecated Tables

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#51]
Everyone please review the following page that lists which tables are being deprecated (dropped) when we move to the new system.

Please think hard about what's stored in each of these tables and whether we need it in the new system. Report any concerns on this ticket and I will follow up with you.

https://namc-utah.github.io/namc-bug-db/database/data_migration.html

**Comment by courtwrightj01** [comment]
Quick gut reaction is that this all looks correct but I will try to review in more detail later in the week.
