### ISSUE TITLE
Fiscal Years?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#53]
Does NAMC require reporting at anything other than a calendar year? Do you use fiscal years that are different from calendar years? Academic (sep 1) or federal government (oct 1)?

**Comment by Feldspar5** [comment]
We do not report any data/science at any fixed schedule.  Financials do include a variety of schedules:
Utah FY
Federal FY
Calendar year

And other grants/agreements run on stochastic start dates based on the signatory date.
