### ISSUE TITLE
R demo authenthicating against OAuth 2.0

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#55]
@David-Fowler can you provide a few lines of R code to demonstrate how to authenticate against an API using OAuth 2.0 please? 

I can provide an API endpoint if you need one to experiment with.

**Comment by David-Fowler** [comment]
I will clone an internal git repo to the NAMC github account today or tomorrow. It contains an abstraction around direct database connections / SQL and http OAuth 2.0 / graphql queries (hitting the views being built into the new DB schema will be easy to add to this abstraction layer). Metrics and project management routines are already included and can be further built on as we progress.

**Comment by philipbaileynar** [comment]
Thanks @David-Fowler. We have an API up and running serving JSON through GraphQL.

If you have time today we can perhaps jump on a meeting and work through getting you connected using OAuth?

**Comment by David-Fowler** [comment]
oAuth2 is connected to cognito via R now. I will get the package cloned from our internal git repo to github shortly.

**Comment by philipbaileynar** [comment]
This task is complete!
