### ISSUE TITLE
Predictor values

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#58]
I forgot to ask this earlier today:

What are the possible types of predictor values we need to consider?

|Predictor Types|Examples|
|---|---|
|Integer|stream order of "1"|
|Floating point|mean temperature, max elevation etc|
|Categorical|"agriculture", "wet", "dry"|

Are all predictor values single values, as I've shown above? Or can they be higher dimensionality such as lists, arrays, lookup dictionaries etc?

**Comment by courtwrightj01** [comment]
We have all three kinds of predictors listed below but all predictors are single values. No lists or arrays
