### ISSUE TITLE
MapIT SplitCounts

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#61]
Why does MAPIT report `LabSplit` and `SplitCount` when it could simply do the math to report a projected total count?

Should the new system continue to report these two fields or do the math?

<img width="1369" alt="Screen Shot 2021-02-09 at 9 25 31 AM" src="https://user-images.githubusercontent.com/8645379/107402417-c49bbe80-6ab8-11eb-8465-2e3abfdf5c56.png">

PilotDB Data:

| LabSplit | SampleID | Code | RowIndex | LifeStage | BugSize | SplitCount | BigRareCount | Notes | Valid |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 75 | 147076 | 863 | NULL | P | NULL | 7 | 0 |  | NULL |
| 75 | 147076 | 2807 | NULL | L | NULL | 8 | 0 |  | NULL |
| 75 | 147076 | 2530 | NULL | L | NULL | 74 | 0 |  | NULL |
| 75 | 147076 | 2762 | NULL | L | NULL | 23 | 0 |  | NULL |
| 75 | 147076 | 1294 | NULL | L | NULL | 1 | 0 |  | NULL |
| 75 | 147076 | 1676 | NULL | P | NULL | 1 | 0 |  | NULL |
| 75 | 147076 | 1147 | NULL | L | NULL | 1 | 0 |  | NULL |
| 75 | 147076 | 1683 | NULL | P | NULL | 1 | 0 |  | NULL |
| 75 | 147076 | 824 | NULL | L | NULL | 1 | 0 |  | NULL |
| 75 | 147076 | 1301 | NULL | L | NULL | 7 | 0 |  | NULL |

**Comment by courtwrightj01** [comment]
My gut is that we probably want both just for lab transparency but I will pass this one to Trip

**Comment by Feldspar5** [comment]
Ideally we would provide sampled area, lab split, and split count.  No calcs needed on our end, and total transparency.
