### ISSUE TITLE
Which locations should be shown in MAPIT?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#62]
Customer submitted lat/long or the official site lat/long?

**Comment by courtwrightj01** [comment]
Hmm….I am leaning towards official lat long….what do others think?

**Comment by David-Fowler** [comment]
I would say official for the public facing map UI. If we are providing separate map views for each customer in their "portals" I would lean toward using the lat / long they submitted to us.

**Comment by Feldspar5** [comment]
I think it is critical that we use the official lat lon in the map UI.  Yet I also think we need to provide the submitted as well as official coordinates to the customer.
