### ISSUE TITLE
Are Sample Times Needed in MAPIT?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#63]
Are Sample times really needed in MAPIT? The vast majority of samples do not have times associated with them. I know there are the before and after dam release samples (for Flaming Gorge if I recall).

Do we need to retain these times in the MapIT results?

**Comment by courtwrightj01** [comment]
Likely no, Trip do you agree?

**Comment by Feldspar5** [comment]
There is no reason to maintain sample times in newMapIt.
