### ISSUE TITLE
What is a private sample in the new system?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#64]
MAPIT used to only display samples that were associated with public projects. Samples associated with private projects were not displayed.

In the new system samples can now be associated with multiple projects (#24). So what does is mean for a sample to be private?

Some suggestions:

1. The map excludes samples that are associated with one or more private projects. As soon as a sample is associated with a private project it will never show up in the map.
2. The map excludes samples that are **only** associated with private projects. i.e. a sample can be associated with a public project and a private project and it will still show up in the map.

**Comment by Feldspar5** [comment]
We should have very few private samples.  As a publicly funded lab, we default to sharing data.  As long as NAMC has the ability to toggle a sample as private, then option 1 above makes the most sense.  Most boxes (not necessarily samples) are not part of projects, but simply 'submissions'.

**Comment by David-Fowler** [comment]
Option 1 is best. The geofenced region and/or manually specified sample list of the private projects will contain the private definition. The auto-update functionality of project will make sure future samples captured in the polygon definition get added to the project.

**Comment by philipbaileynar** [comment]
I have implemented option 1. If a sample is part of 1 or more private projects then they are no longer visible on the map (or any other general public views).
