### ISSUE TITLE
Example StreamCAT variables

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#65]
@alherca73 can you please identify 10-20 StreamCAT variables that you foresee being useful in the new system? Please identify them using either their unique name or URL etc. Ideally the ones that you provide would be those that are most important/valuable/relevant. Please put the names/identifiers of the desired variables on this GitHub issue.

I want to confirm how the database will store and deliver StreamCAT variables via the API. Having the list that you provide will help me iron out any kinks in how we intend to obtain and store these values.

Mention @Feldspar5 and @courtwrightj01 for visibility.

**Comment by courtwrightj01** [comment]
I will provide the list momentarily

**Comment by courtwrightj01** [comment]
@Feldspar5<https://github.com/Feldspar5> can you review this list and see if you agree

Highest priorty
WsAreaSqKm
Highest priorty
CatAreaSqKm
Highest priorty
ElevCat
Highest priorty
Precip8110Ws
Highest priorty
Tmean8110Ws
medium
CaOWs
medium
NCat
medium
RunoffWs
medium
SWs
medium
PctSalLakeWs
medium
MAST_2008
medium
MAST_2009
medium
MAST_2013
medium
MAST_2014
medium
MSST_2008
medium
MSST_2009
medium
MSST_2013
medium
MSST_2014
medium
MWST_2008
medium
MWST_2009
medium
MWST_2013
medium
MWST_2014
low
RdCrsCat
low
RdCrsWs
low
RdDensWs
low
DamDensCat
low
CanalDensCat
low
CanalDensWs
low
SuperfundDensWs
low
MineDensWs
low
PctUrbHi2006Ws
low
PctUrbHi2006Cat
low
PctUrbLo2006Ws
low
PctUrbLo2006Cat
low
PctUrbMd2006Ws
low
PctUrbMd2006Cat
low
PctAg2006Slp10Ws
low
PctAg2006Slp20Ws
low
PctAg2006Slp10Cat
low
PctAg2006Slp20Cat
lowest
PctUrbHi2011Ws
lowest
PctUrbHi2011Cat
lowest
PctUrbLo2011Ws
lowest
PctUrbLo2011Cat
lowest
PctUrbMd2011Ws
lowest
PctUrbMd2011Cat

**Comment by Feldspar5** [comment]
We have the modtest values, then the WW values, and after that the Low and Lowest seem like they are for the GIS ref site screening?  I typically do not use those, so just a guess.  But the high and medium lists are correct.  Thanks

**Comment by courtwrightj01** [comment]
Correct
