### ISSUE TITLE
Project Samples

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#66]
@David-Fowler can you confirm that the query below can be used in PilotDB to identify all samples associated with each project. Note how I'm combining data from BoxTracking and Collection. Is this valid?

```sql
SELECT P.ProjectID, Bs.SampleID
FROM Project P
         INNER JOIN BoxTracking B ON P.ProjectID = B.ProjectID
         INNER JOIN BugSample BS on B.BoxId = BS.BoxID
UNION
SELECT ProjectID, SampleID
FROM Collection
```

Note that the new database retains the same IDs for Boxes, Samples and Projects.

**Comment by David-Fowler** [comment]
Yes, this query will work however it may also lead to some projects being assigned multiple projectIDs. While the default projectID used currently is in Collection I think keeping both linked Projects for those that the query does output is fine.

**Comment by philipbaileynar** [comment]
@philipbaileynar make sure to go review private projects through the collections.
