### ISSUE TITLE
API pagination default

### ISSUE THREAD

**Issue by David-Fowler** [namc-utah/namc-bug-db#70]
@philipbaileynar  if you could add a default value to the "limit" argument. Whatever value you think is best (and could be different for different endpoints if you like). I can introspect the default and use it directly to start the pagination. I have a high level default of 100 which I can keep as a backup but if it is passed down in the schema I can use it instead.

**Comment by philipbaileynar** [comment]
Absolutely. I will implement default.

We need to stay under 5Mb per request. Probably safest to aim for 2Mb. I will set default accordingly.

**Comment by philipbaileynar** [comment]
This is now implemented.
