### ISSUE TITLE
Do we have too many Sample notes fields?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#73]
We currently have the following fields to store notes associated with each sample:

* `sample.samples.field_notes`
* `sample.samples.lab_notes`
* `sample.plankton.notes`
* `sample.drift.notes`

(There's also `sample.organisms.notes`, but that's a child table).

Do we need all these notes fields? Can we live with just `field_notes` and `lab_notes` on the samples table and drop those on the 1:1 tables plankton and drift?

**Comment by David-Fowler** [comment]
Yes. I think we can and probably should. I do wonder if storing lab_notes and/or field notes in a JSON structure allowing for named notes would be worth while. I can think of at least of hand full of cases where having the ability to separate our various random notes has been needed. Having the most basic JSON schema holding a single key called "text" (where the traditional human typed / sentence would exist) followed by additional keys on an as needed basis.

We already have a "metadata" sample level field which is JSON so we would need to decide if "true" notes ever need to have separation in which case JSON formatted note fields would make sense.
