### ISSUE TITLE
Which predictors are temporal?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#74]
The following table lists all the predictors that I currently have in the database. It is a mix of those provided by @courtwrightj01  and the list we agreed on from StreamCAT (#65 ).

Can someone please edit this table and flag those predictors that are temporal (have values associated with the date that a sample is collected) as opposed to static predictor values for the site. Here's the table as a CSV file should that be easier to work with:

[predictors.csv.zip](https://github.com/namc-utah/namc-bug-db/files/6031934/predictors.csv.zip)

I'm also looking for the units of some predictors. See `??` below.

| predictor\_id | abbreviation | units | predictor\_type\_name | is\_temporal | description |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 152 | HydrAlt\_km | ?? | Anthro |  | Total length of Hydraulic alteration in the watershed \(pipelines and canals\) |
| 153 | RdDens | ?? | Anthro |  | Road Density in the watershed |
| 46 | AtmCa | ?? | Atmosphere |  | atmospheric calcium at the point |
| 48 | AtmMg | ?? | Atmosphere |  | atmospheric Mg at the point |
| 66 | AtmNa | ?? | Atmosphere |  | atmospheric Na at the point |
| 67 | AtmNO3 | ?? | Atmosphere |  | atmospheric NO3 at the point |
| 47 | AtmSO4 | ?? | Atmosphere |  | atmospheric SO4 at the point |
| 102 | AT | ?? | Climate |  | Average temperature at the point for a given year |
| 129 | daynum | ?? | Climate |  | Day of Year |
| 73 | DOY | ?? | Climate |  | Day of Year |
| 146 | FST32F\_AVE | ?? | Climate |  | Average first freeze day at the watershed |
| 121 | HYDR\_WS | ?? | Climate |  | Mean of Hydr at the watershed |
| 136 | LOG\_LT\_PPT\_PT | ?? | Climate |  | Precip at the point |
| 49 | LST32AVE | ?? | Climate |  | Average last freeze day at the watershed |
| 145 | MAXWD\_AVE | ?? | Climate |  | Mean of max number of wet days at the watershed |
| 54 | MAXWD\_WS | ?? | Climate |  | Mean of max number of wet days at the watershed |
| 143 | MEANP\_AVE | mm | Climate |  | Mean precip at the watershed |
| 51 | MEANP\_WS | ?? | Climate |  | Mean precip at the watershed |
| 55 | MINP\_WS | ?? | Climate |  | Average of minimum precip at the watershed |
| 50 | MINWD\_WS | ?? | Climate |  | Wet Days min at the watershed |
| 122 | Pmax\_PT | ?? | Climate |  | Precip max at the point |
| 123 | Pmax\_WS | ?? | Climate |  | Precip max at the watershed |
| 166 | PMIN\_PT | ?? | Climate |  | Precip min at the point |
| 119 | Pmin\_WS | ?? | Climate |  | Average of minimum precip at the watershed |
| 163 | PMIN\_WS | ?? | Climate |  | Average of minimum precip at the watershed |
| 169 | PMIN\_WS- same as MMI | ?? | Climate |  | Average of minimum precip at the watershed |
| 72 | PPT\_2MoAvg | ?? | Climate |  | Mean of the previous month's precip and the current month's precip |
| 71 | PPT\_ACCUM | ?? | Climate |  | Mean of previous year's precip sum \(May-April\) |
| 116 | PRCPSHORTW | ?? | Climate |  | Calendar year average precip at the watershed |
| 68 | PT\_Tmin | ?? | Climate |  | Minimum temperature at the point |
| 141 | RH\_AVE | ?? | Climate |  | RH mean at the watershed |
| 70 | RH\_WS | ?? | Climate |  | RH mean at the watershed |
| 53 | SumAve\_P | ?? | Climate |  | Summer average precip at the watershed |
| 138 | TMAX\_AVE | ?? | Climate |  | Average of max temperature at the watershed |
| 124 | Tmax\_PT | ?? | Climate |  | Temperature max at the point |
| 135 | TMAX\_PT | ?? | Climate |  | Temperature max at the point |
| 120 | Tmax\_WS | ?? | Climate |  | Average of max temperature at the watershed |
| 56 | TMAX\_WS | ?? | Climate |  | Average of max temperature at the watershed |
| 139 | TMEAN\_AVE | ?? | Climate |  | Average of mean temperature at the watershed |
| 164 | TMEAN\_PT | ?? | Climate |  | Temperature mean at the point |
| 142 | TMEANPT | ?? | Climate |  | Average temperature at the point |
| 165 | TMEAN\_WS | ?? | Climate |  | Average of mean temperature at the watershed |
| 140 | TMIN\_AVE | ?? | Climate |  | Minimum temperature at the watershed |
| 69 | TMIN\_WS | ?? | Climate |  | Minimum temperature at the watershed |
| 118 | WDmax\_WS | ?? | Climate |  | Mean of max number of wet days at the watershed |
| 52 | XWD\_WS | ?? | Climate |  | Mean number of wet days at the watershed |
| 159 | Dams | ?? | DamsSpringsMines |  | Count of dams in the watershed |
| 158 | Mines | ?? | DamsSpringsMines |  | Count of mines in the watershed |
| 110 | ECO3 | ?? | Ecoregion |  | Eco Region level 3 \(number\) of the point |
| 74 | Eco3\_PT | ?? | Ecoregion |  | Eco Region level 3 \(number\) of the point |
| 111 | ECO4 | ?? | Ecoregion |  | Eco Region level 4 of the point |
| 75 | ER13 | ?? | Ecoregion |  | Is the level 3 ecoregion number 23? \(Y or N\) |
| 57 | LPREM\_mean | ?? | Geology |  | Mean of hydraulic condition in the watershed |
| 89 | PCT\_SEDIM | % | Geology |  | Percentage of watershed that is Sedimentary geology type \(geology type number 5\) |
| 76 | Vol\_ave | ?? | Geology |  | Mean of volcanic raster in the watershed |
| 161 | AG\_WS | % | Landcover |  | Percent ag landcover of the watershed |
| 77 | alru\_dom | % | Landcover |  | Percent of Alru landcover in the watershed |
| 78 | Evergr\_ave | % | Landcover |  | Percent of Evergreen landcover in the watershed |
| 79 | EVI\_AveAve | ?? | Landcover |  | Mean of Evi\_ave in the watershed |
| 58 | EVI\_MaxAve | ?? | Landcover |  | Mean of Evi\_max in the watershed |
| 147 | EVI\_MAX\_AVE | ?? | Landcover |  | Mean of Evi\_max in the watershed |
| 160 | Urban\_WS | % | Landcover |  | Percent urban landcover of the watershed |
| 151 | AreaKM | ?? | Metrics |  | Area of the watershed in sq km |
| 90 | AREA\_SQKM | ?? | Metrics |  | Area of the watershed in sq km |
| 81 | AWC\_soil | ?? | Metrics |  | Soil Water Capacity across the watershed |
| 104 | Bdh\_Ave | ?? | Metrics |  | Soil bulk density across the watershed |
| 64 | BDH\_AVE | ?? | Metrics |  | Soil bulk density across the watershed |
| 105 | BFI\_WS | ?? | Metrics |  | Base Flow Index across the watershed |
| 60 | CaO\_Mean | ?? | Metrics |  | Calcium Oxide average across the watershed |
| 87 | Db3rdbar | ?? | Metrics |  | Soil Bulk Density across the watershed |
| 150 | DD\_LAT\_Y | ?? | Metrics |  | Latitude of the point |
| 133 | east | ?? | Metrics |  | Does the poitn fall in an eastern Oregon ecoregion |
| 149 | ELEV\_MEAN | m | Metrics |  | Mean elevation across the watershed |
| 148 | ELEV\_MIN | m | Metrics |  | Average of min elevation in the watershed |
| 98 | ELEV\_RANGE | m | Metrics |  | Range between max and min elevations |
| 109 | ELEV\_SITE | m | Metrics |  | Elevation of the point |
| 134 | elev\_sqrt | ?? | Metrics |  | Square root of elevation at the point |
| 117 | ELEV\_WS | m | Metrics |  | Mean elevation across the watershed |
| 126 | ELVcv\_PT | ?? | Metrics |  | Square Root of topo value at the point |
| 96 | ELVmax\_WS | m | Metrics |  | Maximum elevation in the watershed |
| 127 | ELVmean\_WS | m | Metrics |  | Mean elevation across the watershed |
| 168 | ELVmean\_WS- same as MMI | m | Metrics |  | Mean elevation across the watershed |
| 97 | ELVmin\_WS | m | Metrics |  | Minimum elevation in the watershed |
| 82 | GW\_P\_Sp\_Mx | ?? | Metrics |  | Ground Water Index across the watershed |
| 86 | Kfact | ?? | Metrics |  | Soil Erodibility across the watershed |
| 162 | KFACT | ?? | Metrics |  | Soil Erodibility across the watershed |
| 65 | KFCT\_AVE | ?? | Metrics |  | Soil Erodibility across the watershed |
| 106 | Lat\_Dec | ?? | Metrics |  | Latitude of the point |
| 137 | LOG\_KM2 | ?? | Metrics |  | Log10 of watershed area |
| 114 | LOG\_XP\_PT | ?? | Metrics |  | Mean precip at the point |
| 130 | long | ?? | Metrics |  | Longitude of the point |
| 107 | Long\_Dec | ?? | Metrics |  | Longitude of the point |
| 61 | MgO\_Mean | ?? | Metrics |  | Magnesium Oxide average across the watershed |
| 94 | New\_Lat | ?? | Metrics |  | Latitude of the point |
| 93 | New\_Long | ?? | Metrics |  | Longitude of the point |
| 91 | N\_MEAN | ?? | Metrics |  | Average of Total Nitrogen across the watershed |
| 84 | Pct\_Alfi | % | Metrics |  | Percent alfi soils in the watershed |
| 92 | P\_MEAN | ?? | Metrics |  | Average of Total Phosphorus across the watershed |
| 100 | PPT\_00\_09 | ?? | Metrics |  | Precip at the point |
| 131 | precip | ?? | Metrics |  | Precip at the point based on the Predator layers |
| 59 | PRMH\_AVE | ?? | Metrics |  | Permeability across the watershed |
| 95 | SITE\_ELEV | m | Metrics |  | Elevation of the point |
| 62 | S\_Mean | ?? | Metrics |  | Average of Total Sulfur across the watershed |
| 83 | SOC | ?? | Metrics |  | Soil Organic Carbon across the watershed |
| 103 | Sq\_km | ?? | Metrics |  | Area of the watershed in sq km |
| 125 | SQ\_KM | ?? | Metrics |  | Area of the watershed in sq km |
| 115 | SQRT\_TOPO | ?? | Metrics |  | Square root of topo from the line shapefile |
| 112 | SUMMER | ?? | Metrics |  | Summer stream temp at the point |
| 132 | temp | ?? | Metrics |  | Temp at the point based on the Predator layers |
| 99 | TEMP\_00\_09 | ?? | Metrics |  | Temperature at the point |
| 80 | TP\_Mean | ?? | Metrics |  | Average of Total Phosphorus across the watershed |
| 63 | UCS\_Mean | ?? | Metrics |  | Uniaxial compressive strength across the watershed |
| 85 | Wb\_mx\_area | ?? | Metrics |  | Area of the largest waterbody in the watershed |
| 113 | WINTER | ?? | Metrics |  | Winter stream temp at the point |
| 167 | WSA\_SQKM | ?? | Metrics |  | Area of the watershed in sq km |
| 154 | BLMown | % | Ownership |  | Percent BLM ownership of the watershed |
| 155 | Privown | % | Ownership |  | Percent Private ownership of the watershed |
| 108 | NHDSLOPE | ?? | Slope |  | NHD Plus slope value taken from the nearest stream segment |
| 88 | slpavg | ?? | Slope |  | Mean slope of the watershed |
| 26 | CanalDensCat | km/km2 | StreamCAT |  | Density of NHDPlus line features classified as canal, ditch, or pipeline within the catchment \(km/ square km\) |
| 27 | CanalDensWs | km/km2 | StreamCAT |  | Density of NHDPlus line features classified as canal, ditch, or pipeline within the upstream watershed \(km/ square km\) |
| 5 | CaOWs | % | StreamCAT |  | Mean % of lithological calcium oxide \(CaO\) content in surface or near surface geology within watershed |
| 1 | CatAreaSqKm | sqkm | StreamCAT |  | Area of local NHDPlus catchment \(square km\) |
| 25 | DamDensCat | dams/km2 | StreamCAT |  | Density of georeferenced dams within catchment \(dams/ square km\) based on the National Inventory of Dams \(https://catalog.data.gov/dataset/national-inventory-of-dams\) |
| 2 | ElevCat | m | StreamCAT |  | Mean catchment elevation \(m\) |
| 10 | MAST\_2008 | C | StreamCAT |  | Predicted mean annual stream temperature \(Jan-Dec\) for year 2008 |
| 11 | MAST\_2009 | C | StreamCAT |  | Predicted mean annual stream temperature \(Jan-Dec\) for year 2009 |
| 12 | MAST\_2013 | C | StreamCAT |  | Predicted mean annual stream temperature \(Jan-Dec\) for year 2013 |
| 13 | MAST\_2014 | C | StreamCAT |  | Predicted mean annual stream temperature \(Jan-Dec\) for year 2014 |
| 29 | MineDensWs | mines/sq km | StreamCAT |  | Density of mine sites within watershed \(mines/square km\) |
| 14 | MSST\_2008 | C | StreamCAT |  | Predicted mean summer stream temperature \(July-Aug\) for year 2008 |
| 15 | MSST\_2009 | C | StreamCAT |  | Predicted mean summer stream temperature \(July-Aug\) for year 2009 |
| 16 | MSST\_2013 | C | StreamCAT |  | Predicted mean summer stream temperature \(July-Aug\) for year 2013 |
| 17 | MSST\_2014 | C | StreamCAT |  | Predicted mean summer stream temperature \(July-Aug\) for year 2014 |
| 18 | MWST\_2008 | C | StreamCAT |  | Predicted mean winter stream temperature \(Jan-Feb\) for year 2008 |
| 19 | MWST\_2009 | C | StreamCAT |  | Predicted mean winter stream temperature \(Jan-Feb\) for year 2009 |
| 20 | MWST\_2013 | C | StreamCAT |  | Predicted mean winter stream temperature \(Jan-Feb\) for year 2013 |
| 21 | MWST\_2014 | C | StreamCAT |  | Predicted mean winter stream temperature \(Jan-Feb\) for year 2014 |
| 6 | NCat | % | StreamCAT |  | Mean % of lithological nitrogen \(N\) content in surface or near surface geology within catchment |
| 38 | PctAg2006Slp10Cat | % | StreamCAT |  | % of catchment area classified as ag land cover \(NLCD 2006 classes 81-82\) occurring on slopes greater than or equal to 10% |
| 36 | PctAg2006Slp10Ws | % | StreamCAT |  | % of watershed area classified as ag land cover \(NLCD 2006 classes 81-82\) occurring on slopes greater than or equal to 10% |
| 39 | PctAg2006Slp20Cat | % | StreamCAT |  | % of catchment area classified as ag land cover \(NLCD 2006 classes 81-82\) occurring on slopes greater than or equal to 20% |
| 37 | PctAg2006Slp20Ws | % | StreamCAT |  | % of watershed area classified as ag land cover \(NLCD 2006 classes 81-82\) occurring on slopes greater than or equal to 20% |
| 9 | PctSalLakeWs | % | StreamCAT |  | % of watershed area classified as lithology type: saline like sediment |
| 31 | PctUrbHi2006Cat | % | StreamCAT |  | % of catchment area classified as developed, high-intensity land use \(NLCD 2006 class 24\) |
| 30 | PctUrbHi2006Ws | % | StreamCAT |  | % of watershed area classified as developed, high-intensity land use \(NLCD 2006 class 24\) |
| 41 | PctUrbHi2011Cat | % | StreamCAT |  | % of catchment area classified as developed, high-intensity land use \(NLCD 2011 class 24\) |
| 40 | PctUrbHi2011Ws | % | StreamCAT |  | % of watershed area classified as developed, high-intensity land use \(NLCD 2011 class 24\) |
| 33 | PctUrbLo2006Cat | % | StreamCAT |  | % of catchment area classified as developed, low-intensity land use \(NLCD 2006 class 22\) |
| 32 | PctUrbLo2006Ws | % | StreamCAT |  | % of watershed area classified as developed, low-intensity land use \(NLCD 2006 class 22\) |
| 43 | PctUrbLo2011Cat | % | StreamCAT |  | % of catchment area classified as developed, low-intensity land use \(NLCD 2011 class 22\) |
| 42 | PctUrbLo2011Ws | % | StreamCAT |  | % of watershed area classified as developed, low-intensity land use \(NLCD 2011 class 22\) |
| 35 | PctUrbMd2006Cat | % | StreamCAT |  | % of catchment area classified as developed, medium-intensity land use \(NLCD 2006 class 23\) |
| 34 | PctUrbMd2006Ws | % | StreamCAT |  | % of watershed area classified as developed, medium-intensity land use \(NLCD 2006 class 23\) |
| 45 | PctUrbMd2011Cat | % | StreamCAT |  | % of catchment area classified as developed, medium-intensity land use \(NLCD 2011 class 23\) |
| 44 | PctUrbMd2011Ws | % | StreamCAT |  | % of watershed area classified as developed, medium-intensity land use \(NLCD 2011 class 23\) |
| 3 | Precip8110Ws | mm | StreamCAT |  | PRISM climate data - 30-year normal mean precipitation \(mm\): Annual period: 1981-2010 within the watershed |
| 22 | RdCrsCat | xs/km2 | StreamCAT |  | Density of roads-stream intersections \(2010 Census Tiger Lines-NHD stream lines\) within catchment \(crossings/square km\) |
| 23 | RdCrsWs | xs/km2 | StreamCAT |  | Density of roads-stream intersections \(2010 Census Tiger Lines-NHD stream lines\) within watershed \(crossings/square km\) |
| 24 | RdDensWs | km/km2 | StreamCAT |  | Density of roads \(2010 Census Tiger Lines\) within watershed \(km/square km\) |
| 7 | RunoffWs | mm | StreamCAT |  | Mean runoff \(mm\) within watershed |
| 28 | SuperfundDensWs | sites/km2 | StreamCAT |  | Density of Superfund sites within watershed \(sites/square km\) |
| 8 | SWs | % | StreamCAT |  | Mean % of lithological sulfur \(S\) content in surface or near surface geology within watershed |
| 4 | Tmean8110Ws | C | StreamCAT |  | PRISM climate data - 30-year normal mean temperature \(°C\): Annual period: 1981-2010 within the watershed |
| 144 | MAXP\_AVE | ?? | Unknown |  | Precip max at the watershed |
| 157 | OilGasWells | ?? | Unknown |  | Count of oil and gas wells in the watershed |
| 128 | Slope\_WS | ?? | Unknown |  | Slope calculation based on \(Max elev - Min elev\)/FlowLengthMax |
| 101 | Variable | ?? | Unknown |  | Variable Description |
| 156 | OilFld\_Pct | % | UT\_Grazing |  | Percent Oil and Gas field of the watershed |

**Comment by alherca73** [comment]
Here's an excel. It's pretty much the dates and PRISM variables.
[predictors.xlsx](https://github.com/namc-utah/namc-bug-db/files/6032298/predictors.xlsx)
