### ISSUE TITLE
Predictor Script Demo

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#75]
@David-Fowler can we stub out some demonstration R code to prove how predictor calculation should work. My vision is described below. Ultimately @alherca73 will be responsible for implementing the predictor calculation functions.

## Script 1 - Site Predictor R Script

* This script is run when a new site gets created in the system (or a site is tweaked to a new location).
* Calculates all site level predictors for this new location. For now, the demo predictor functions will not perform any inner calculations. Perhaps they just log a message to the console output and then return a constant value back to the outer scripts. 
* Calls the bug API to get the site information (ID, name, point GeoJSON, catchment polygon GeoJSON)
* Each site predictor is calculated using a separate R function. The name of the function comes from an API call.
* The parent script is responsible for calling a bug API mutation to store the resultant predictor value in the database. (i.e. the inner predictor scripts should know nothing about the API. They take parameters and return the final predictor value. There are no internal bug API calls. But there might be external calls to services such as StreamCAT or Google Earth Engine.)

## Script 2 - Sample Predictor R Script

* This script is run when a new sample gets assigned an official site (i.e. during submission QA).
* Workflow is the same as script 1 except that the sample date is also needed to get the correct time-dependent datasets.

All code from the demo should be on GitHub for @alherca73 to pick up and run with.

FYI @Feldspar5 @courtwrightj01

**Comment by David-Fowler** [comment]
I think I will create a demo R repo for the lab where it can house broader ideas about how the lab as a whole uses R. Including:

- styling guides / formatting tool usage
- package creation / editing both with GitHub and CRAN backing
- core package usage which NAMC depends on
- how to setup unit testing
- etc.

I can put some of these docs in this repo (those not specific to the db API).

**Comment by philipbaileynar** [comment]
@David-Fowler has stubbed out the code here:

https://github.com/namc-utah/NAMCGeopa/blob/main/sudo_example.R
