### ISSUE TITLE
API endpoint arguments

### ISSUE THREAD

**Issue by David-Fowler** [namc-utah/namc-bug-db#77]
For consistency I think it would be nice to convert all non-paginating arguments (i.e. everything but limit and offset) to accept arrays/lists of values.

I just verified that I am picking the scalar/list format up via introspection and therefore I will allow the users on R to pass scalar or array values and internally they will get converted to arrays as needed. @philipbaileynar I will fix this from our earlier trial.

The naming of the endpoint arguments is currently following a plural format for those accepting arrays and singular for scalars. I am questioning if it would be better to keep them the same as the database fields (in scalar form) just for naming consistency and aiding those who may work with both. One less nuance that needs to be learned.

I will probably add intellisense helpers to the R end so maybe the above is unnecessary.

Open for comments / thoughts.

**Comment by philipbaileynar** [comment]
I like the consistency of naming all arguments the same as the database fields (i.e. using scalar naming).

I will talk to @MattReimer regarding having arguments that can be scalar or array. We might have to just take arrays and the R package encapsulate scalars on the way into the API call.

**Comment by David-Fowler** [comment]
I do not mind have R handle the scalar encapsulation. That is already added in. It was more the notion of some fields not accepting arrays and others not accepting them which is why I was proposing to accept them everywhere to limit potential confusion.
