### ISSUE TITLE
Nitrogen and Phosphorous Category?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#78]
@courtwrightj01 I will add "Total Nitrogen" and "Total Phosphorous" as predictors to the database.

1. What category should I assign these? "Water Quality"?
2. Are they temporal or static for an individual site?
3. How about the following for abbreviations?
    * "TotalN"
    * "TotalP"

**Comment by courtwrightj01** [comment]
Yes assign these as Water Quality. These are temporal. And the output names need to be TotalNitrogen and TotalPhosphorous

**Comment by philipbaileynar** [comment]
Total Nitrogen and Total Phosphorus are provided to NAMC from another lab. They will be imported through a CSV import process.

Note that PredictedPhosophorus, PredictedNitrogen PredictedSpecificConductance are metrics that are output from a model R script. The R script model that generates these is like an O2E or MMI model but instead of outputting a score, these R models output predicted concentrations of the aforementioned values.
