### ISSUE TITLE
Predictor Workflow

### ISSUE THREAD

**Issue by David-Fowler** [namc-utah/namc-bug-db#79]
I edited and cut the top section of the code block I pushed on Friday and am pasting it here for discussion. The proposal should fill in a missing piece of workflow logic to make sure predictors are calculated and updated when required while also allowing for the details of how the processes are executed to be flexible (i.e. fully automated, semi-automated or manual).

 I propose we have 5 predictor-states associated at the sample 
 level which are controlled via automatic database triggers. Processing at the 
 sample level guarantees that upon any change both temporal and non-temporal 
 predictors get calculated when needed. This requires a new field in the 
 sample table named "predictor_state" or something of that liking. 
 Proposed states are:
 
 1. "pending" - (default) new samples added to the db automatically get assigned
                 this state. When processing predictors associated
                 with the sample if the site level (non-temporal)
                 predictors already exist only sample level temporals are calculated.
                 
 3. "noModel" -  This state is determined after attempting to process 
                 the first time. If no site->model link exists in the 
                 database the script sets this state. It comes out of
                 this state following the "dirty" state logic below.               
                 
 2. "dirty" -    Any time a site's coordinates or catchment changes a db trigger
                 flags all samples associated with that site as
                 "dirty" thereby indicating to the script that all 
                 site and sample level predictors need to be 
                 recalculated and overridden. Another database trigger 
                 would trigger any time a new model is associated with 
                 a site or sample. This again would trigger a "dirty" state.
                 This model trigger is conservative and could cause
                 the recalculation of already valid predictors (as some
                models share predictors with others) but it would also
                 guarantee all predictors are up to date.
                 
 3. "complete" - Upon successfully processing a sample's predictors
                 without error this script marks the sample as complete.
                 
 4. "error"    - Upon this script failing to run due to some unknown
                 problem / error the sample gets marked as "error". This 
                 would trigger a notification to someone or at the
                 very least we have a query to get these problems
                 when they occur.

**Comment by Feldspar5** [comment]
David - would you please provide an example of a situation that would trigger the dirty state?  Set was in CA, but coordinates trigger NV model predictors?

**Comment by David-Fowler** [comment]
A dirty state would always follow after we already have predictors calculated for a site. At some point in time after the predictors were calculated we either decide to adjust the coordinates associated with that site OR add/replace a model associated with a site. The later would give us the flexibility to adjust and/or assign multiple models to a site at any point in time (even if it is just to do research or run a trial). The former would allow for customers coming back to us with "more accurate coordinates" of past sites (something that has happened occasionally).

In essence though, "dirty" gives us the flexibility of the unknown and allows our calculation processes to perform in those types of situations with requiring modification or special handling.

**Comment by Feldspar5** [comment]
Perhaps 'dirty' is not the ideal descriptor.  Or is that a proper db nomenclature use?

**Comment by David-Fowler** [comment]
It is kind of a coding nomenclature for something that has changed but not yet been dealt with. But the names are not that important so if there are more descriptive names that are more evident / obvious to everyone we should use them instead.

**Comment by David-Fowler** [comment]
I also did not explain database triggers in case we are not all familiar. They are bits of database code (like a stored procedure) tied directly to the database which are triggered automatically based on the trigger condition (i.e. table insert, table update, table delete etc.). By putting triggers on fields like "site coordinates", "site catchment" and the "site model" no matter where the change came from the database will have adjusted the predictor state. This prevents an external system from having to keep track of when things change (that external system currently is a human in the loop often times). It helps our database be the one source of truth for the state of the data and therefore allows any external process (i.e. calculation scripts) to easily identify what needs to be done.

**Comment by philipbaileynar** [comment]
Not all site predictors are needed for all sites. Not all sample predictors are needed for all samples. Which predictors are needed is controlled by models. Models relate to predictors.

So the question becomes, how do we know which models are needed for a sample (and by association, its site)? This could be controlled one of several ways:

* Associated models with boxes
* Associate models with samples
* Associate models with sites
* Associate models with customers
* Associate models with projects

Let's discuss in person...

**Comment by courtwrightj01** [comment]
Should be a combination of state and customer I think? Right now we use Box

**Comment by David-Fowler** [comment]
Your right Phillip and that is exactly how it is outlined in the code snippet (leaving out potentially other link to attach models to sites).

The above workflow was just for the triggering process and how to keep predictors up to date as fields change in the database. If we do expand to allow model relations beyond site->model (i.e. cust -> model, project -> model etc) I think additional update triggers at each of those points would be necessary as well.

How and were we store those model links is important and as of yet is not defined.

**Comment by philipbaileynar** [comment]
@David-Fowler we might not need to store the state of predictor values. We might be able to determine their state if we have the correct timestamps in place. i.e. 

* "stale" or "out of date" site predictors are those whose calculation predates the date when the site geometry was last changed.
* "stale" or "out of date" sample predictors are those whose calculation predates the date when the site geometry OR the sample date was changed.

**Comment by philipbaileynar** [comment]
ps I like the term "expired" rather than stale...

**Comment by philipbaileynar** [comment]
Notes from a productive meeting on this topic:

1. All models must have a polygon extent to which they apply. The polygon might represent a single or collection of states, an ecoregion or even a custom polygon. 
2. Customers can be associated with one or more models. These models are presented to the NAMC person who is quality controlling sample submissions as the "default" set of models to be calculated for all samples within a box. The NAMC person can add more models to this list (or in rare circumstances remove one of the default models if they are really sure.)
3. NAMC can add or remove models associated with a sample at any time. (i.e. months or years after a sample is processed someone might edit a sample and add associate with additional models to be run for the sample. This will queue any missing or expired predictors to be calculated).
3. Projects can be associated with models. 
4. The lab manager can potentially be the person who will run the predictor calculation R script after they finish quality controlling one or more submissions. 
5. The longterm vision is that the predictor calculation script can be fully automated. For the foreseeable future it will be run manually.


![workflow](https://docs.google.com/drawings/d/e/2PACX-1vTxLCYQwT0b88IDfx4lAIxRiklZknDkFZxdEqNXWyG2i6Sl13lXvv3HPuu6YfE5WGm0uOZs542ugifs/pub?w=1464&h=840)

**Comment by David-Fowler** [comment]
I would recommend we constrain item 3 above to only occur during sample processing (if that is even needed). Once sample processing is complete and the report is sent out the only way to associate new models to a sample would be through item number 4 (i.e. sample level ad-hoc adjustments should only be done through a project). This would not affect the ability to add models to Customers or changing the Model's polygon.

The reason for this is to make sure the reasoning for any model assignment is transparent and that there is always an endpoint to go (i.e. Project, Model (via its polygon) or Customer). A model assigned directly to a sample can only relate back to a box (i.e. a Customer) where in many (if not all) cases after sample processing is complete that would not be the case. Since projects can be hierarchical it does not limit the ability to have multiple models sub-divided under a single parent project (that detail is less important now).

The question is do we even need Models directly assigned to Samples? If we do then I believe we must make sure those assignments exist only in the context of box processing (i.e. we are delivering the results back to the customer associated with the box).

**Comment by Feldspar5** [comment]
I think I agree with David.  Samples/boxes need a model run shortly after processing complete.  Any additional model assignations after that initial run would come as part of a project (often research related).

**Comment by philipbaileynar** [comment]
Based on @David-Fowler and @Feldspar5 latest comments I am leaning towards associating models with boxes during sample submission review. The same "customer default models" concept will still apply. But the data will be simpler if we link boxes to models than (the more numerous) samples to models. 

Projects will still link to models.

Here's a summary of the related tables:

![models](https://docs.google.com/drawings/d/e/2PACX-1vTB2pvjRHRkHmSXhhW2r7qenyrP6I8VtQbqYiT-seU8xreylBIhPsU8eabzsD-I8jgqDCo72hZV3xwT/pub?w=1653&h=774)

**Comment by Feldspar5** [comment]
There are problems with that though: OR, WY, CO for example.  A single Box from Oregon cannot be assigned to an OR model, because the samples within often span 2 or 3 of the models in that state.  Or am I misunderstanding?

**Comment by David-Fowler** [comment]
If the default model polygons match and the models are assigned to the customer already then no overriding at the box processing stage would be needed. It would just process automatically. If the polygons attached to the models are not accurate or we want to override them that is when we would need to add additional at the box processing stage.

The above does not discuss applying at the sample or box level bit perhaps the above understanding will help lead is to what we need.

**Comment by David-Fowler** [comment]
Actually do we not just want any sample / site that is within a models polygon to automatically get predictors for that model no matter if they are linked through customer or not.

The polygons could catch most everything and these extra links through box or sample, customer, project etc would only be necessary for ones that don't already fit.

**Comment by philipbaileynar** [comment]
@David-Fowler I think you are you suggesting:

1. models  are associated with customers
2. models are associated with projects
3. We use the model polygon to filter out which samples are relevant for a particular model based on sample locations.

And therefore we don't need to associate models with boxes or samples. We know which models are needed for each sample based on which customer its for and where the sample is located.

Question:
How do we handle changes in models over time? e.g. customer X wants models A, B, C in 2018 but for 2019 they just want models C and D. Surely this would be better handled by associating models with boxes, using the customer associations as the default.

Upon QC of a box, the lab manager sees the proposed default customer models and can then add or remove any before the resultant list of models is stored with the box.

**Comment by Feldspar5** [comment]
A model does not change; a new model is created.  For example: CO EDAS 2009, CO EDAS 2017.  The older version is eventually abandoned as the state no longer supports it.  

Per David's comments about automatically getting predictors: this is something to which we have not committed.  ~50% of samples that enter lab never get a model applied.  Predictors would mean delineating first.  This is a decision on which I have reserved judgement until Alex and Kristen get that process so smoothed out that it is no longer a burden.

**Comment by philipbaileynar** [comment]
Closing this outdated issue now that @alherca73 has done a great job of coding the functions. And we have prototype code for reading and writing predictors to the database. @David-Fowler will finalize this code.
