### ISSUE TITLE
Model Names

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#80]
@courtwrightj01 can I get the "plain English" names for each of these model please? For example PIBO would be "USFS Pacfish/Infish Biological Opinion".

Also... can you confirm if this is the exhaustive list of all models needed in the new system? Are there any others? If so, I please provide an abbreviation and name for these missing models.

| model\_name |
| :--- |
| EC12 |
| TNTP12 |
| CSCI |
| StreamTemp12 |
| CO |
| NVMMI |
| OR\_MWCF |
| OR\_WCCP |
| PIBO |
| New UTOE |
| Anthropogenic |
| AREMP2014MMI |
| AREMP2014OE |

**Comment by courtwrightj01** [comment]
Here is a list of all models and the WQ and Bug end points needed. It might be best to discuss some of this. For example, the bug end point needs not only the model used but the ecoregion that was used to set the thresholds for the model.

**Comment by courtwrightj01** [comment]
Sorry, I forgot to populate one of the worksheets. Here is a revised file
