### ISSUE TITLE
AREMP Model Type

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#81]
@Feldspar5 you just emailed that the following models are missing from @courtwrightj01 spreadsheet. Can you confirm:

1. The WY and westwide models are all O2E?
2. What is the model type for AREMP - O2E, MMI or hybrid (like the CA_CSCI)?

**Comment by Feldspar5** [comment]
The WY and WestWide models are both OE.  

AREMP is really 2 models - MMI and OE; we were being sloppy calling it one.
