### ISSUE TITLE
Customer Hierarchy

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#84]
So far I have just populated the new database with all the current customers. Now I need to build the customer hierarchy that binds them together as parents and child "entities". The customer records in PilotDB suggest the following hierarchy:

* BLM Federal
    * BLM State Offices
        * BLM Field Offices
* USFS Federal
    * USFS Regions
        * USFS District or forest offices
    * All other Exceptions (e.g.  USFS Lake Tahoe Basin Management Unit)
* NPS
    * national parks
 * All other customers are top level with no parent.

There are some other potential relationships such as several departments of fish and game, and departments of water quality, but these are state agencies that I believe don't have a relationship between states?

Am I missing anything?

**Comment by Feldspar5** [comment]
Many of the NPS partners we have are units that work across Parks (Mojave Desert Network, Southern Colorado Plateau Network, etc.), although this does not change the parent as NPS.  We also work with USGS, USFWS, USBOR so perhaps we need to go up in lineage to USDA, USDI, etc.?

**Comment by David-Fowler** [comment]
Most all of this can be pulled from the customerTypeSpecial table that I don't believe we imported into the new db but is part of the frontend BugLab database backup @philipbaileynar has. All federal agencies up the hierarchy are listed in that table even those we do not have as customers. A few may be out of date or merged but the majority should exist as is.

This was done such that we have consistent agency naming conventions and are not relying on the new customer's input. This table can be replaced with a hierarchical set of drop-down / fill in fields for new customer's as they come in. It would be beneficial to make sure our agency names have consistent naming conventions.

**Comment by Feldspar5** [comment]
Our cust naming conventions are so not standardized; they are terrible.

**Comment by David-Fowler** [comment]
Even for the agencies? Please look through the TypeCustomerSpecial table in the BugLab db. There was a major effort to standardize all agency names and what is currently custId. Most was pulled and adopted from the agencies themselves but order and placement of nouns within the names I thought was all uniform; at least within each separate top-level parent agency.

I think it is at least a place to look at to determine what we can do better this time around.

**Comment by Feldspar5** [comment]
David - sorry I let this slip.  I just reviewed the customers in that table and they have been standardized and look fine.  I must be thinking about non-agency customer IDs: private, NGO, tribal, university etc.  These could likely be standardized as well.  "Ecorp Consulting Inc." and " Henrys Fork Foundation and USU Fish Ecology Laboratory"  are custids (there are many others)!

**Comment by philipbaileynar** [comment]
Fina
