### ISSUE TITLE
Locked Projects

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#85]
We are encouraging widespread use of projects in the new system. NAMC staff will have a user interface for creating a project and associating samples with it. The user interface will also have the ability to delete projects for situations where:

1. a project is temporary and no longer needed.
2. a mistake was made creating or editing a project.

We also have some very important projects for recurring customers and that span multiple years. We don't want someone accidentally deleting these extremely important projects ("oops I just deleted AIM!").

I am proposing an `is_locked` boolean field on the `sample.projects` table. We will set this field to true for important projects so that no one can delete them through the user interface. Only the system admin will be able to delete them via the database. Users will not have the ability to change the is_locked field through the user interface. This is essentially a hidden feature to prevent data loss.

Thoughts?

(Note that deleting a project doesn't delete the associated samples. It merely deletes the association between the samples and the project. This could still cause a lot of problems if an important project were accidentally deleted and needed to be recreated.)

**Comment by courtwrightj01** [comment]
Hmm… this seems a bit overkill. If we delete AIM it is really easy to recreate it. What I don’t want is not to be allowed to remove samples from the AIM project. Would this lock prevent deletion of the project altogether and edits of associated samples or just the former?

Jennifer

**Comment by Feldspar5** [comment]
We are talking about deletion of the project association and not the sample data, correct?  If that is the case, then I echo Jennifer in that I think this is too much security.  Projects will be helpful for us in the future, but they do not need the level of admin overwatch is_locked would create.

**Comment by David-Fowler** [comment]
Yes. Only project associations and definitions would be part of project deletions. So I too agree is_locked is unnecessary. The very worst case scenario where the project definition (either manually selected list of samples or polygons defining it) are deleted and the original parameters are difficult to rebuild we can always pull it from a database backup. But it probably won't ever come to that.
