### ISSUE TITLE
Shared metric formulae

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#88]
Multiple metrics can refer to the same formula. The following "calculations" were coped from the Excel report. 

What is the level of formula reuse? In the screenshot below, are the metrics that measure "abundance" all referring to the same formula? Or are they different because they are measuring abundance of different traits?

<img width="1332" alt="Screen Shot 2021-03-05 at 3 13 44 PM" src="https://user-images.githubusercontent.com/8645379/110184758-85197700-7dc5-11eb-8fd2-d60f73716477.png">

**Comment by David-Fowler** [comment]
I will pass you the specific tables for those function - metric relations. But yes for the most part they are all referring to the same function. This is also why the metric to multi-taxa relationship should be required as that really is the definition of what goes into the function while also providing the necessary documtation .
