### ISSUE TITLE
Model Polygons

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#89]
I need a ShapeFile with a polygon for each model. The specifications are:

1. One record for each of the models listed below.
2. Can be a single or multipart polygon.
3. Single attribute that is the model abbreviation that matches one the items below:
4. Can be any spatial reference. WGS84 (EPSG: 4326 preferred).

| abbreviation | model\_name |
| :--- | :--- |
| AREMP MMI | USFS Aquatic and Riparian Effectiveness Monitoring Program MMI |
| AREMP O2E | USFS Aquatic and Riparian Effectiveness Monitoring Program O2E |
| CA\_CSCI | California Stream Condition Index \(O/E and Multimetric Index\) |
| CO-EDAS2017 - Biotype 1 | CO Ecological Data Application System Multimetric Index - Biotype 1 |
| CO-EDAS2017 - Biotype 2 | CO Ecological Data Application System Multimetric Index - Biotype 2 |
| CO-EDAS2017 - Biotype 3 | CO Ecological Data Application System Multimetric Index - Biotype 3 |
| ColumbiaRiverBasin\_PIBO | USFS Pacfish/Infish Biological Opinion O/E |
| EC12 | Specific Conductance Olson 2012 |
| NV\_MMI | NV Multimetric Index |
| OR\_MarineWesternCoastalForest | OR MarineWesternCoastalForest O/E |
| OR\_NorthernBasinRange | OR NorthernBasinRange O/E Null Model |
| OR\_WesternCordillera\_ColumbiaPlateau | OR WesternCordillera ColumbiaPlateau O/E |
| StreamTemp12 | August Mean Stream Temperature Hill 2012 |
| TN12 | Total Nitrogen Olson 2012 |
| TP12 | Total Phosphorus Olson 2012 |
| UT\_DEQ\_2015 | UT Department of Environmental Quality O/E |
| Westwide2018\_OtherEcoregions | Westwide O/E |
| WestWide\_eastern\_xeric\_plains | WestWide\_eastern\_xeric\_plains |
| WY2018\_BIGHORN BASIN FOOTHILLS | WY 2018 Big Horn Basin Foothills O/E |
| WY2018: Black hills | WY2018: Black hills |
| WY2018\_GRANITIC MNTS | WY Granite Mountains 2018 O/E |
| WY2018\_HIGH VALLEYS | WY 2018 High Valleys O/E |
| WY2018\_NE PLAINS | WY 2018 NE Plains O/E |
| WY2018\_SEDIMENTARY MNTS | WY 2018 Sedimentary Mountains O/E |
| WY2018\_SE PLAINS | WY 2018 SE Plains O/E |
| WY2018\_SOUTHERN ROCKIES | WY 2018 southern Rockies O/E |
| WY2018\_SOUTH FH LARAMIE RANGE | WY 2018 South FH Laramie Range O/E |
| WY2018: volcanic mountains and valleys | WY2018: volcanic mountains and valleys |
| WY2018\_WYOMING BASIN | WY 2018 Wyoming Basin O/E |

**Comment by alherca73** [comment]
Working on this. Just a had meeting with Kristin about how to work the CO models... We may have found a solution.

**Comment by alherca73** [comment]
The zip file exceeded Github's limit. Sent via email.

**Comment by philipbaileynar** [comment]
Unfortunately the ShapeFile has several problems. We can meet to discuss if you want. 

# 1. Self Intersecting Geometries

The ShapeFile would not load in QGIS, so I loaded it into ArcGIS and ran the repair geometry tool. It highlighted several self intersecting geometries.

<img width="645" alt="Screen Shot 2021-03-17 at 11 47 54 AM" src="https://user-images.githubusercontent.com/8645379/111522152-33eb7a80-8717-11eb-9760-4f9e1333dae2.png">

# 2. Polygon Slivers

There are several places where the boundaries do not align properly. We could overlook this, but I don't think we should. Now is the time to invest in getting this layer correct. There's a non-zero chance that someone will collect a sample right in the gap between these polygons!

<img width="1061" alt="Screen Shot 2021-03-17 at 11 47 40 AM" src="https://user-images.githubusercontent.com/8645379/111523177-34d0dc00-8718-11eb-8e30-93db50d006ef.png">

# 3. Detail

There are areas in Colordao with immense detail. I don't know how these layers were produced, but if they were just generated by thresholding rasters then we might not need all the resultant detail. Many of the small polygons are delineating hillslopes, and not distinguishing streams of different types. Perhaps we can discuss.

<img width="1061" alt="Screen Shot 2021-03-17 at 11 46 30 AM" src="https://user-images.githubusercontent.com/8645379/111523558-9ee98100-8718-11eb-9538-950ed935ae2b.png">

**Comment by philipbaileynar** [comment]
Closing this outdated issue. 

The Colorado polygons still have some issues, but @Feldspar5 has requested that this be put on hold.
