### ISSUE TITLE
Please review email about geojsons

### ISSUE THREAD

**Issue by alherca73** [namc-utah/namc-bug-db#94]
@philipbaileynar, did you have a chance to take a look at my email about geojsons?

**Comment by philipbaileynar** [comment]
@alherca73 please try:

1. adding the Shapefile to QGIS
2. right click on the layer and choose "Export"
3. change the data format to GeoJSON.
4. Save the file.

Does that fix the problem?


<img width="860" alt="Screen Shot 2021-03-19 at 10 09 13 AM" src="https://user-images.githubusercontent.com/8645379/111817544-5c9c7d00-889b-11eb-917f-d6432d5bc192.png">
<img width="703" alt="Screen Shot 2021-03-19 at 10 09 31 AM" src="https://user-images.githubusercontent.com/8645379/111817548-5e664080-889b-11eb-846e-2fd87566f4ca.png">

**Comment by alherca73** [comment]
I think it will be better if we discuss this on a meeting. More than likely the text in my email did not make much sense.
