### ISSUE TITLE
Model Extents

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#95]
I now have @kemaier latest model extent polygons (provided 25 Mar 2021) imported into the new database. For the remaining models (e.g. Alaska, Nevada, California) I am using the polygons from the corresponding state(s).

This just leaves two models without a polygon extent:

* WestWide2018_OtherEcoregions
* WestWide2018_XericEasternPlains

@kemaier are you able to provide polygons for these two models please? If so, then add them to your existing ShapeFile and re-send.

FYI @Feldspar5

**Comment by Feldspar5** [comment]
Welcome to GitHub, Kristin.  And thanks for sorting out the model regions - especially the CO model.  Please let me know if you have any questions about the WestWide model regions.  Phillip - you are correct about the all-state regions you list.

**Comment by kemaier** [comment]
The excel sheet I was working off of (AllModelDetails.xlsx) did not have model extent locations listed for the Westwide models. Do we have those hidden somewhere?

**Comment by philipbaileynar** [comment]
@Feldspar5 are the westwide models defined by a collection of US States, or by a custom polygon (that @kemaier can provide)?

**Comment by Feldspar5** [comment]
The WW model is used in all parts of the following states: WA, MT, ID, WY, OR, CA, NV, UT, CO, AZ, NM.  The region is subdivided into 2 regions that determine thresholds (like the CO MMI): Eastern Xeric Plains and everything else.

**Comment by philipbaileynar** [comment]
@kemaier can you please add these two polygons to your Shapefile and re-send. 

State boundaries are available from the [US Census Bureau](https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html) if you need them.

**Comment by philipbaileynar** [comment]
OK we now have model polygons for all models. Closing this issue. Nice work @kemaier!

<img width="1222" alt="Screen Shot 2021-03-25 at 3 10 24 PM" src="https://user-images.githubusercontent.com/8645379/112550252-549d7b00-8d7c-11eb-9a86-a949564f9001.png">
