### ISSUE TITLE
Latest front end database

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/namc-bug-db#96]
Hey @David-Fowler , just a reminder to please provide the latest copy of the front end database.

**Comment by philipbaileynar** [comment]
Thanks for this!

Question... why are there only 484 records in `BugLab.SiteInfo`? I thought this table would have every historical site in it?

**Comment by David-Fowler** [comment]
The siteinfo table on this database only holds new sites for samples which have not been completely processed via the lab (complete = False in bugboxes). During the sample completion process where samples are sent from this database to PilotDB any new sites relating to the samples are also transferred and then deleted from the BugLab database.

Historically, one reason for this was such that we did not pollute PilotDB with incomplete data and data that may or may not ever get completed (i.e. OnHold boxes etc).

So, the complete set of sites should be a union of both the PilotDB and BugLab database SiteInfo tables.
